-- If the TC machine is enabled, it will automatically disable Config.Shop and Config.SellShop. The GradingShop will work independently.
-- tc machine will still take info from Config.Shop = items and Config.SellShop = items
Config.TcMachine = {
    enabled = false,                                     -- toggles the tc machine on/off
    prop = 'jim_g_trading_cards_vending_machine',        -- prop model for the tc machine
    locations = {
        vector4(25.7054, -1349.6705, 28.2207, 359.99),
        vector4(372.4957, 323.8303, 102.4551, 344.99),
        vector4(644.6331, 264.1503, 102.1970, 239.99),
        vector4(1165.8815, -325.8591, 68.1143, 9.99),
        vector4(-58.3816, -1749.0130, 28.2137, 229.99),
        vector4(-3037.4238, 586.9555, 6.6934, 109.99),
        vector4(-2551.5388, 2315.3811, 32.0863, 184.99),
        vector4(-97.7334, 6406.1025, 30.5165, 225.0),
        vector4(1738.5682, 6407.3007, 33.8587, 334.99),
        vector4(2684.9636, 3287.1555, 54.3209, 59.99),
        vector4(1183.6961, 2702.7709, 37.0359, 0.0),
        vector4(-147.7658, 229.5478, 93.8327, 179.99)
    }
}

-- if grading shop is FALSE empty_grading_case item will work on its own as a useable item
Config.GradingShop = {
    enabled = true,                                      -- toggles the grading shop on/off
    currency = 'bank',                                   -- currency name used for payouts
    location = vector4(-143.66, 222.47, 93.93, 0.62),    -- ped spawn position
    pedModel = 's_m_m_lathandy_01',                      -- ped model for the buyer
    scenario = 'WORLD_HUMAN_CLIPBOARD',                  -- idle scenario played by the ped
    blipenabled = true,                                  -- toggles the sell shop on/off
    blipname = 'Trading Card Shop',                       -- blip name
    blipid = 671,                                         -- blip id 
    scale = 0.8,                                         -- blip scale
    blipcolor = 46,                                      -- blip color     
    prices = {
        Normal      = { price = 500,    timeSec = 5 },
        Uncommon    = { price = 1000,   timeSec = 5 },
        Rare        = { price = 1500,   timeSec = 5 },
        Epic        = { price = 2000,   timeSec = 5 },
        Legendary   = { price = 3000,   timeSec = 5 },
        Holo        = { price = 4000,   timeSec = 5 },
        OriginalArt = { price = 5000,   timeSec = 5 }
    }
}

-- shop to buy items from can be turn false to add item to you own selling shop or crafting script
Config.Shop = {
    enabled = true,                                    -- toggles the sell shop on/off
    currency = 'bank',                                 -- currency name used for payouts
    location = vector4(-150.99, 222.25, 93.94, 273.17), -- ped spawn position
    pedModel = 'u_m_y_rsranger_01',                    -- ped model for the buyer
    scenario = 'WORLD_HUMAN_CLIPBOARD',                -- idle scenario played by the ped
    blipenabled = false,                                -- toggles the blip on/off
    blipname = 'Trading Card Shop',                    -- blip name
    blipid = 52,                                       -- blip id 
    scale = 0.4,                                       -- blip scale
    blipcolor = 5,                                     -- blip color     
    cooldownSeconds = 1,                               -- cooldown between purchases in seconds dont touch it really
    maxBasketItems = 60,                               -- max items allowed in a single purchase
    items = {
        -- _card_pack
        { item = '_card_pack',                              label = ' Pack',                            price = 5000,    category = ' Series',              image = '_card_trading_cards_pack.webp' },
        { item = '_card_booster_box',                       label = ' Booster Box',                     price = 25000,    category = ' Series',              image = '_card_trading_cards_booster_box.webp' },
        -- jg_warlords
        { item = 'jg_warlords_pack',                              label = 'JG Warlords Pack',                            price = 5000,    category = 'JG Warlords Series',       image = 'jg_warlords_trading_cards_pack.webp' },
        { item = 'jg_warlords_pack_mythic',                       label = 'JG Warlords Mythic Pack',                     price = 7500,    category = 'JG Warlords Series',       image = 'jg_warlords_trading_cards_pack_mythic.webp' },
        { item = 'jg_warlords_pack_legendary',                    label = 'JG Warlords Legendary Pack',                  price = 10000,    category = 'JG Warlords Series',       image = 'jg_warlords_trading_cards_pack_legendary.webp' },
        { item = 'jg_warlords_booster_box',                       label = 'JG Warlords Booster Box',                     price = 25000,    category = 'JG Warlords Series',       image = 'jg_warlords_trading_cards_booster_box.webp' },
        { item = 'jg_warlords_booster_box_mythic',                label = 'JG Warlords Mythic Booster Box',              price = 37500,   category = 'JG Warlords Series',       image = 'jg_warlords_trading_cards_booster_box_mythic.webp' },
        { item = 'jg_warlords_booster_box_legendary',             label = 'JG Warlords Legendary Booster Box',           price = 50000,   category = 'JG Warlords Series',       image = 'jg_warlords_trading_cards_booster_box_legendary.webp' },
        -- -- jg_shin_genesis
        -- { item = 'jg_shin_genesis_pack',                          label = 'JG Shin Genesis Pack',                        price = 1000,    category = 'JG Shin Genesis Series',   image = 'jg_shin_genesis_trading_cards_pack.webp' },
        -- { item = 'jg_shin_genesis_pack_mythic',                   label = 'JG Shin Genesis Mythic Pack',                 price = 2200,    category = 'JG Shin Genesis Series',   image = 'jg_shin_genesis_trading_cards_pack_mythic.webp' },
        -- { item = 'jg_shin_genesis_pack_legendary',                label = 'JG Shin Genesis Legendary Pack',              price = 3500,    category = 'JG Shin Genesis Series',   image = 'jg_shin_genesis_trading_cards_pack_legendary.webp' },    
        -- { item = 'jg_shin_genesis_booster_box',                   label = 'JG Shin Genesis Booster Box',                 price = 5800,    category = 'JG Shin Genesis Series',   image = 'jg_shin_genesis_trading_cards_booster_box.webp' },
        -- { item = 'jg_shin_genesis_booster_box_mythic',            label = 'JG Shin Genesis Mythic Booster Box',          price = 13000,   category = 'JG Shin Genesis Series',   image = 'jg_shin_genesis_trading_cards_booster_box_mythic.webp' },
        -- { item = 'jg_shin_genesis_booster_box_legendary',         label = 'JG Shin Genesis Legendary Booster Box',       price = 20800,   category = 'JG Shin Genesis Series',   image = 'jg_shin_genesis_trading_cards_booster_box_legendary.webp' },
        -- -- jg_void_ether
        -- { item = 'jg_void_ether_pack',                            label = 'JG Void Ether Pack',                          price = 1000,    category = 'JG Void Ether Series',     image = 'jg_void_ether_trading_cards_pack.webp' },
        -- { item = 'jg_void_ether_pack_mythic',                     label = 'JG Void Ether Mythic Pack',                   price = 2200,    category = 'JG Void Ether Series',     image = 'jg_void_ether_trading_cards_pack_mythic.webp' },
        -- { item = 'jg_void_ether_pack_legendary',                  label = 'JG Void Ether Legendary Pack',                price = 3500,    category = 'JG Void Ether Series',     image = 'jg_void_ether_trading_cards_pack_legendary.webp' },
        -- { item = 'jg_void_ether_booster_box',                     label = 'JG Void Ether Booster Box',                   price = 5800,    category = 'JG Void Ether Series',     image = 'jg_void_ether_trading_cards_booster_box.webp' },
        -- { item = 'jg_void_ether_booster_box_mythic',              label = 'JG Void Ether Mythic Booster Box',            price = 13000,   category = 'JG Void Ether Series',     image = 'jg_void_ether_trading_cards_booster_box_mythic.webp' },
        -- { item = 'jg_void_ether_booster_box_legendary',           label = 'JG Void Ether Legendary Booster Box',         price = 20800,   category = 'JG Void Ether Series',     image = 'jg_void_ether_trading_cards_booster_box_legendary.webp' },
        -- -- jg_sands_of_eternity
        -- { item = 'jg_sands_of_eternity_pack',                     label = 'JG Sands of Eternity Pack',                   price = 1000,    category = 'JG Sands of Eternity',     image = 'jg_sands_of_eternity_trading_cards_pack.webp' },
        -- { item = 'jg_sands_of_eternity_pack_mythic',              label = 'JG Sands of Eternity Mythic Pack',            price = 2200,    category = 'JG Sands of Eternity',     image = 'jg_sands_of_eternity_trading_cards_pack_mythic.webp' },
        -- { item = 'jg_sands_of_eternity_pack_legendary',           label = 'JG Sands of Eternity Legendary Pack',         price = 3500,    category = 'JG Sands of Eternity',     image = 'jg_sands_of_eternity_trading_cards_pack_legendary.webp' },
        -- { item = 'jg_sands_of_eternity_booster_box',              label = 'JG Sands of Eternity Booster Box',            price = 5800,    category = 'JG Sands of Eternity',     image = 'jg_sands_of_eternity_trading_cards_booster_box.webp' },
        -- { item = 'jg_sands_of_eternity_booster_box_mythic',       label = 'JG Sands of Eternity Mythic Booster Box',     price = 13000,   category = 'JG Sands of Eternity',     image = 'jg_sands_of_eternity_trading_cards_booster_box_mythic.webp' },
        -- { item = 'jg_sands_of_eternity_booster_box_legendary',    label = 'JG Sands of Eternity Legendary Booster Box',  price = 20800,   category = 'JG Sands of Eternity',     image = 'jg_sands_of_eternity_trading_cards_booster_box_legendary.webp' },
        -- -- ammunation_elite
        -- { item = 'ammunation_elite_pack',                         label = 'Ammunation Elite Pack',                       price = 1000,    category = 'Ammunation Elite',         image = 'ammunation_elite_pack.webp' },
        -- { item = 'ammunation_elite_mythic_pack',                  label = 'Ammunation Elite Mythic Pack',                price = 2200,    category = 'Ammunation Elite',         image = 'ammunation_elite_mythic_pack.webp' },
        -- { item = 'ammunation_elite_legendary_pack',               label = 'Ammunation Elite Legendary Pack',             price = 3500,    category = 'Ammunation Elite',         image = 'ammunation_elite_legendary_pack.webp' },
        -- { item = 'ammunation_elite_booster_box',                  label = 'Ammunation Elite Booster Box',                price = 5800,    category = 'Ammunation Elite',         image = 'ammunation_elite_booster_box.webp' },
        -- { item = 'ammunation_elite_booster_box_mythic',           label = 'Ammunation Elite Mythic Booster Box',         price = 13000,   category = 'Ammunation Elite',         image = 'ammunation_elite_booster_box_mythic.webp' },
        -- { item = 'ammunation_elite_booster_box_legendary',        label = 'Ammunation Elite Legendary Booster Box',      price = 20800,   category = 'Ammunation Elite',         image = 'ammunation_elite_booster_box_legendary.webp' },
        -- -- full_throttle
        -- { item = 'full_throttle_pack',                            label = 'Full Throttle Pack',                          price = 1000,    category = 'Full Throttle',            image = 'full_throttle_pack.webp' },
        -- { item = 'full_throttle_mythic_pack',                     label = 'Full Throttle Mythic Pack',                   price = 2200,    category = 'Full Throttle',            image = 'full_throttle_mythic_pack.webp' },
        -- { item = 'full_throttle_legendary_pack',                  label = 'Full Throttle Legendary Pack',                price = 3500,    category = 'Full Throttle',            image = 'full_throttle_legendary_pack.webp' },
        -- { item = 'full_throttle_booster_box',                     label = 'Full Throttle Booster Box',                   price = 5800,    category = 'Full Throttle',            image = 'full_throttle_booster_box.webp' },
        -- { item = 'full_throttle_booster_box_mythic',              label = 'Full Throttle Mythic Booster Box',            price = 13000,   category = 'Full Throttle',            image = 'full_throttle_booster_box_mythic.webp' },
        -- { item = 'full_throttle_booster_box_legendary',           label = 'Full Throttle Legendary Booster Box',         price = 20800,   category = 'Full Throttle',            image = 'full_throttle_booster_box_legendary.webp' },
        -- -- ls_legends
        -- { item = 'ls_legends_pack',                               label = 'LS Legends Pack',                             price = 1000,    category = 'LS Legends',               image = 'ls_legends_pack.webp' },
        -- { item = 'ls_legends_mythic_pack',                        label = 'LS Legends Mythic Pack',                      price = 2200,    category = 'LS Legends',               image = 'ls_legends_mythic_pack.webp' },
        -- { item = 'ls_legends_legendary_pack',                     label = 'LS Legends Legendary Pack',                   price = 3500,    category = 'LS Legends',               image = 'ls_legends_legendary_pack.webp' },
        -- { item = 'ls_legends_booster_box',                        label = 'LS Legends Booster Box',                      price = 5800,    category = 'LS Legends',               image = 'ls_legends_booster_box.webp' },
        -- { item = 'ls_legends_booster_box_mythic',                 label = 'LS Legends Mythic Booster Box',               price = 13000,   category = 'LS Legends',               image = 'ls_legends_booster_box_mythic.webp' },
        -- { item = 'ls_legends_booster_box_legendary',              label = 'LS Legends Legendary Booster Box',            price = 20800,   category = 'LS Legends',               image = 'ls_legends_booster_box_legendary.webp' },
        -- -- ls_landmark_pack
        -- { item = 'ls_landmark_pack',                              label = 'LS Landmark Pack',                            price = 1000,    category = 'LS Landmark',              image = 'ls_landmark_pack.webp' },
        -- { item = 'ls_landmark_mythic_pack',                       label = 'LS Landmark Mythic Pack',                     price = 2200,    category = 'LS Landmark',              image = 'ls_landmark_mythic_pack.webp' },
        -- { item = 'ls_landmark_legendary_pack',                    label = 'LS Landmark Legendary Pack',                  price = 3500,    category = 'LS Landmark',              image = 'ls_landmark_legendary_pack.webp' },
        -- { item = 'ls_landmark_booster_box',                       label = 'LS Landmark Booster Box',                     price = 5800,    category = 'LS Landmark',              image = 'ls_landmark_booster_box.webp' },
        -- { item = 'ls_landmark_booster_box_mythic',                label = 'LS Landmark Mythic Booster Box',              price = 13000,   category = 'LS Landmark',              image = 'ls_landmark_booster_box_mythic.webp' },
        -- { item = 'ls_landmark_booster_box_legendary',             label = 'LS Landmark Legendary Booster Box',           price = 20800,   category = 'LS Landmark',              image = 'ls_landmark_booster_box_legendary.webp' },
    
        -- Accessories
        { item = '_card_book',                              label = ' V1 Book',                              price = 5000,    category = 'Accessories',              image = '_card_trading_cards_book.webp' },
        { item = 'jg_warlords_book',                              label = 'JG Warlords Book',                            price = 5000,    category = 'Accessories',              image = 'jg_warlords_trading_cards_book.webp' },
        -- { item = 'jg_shin_genesis_book',                          label = 'JG Shin Genesis Book',                        price = 10000,    category = 'Accessories',              image = 'jg_shin_genesis_trading_cards_book.webp' },
        -- { item = 'jg_void_ether_book',                            label = 'JG Void Ether Book',                          price = 10000,    category = 'Accessories',              image = 'jg_void_ether_trading_cards_book.webp' },
        -- { item = 'jg_sands_of_eternity_book',                     label = 'JG Sands of Eternity Book',                   price = 10000,    category = 'Accessories',              image = 'jg_sands_of_eternity_trading_cards_book.webp' },
        -- { item = 'ammunation_elite_book',                         label = 'Ammunation Elite Book',                       price = 10000,    category = 'Accessories',              image = 'ammunation_elite_book.webp' },
        -- { item = 'full_throttle_book',                            label = 'Full Throttle Book',                          price = 10000,    category = 'Accessories',              image = 'full_throttle_book.webp' },
        -- { item = 'ls_legends_book',                               label = 'LS Legends Book',                             price = 10000,    category = 'Accessories',              image = 'ls_legends_book.webp' },
        -- { item = 'ls_landmark_book',                              label = 'LS Landmark Book',                            price = 10000,    category = 'Accessories',              image = 'ls_landmark_book.webp' },

        { item = 'empty_grading_case',                            label = 'Empty Grading Case',                          price = 5000,   category = 'Accessories',              image = 'jim_g_trading_cards_grading_pack_s.webp' },
        { item = 'card_sleeves',                                  label = 'Card Sleeves',                                price = 1000,    category = 'Accessories',              image = 'card_sleeve_overlay.webp' },
        { item = 'cvg_binder',                                    label = 'CVG Binder',                                  price = 5000,   category = 'Accessories',              image = 'cvg_binder.webp' },
        { item = 'cvg_case_splitter',                             label = 'CVG Case Splitter',                           price = 1000,    category = 'Accessories',              image = 'cvg_case_splitter.webp' },

        { item = 'cvg_label_star_galaxy',                         label = 'CVG Label - Star Galaxy',                     price = 2000,   category = 'CVG labels',              image = 'cvg_label_star_galaxy.webp' },
        { item = 'cvg_label_color_shift',                         label = 'CVG Label - Color Shift',                     price = 2000,   category = 'CVG labels',              image = 'cvg_label_color_shift.webp' },
        { item = 'cvg_label_p_and_b_mix',                         label = 'CVG Label - P & B Mix',                       price = 2000,   category = 'CVG labels',              image = 'cvg_label_p_and_b_mix.webp' },
        { item = 'cvg_label_mellow_sky',                          label = 'CVG Label - Mellow Sky',                      price = 2000,   category = 'CVG labels',              image = 'cvg_label_mellow_sky.webp' },
        { item = 'cvg_label_aetheric_sigil',                      label = 'CVG Label - Aetheric Sigil',                  price = 2000,   category = 'CVG labels',              image = 'cvg_label_aetheric_sigil.webp' },
        { item = 'cvg_label_arcane_circle',                       label = 'CVG Label - Arcane Circle',                   price = 2000,   category = 'CVG labels',              image = 'cvg_label_arcane_circle.webp' },
        { item = 'cvg_label_astral_dragon',                       label = 'CVG Label - Astral Dragon',                   price = 2000,   category = 'CVG labels',              image = 'cvg_label_astral_dragon.webp' },
        { item = 'cvg_label_celestial_gear',                      label = 'CVG Label - Celestial Gear',                  price = 2000,   category = 'CVG labels',              image = 'cvg_label_celestial_gear.webp' },
        { item = 'cvg_label_cosmic_phoenix',                      label = 'CVG Label - Cosmic Phoenix',                  price = 2000,   category = 'CVG labels',              image = 'cvg_label_cosmic_phoenix.webp' },
        { item = 'cvg_label_elemental_fusion',                    label = 'CVG Label - Elemental Fusion',                price = 2000,   category = 'CVG labels',              image = 'cvg_label_elemental_fusion.webp' },
        { item = 'cvg_label_glacial_inferno',                     label = 'CVG Label - Glacial Inferno',                 price = 2000,   category = 'CVG labels',              image = 'cvg_label_glacial_inferno.webp' },
        { item = 'cvg_label_golden_valley',                       label = 'CVG Label - Golden Valley',                   price = 2000,   category = 'CVG labels',              image = 'cvg_label_golden_valley.webp' },
        { item = 'cvg_label_katana_street',                       label = 'CVG Label - Katana Street',                   price = 2000,   category = 'CVG labels',              image = 'cvg_label_katana_street.webp' },
        { item = 'cvg_label_mecha_hangar',                        label = 'CVG Label - Mecha Hangar',                    price = 2000,   category = 'CVG labels',              image = 'cvg_label_mecha_hangar.webp' },
        { item = 'cvg_label_nebula_drift',                        label = 'CVG Label - Nebula Drift',                    price = 2000,   category = 'CVG labels',              image = 'cvg_label_nebula_drift.webp' },
        { item = 'cvg_label_nebula_fox',                          label = 'CVG Label - Nebula Fox',                      price = 2000,   category = 'CVG labels',              image = 'cvg_label_nebula_fox.webp' },
        { item = 'cvg_label_sage_alignment',                      label = 'CVG Label - Sage Alignment',                  price = 2000,   category = 'CVG labels',              image = 'cvg_label_sage_alignment.webp' },
        { item = 'cvg_label_solaris_runes',                       label = 'CVG Label - Solaris Runes',                   price = 2000,   category = 'CVG labels',              image = 'cvg_label_solaris_runes.webp' },
        { item = 'cvg_label_winter_shrine',                       label = 'CVG Label - Winter Shrine',                   price = 2000,   category = 'CVG labels',              image = 'cvg_label_winter_shrine.webp' },
    }
}

-- CVG Grade Multipliers for sell shop on cvg selling 
Config.CVG = {
    gradeMultipliers = {
        [1] = 1.0, -- 1.0X multiplier 
        [2] = 1.05, -- 1.05X multiplier
        [3] = 1.1, -- 1.1X multiplier
        [4] = 1.2, -- 1.2X multiplier
        [5] = 1.3, -- 1.35X multiplier
        [6] = 1.5, -- 1.5X multiplier
        [7] = 1.7, -- 1.7X multiplier
        [8] = 1.9, -- 2.0X multiplier
        [9] = 2.1, -- 2.4X multiplier
        [10] = 2.2 -- 3X multiplier
    }
}

-- shop to sell unwanted card if dynamic is true price will change 5% up or down every hour
Config.SellShop = {
    enabled = true,                                     -- toggles the sell shop on/off
    currency = 'bank',                                  -- currency name used for payouts
    location = vector4(-150.98, 220.44, 93.93, 272.18), -- ped spawn position
    pedModel = 's_m_m_lathandy_01',                     -- ped model for the buyer
    scenario = 'WORLD_HUMAN_CLIPBOARD',                 -- idle scenario played by the ped
    blipenabled = false,                                 -- toggles the blip on/off           
    blipname = 'Card Buyer Shop',                       -- blip name
    blipid = 52,                                        -- blip id     
    scale = 0.4,                                        -- blip scale
    blipcolor = 28,                                     -- blip color
    dynamic = {
        enabled = true,                                 -- enable dynamic buy prices
        intervalHours = 1,                              -- how often prices change
        changePercent = 25                              -- +/- percent from basePrice when changing 
    },
    items = {
        -- grading_case must be kept here for CVG selling in the shop; base price does not matter.
        { item = 'grading_case', basePrice = 0 },
        -- grading_case must be kept here for CVG selling in the shop; base price does not matter.
-- _card
        { item = 'card_og', basePrice = 100 },
        { item = 'card_worldwide', basePrice = 100 },
        { item = 'card_almighty', basePrice = 100 },
        { item = 'card_stars', basePrice = 100 },
        { item = 'card_angel', basePrice = 100 },
        { item = 'card_above', basePrice = 100 },
        { item = 'card_aura', basePrice = 100 },
        { item = 'card_baaaa', basePrice = 100 },
        { item = 'card_bigt', basePrice = 100 },
        { item = 'card_boing', basePrice = 100 },
        { item = 'card_burger', basePrice = 100 },
        { item = 'card_burning', basePrice = 100 },
        { item = 'card_chief', basePrice = 100 },
        { item = 'card_compensation', basePrice = 100 },
        { item = 'card_dark', basePrice = 100 },
        { item = 'card_dusk', basePrice = 100 },
        { item = 'card_ems', basePrice = 100 },
        { item = 'card_final', basePrice = 100 },
        { item = 'card_grime', basePrice = 100 },
        { item = 'card_gym', basePrice = 100 },
        { item = 'card_halal', basePrice = 100 },
        { item = 'card_hold', basePrice = 100 },
        { item = 'card_hunny', basePrice = 100 },
        { item = 'card_blue', basePrice = 100 },
        { item = 'card_chi', basePrice = 100 },
        { item = 'card_phase', basePrice = 100 },
        { item = 'card_jack', basePrice = 100 },
        { item = 'card_jear', basePrice = 100 },
        { item = 'card_vibe', basePrice = 100 },
        { item = 'card_deal', basePrice = 100 },
        { item = 'card_kingpin', basePrice = 100 },
        { item = 'card_sasquatch', basePrice = 100 },
        { item = 'card_flex', basePrice = 100 },
        { item = 'card_luh', basePrice = 100 },
        { item = 'card_wish', basePrice = 100 },
        { item = 'card_myself', basePrice = 100 },
        { item = 'card_mistletoe', basePrice = 100 },
        { item = 'card_moomuffin', basePrice = 100 },
        { item = 'card_mustache', basePrice = 100 },
        { item = 'card_town', basePrice = 100 },
        { item = 'card_tots', basePrice = 100 },
        { item = 'card_night', basePrice = 100 },
        { item = 'card_old', basePrice = 100 },
        { item = 'card_case', basePrice = 100 },
        { item = 'card_pink', basePrice = 100 },
        { item = 'card_plomo', basePrice = 100 },
        { item = 'card_pov', basePrice = 100 },
        { item = 'card_proud', basePrice = 100 },
        { item = 'card_raygun', basePrice = 100 },
        { item = 'card_rest', basePrice = 100 },
        { item = 'card_roulette', basePrice = 100 },
        { item = 'card_sassy', basePrice = 100 },
        { item = 'card_pinky', basePrice = 100 },
        { item = 'card_nightshade', basePrice = 100 },
        { item = 'card_shark', basePrice = 100 },
        { item = 'card_silent', basePrice = 100 },
        { item = 'card_sin', basePrice = 100 },
        { item = 'card_soup', basePrice = 100 },
        { item = 'card_frosty', basePrice = 100 },
        { item = 'card_sugar', basePrice = 100 },
        { item = 'card_sweet', basePrice = 100 },
        { item = 'card_butterfly', basePrice = 100 },
        { item = 'card_frostys', basePrice = 100 },
        { item = 'card_high', basePrice = 100 },
        { item = 'card_nose', basePrice = 100 },
        { item = 'card_snack', basePrice = 100 },
        { item = 'card_sun', basePrice = 100 },
        { item = 'card_welshman', basePrice = 100 },
        { item = 'card_biggs', basePrice = 100 },
        { item = 'card_thugs', basePrice = 100 },
        { item = 'card_twilight', basePrice = 100 },
        { item = 'card_two', basePrice = 100 },
        { item = 'card_up', basePrice = 100 },
        { item = 'card_vital', basePrice = 100 },
        { item = 'card_red', basePrice = 100 },
        { item = 'card_what', basePrice = 100 },
        { item = 'card_whatever', basePrice = 100 },
        { item = 'card_wish_you', basePrice = 100 },
        { item = 'card_yin', basePrice = 100 },
        { item = 'card_super', basePrice = 100 },
        { item = 'card_pato', basePrice = 100 },
-- jg_warlords
        -- basePrice is the nominal price; dynamic pricing can adjust around this
        -- Normal
        { item = 'card_grizzlethorn', basePrice = 1 },
        { item = 'card_hollowmane', basePrice = 1 },
        { item = 'card_iron_warlock', basePrice = 2 },
        { item = 'card_glintfang', basePrice = 3 },
        { item = 'card_razorbloom', basePrice = 4 },
        { item = 'card_whisperling', basePrice = 6 },
        { item = 'card_moltencore', basePrice = 8 },
        { item = 'card_spectrix', basePrice = 9 },
        { item = 'card_lumigore', basePrice = 11 },
        { item = 'card_brackenshade', basePrice = 13 },
        { item = 'card_quillfin', basePrice = 14 },
        { item = 'card_thornax', basePrice = 16 },
        { item = 'card_nimbra', basePrice = 18 },
        { item = 'card_bone_collector', basePrice = 19 },
        { item = 'card_vexwing', basePrice = 19 },
        { item = 'card_crystide', basePrice = 22 },
        { item = 'card_fire_demon', basePrice = 23 },
        { item = 'card_void_walker', basePrice = 24 },
        { item = 'card_toxic_spitter', basePrice = 26 },
        { item = 'card_murklash', basePrice = 28 },
        { item = 'card_cursed_knight', basePrice = 29 },
        { item = 'card_zyphoon', basePrice = 31 },
        { item = 'card_stone_crusher', basePrice = 32 },
        { item = 'card_star_touched', basePrice = 33 },
        { item = 'card_voidcaller', basePrice = 34 },
        { item = 'card_mistweaver', basePrice = 36 },
        { item = 'card_storm_juggernaut', basePrice = 37 },
        { item = 'card_venom_burrower', basePrice = 39 },
        { item = 'card_dark_knight', basePrice = 42 },
        { item = 'card_toxic_hydra', basePrice = 43 },
        -- Uncommon
        { item = 'card_gloom_dragon', basePrice = 30 },
        { item = 'card_steel_mauler', basePrice = 32 },
        { item = 'card_spirit_hornet', basePrice = 34 },
        { item = 'card_blight_harpy', basePrice = 36 },
        { item = 'card_thunder_gryphon', basePrice = 38 },
        { item = 'card_grimblight', basePrice = 40 },
        { item = 'card_plagueborn', basePrice = 42 },
        { item = 'card_soul_eater', basePrice = 44 },
        { item = 'card_frostclaw_ape', basePrice = 46 },
        { item = 'card_blazehoof', basePrice = 48 },
        { item = 'card_ashwalker', basePrice = 51 },
        { item = 'card_thunder_serpent', basePrice = 53 },
        { item = 'card_lightning_mantis', basePrice = 55 },
        { item = 'card_quake_bison', basePrice = 57 },
        { item = 'card_earthshaker', basePrice = 59 },
        { item = 'card_ancient_one', basePrice = 61 },
        { item = 'card_arcane_wolf', basePrice = 63 },
        { item = 'card_dreadeye', basePrice = 65 },
        { item = 'card_voidborn', basePrice = 67 },
        { item = 'card_sand_ravager', basePrice = 69 },
        -- Rare
        { item = 'card_phantom_sentry', basePrice = 105 },
        { item = 'card_soul_ripper', basePrice = 110 },
        { item = 'card_fire_kraken', basePrice = 116 },
        { item = 'card_granite_behemoth', basePrice = 121 },
        { item = 'card_molten_reaper', basePrice = 127 },
        { item = 'card_night_howler', basePrice = 132 },
        { item = 'card_abyss_crawler', basePrice = 138 },
        { item = 'card_stormling_beast', basePrice = 143 },
        { item = 'card_dread_warden', basePrice = 149 },
        { item = 'card_storm_brute', basePrice = 154 },
        { item = 'card_storm_spirit', basePrice = 160 },
        { item = 'card_mist_leviathan', basePrice = 165 },
        { item = 'card_frost_golem', basePrice = 171 },
        { item = 'card_ash_hollow', basePrice = 176 },
        { item = 'card_iron_fang', basePrice = 182 },
        { item = 'card_shadow_marauder', basePrice = 187 },
        { item = 'card_void_revenant', basePrice = 193 },
        { item = 'card_cloud_watcher', basePrice = 198 },
        { item = 'card_ember_ogre', basePrice = 204 },
        { item = 'card_echo_shade', basePrice = 209 },
        -- Epic
        { item = 'card_crystal_titan', basePrice = 1400 },
        { item = 'card_chaos_spawn', basePrice = 1466 },
        { item = 'card_chaos_gorgon', basePrice = 1533 },
        { item = 'card_blood_talon', basePrice = 1599 },
        { item = 'card_lunar_specter', basePrice = 1666 },
        { item = 'card_dread_basilisk', basePrice = 1733 },
        { item = 'card_venom_hunter', basePrice = 1799 },
        { item = 'card_void_stalker', basePrice = 1866 },
        { item = 'card_ember_wraith', basePrice = 1932 },
        { item = 'card_wind_phantom', basePrice = 1999 },
        -- Legendary
        { item = 'card_bone_colossus', basePrice = 2000 },
        { item = 'card_flame_beast', basePrice = 2066 },
        { item = 'card_ironclad_leviathan', basePrice = 2133 },
        { item = 'card_whisperwing', basePrice = 2199 },
        { item = 'card_chronospecter', basePrice = 2266 },
        { item = 'card_shroomancer', basePrice = 2333 },
        { item = 'card_stormcoil', basePrice = 2399 },
        { item = 'card_cinderfang', basePrice = 2466 },
        { item = 'card_sunscorch', basePrice = 2532 },
        { item = 'card_tanglevine', basePrice = 2599 },
        -- Holo
        { item = 'card_boltstride', basePrice = 26000 },
        { item = 'card_hydrusk', basePrice = 26444 },
        { item = 'card_terraklaw', basePrice = 26888 },
        { item = 'card_crystalfrost', basePrice = 27332 },
        { item = 'card_valtherix', basePrice = 27776 },
        { item = 'card_tektorrath', basePrice = 28220 },
        { item = 'card_rootstride', basePrice = 28664 },
        { item = 'card_eldrephon', basePrice = 29108 },
        { item = 'card_mirthful_mimic', basePrice = 29552 },
        { item = 'card_aetheron', basePrice = 30000 },
        -- OriginalArt
        { item = 'card_aetherion', basePrice = 31000 },
        { item = 'card_the_chronos_wraith', basePrice = 32000 },
        { item = 'card_vortex_stalker', basePrice = 33000 },
        { item = 'card_runebane_golem', basePrice = 34000 },
        { item = 'card_ignis_rex', basePrice = 35000 },
        { item = 'card_quillwing_harpy', basePrice = 35500 },
        { item = 'card_terrashear_hydra', basePrice = 36000 },
        { item = 'card_gravemaw', basePrice = 36500 },
        { item = 'card_shadow_silk', basePrice = 37000 },
        { item = 'card_fang', basePrice = 37500 },
-- -- jg_shin_genesis
--         -- Normal
--         { item = 'card_android_aria_v3', basePrice = 1 },
--         { item = 'card_android_final_form', basePrice = 1 },
--         { item = 'card_android_izumi_x', basePrice = 2 },
--         { item = 'card_android_jin_model_s', basePrice = 3 },
--         { item = 'card_android_kaya_flow', basePrice = 4 },
--         { item = 'card_android_natsu_g', basePrice = 6 },
--         { item = 'card_android_t_80_girl', basePrice = 8 },
--         { item = 'card_android_unit_99', basePrice = 9 },
--         { item = 'card_aoi_vector_girl', basePrice = 11 },
--         { item = 'card_asuka_saber_vessel', basePrice = 13 },
--         { item = 'card_ayaka_armor_angel', basePrice = 14 },
--         { item = 'card_chihiro_cradle_pilot', basePrice = 16 },
--         { item = 'card_cyborg_benji_blast', basePrice = 18 },
--         { item = 'card_cyborg_daisuke_x', basePrice = 19 },
--         { item = 'card_cyborg_goro_tank', basePrice = 19 },
--         { item = 'card_cyborg_kenji_prime', basePrice = 22 },
--         { item = 'card_cyborg_raiden_v', basePrice = 23 },
--         { item = 'card_cyborg_zane_rogue', basePrice = 24 },
--         { item = 'card_daichi_gravity_king', basePrice = 26 },
--         { item = 'card_eri_plasma_witch', basePrice = 28 },
--         { item = 'card_fuka_frost_android', basePrice = 29 },
--         { item = 'card_gaku_ground_zero', basePrice = 31 },
--         { item = 'card_gen_cortex_crusher', basePrice = 32 },
--         { item = 'card_genesis_eve_girl', basePrice = 33 },
--         { item = 'card_hana_neon_sniper', basePrice = 34 },
--         { item = 'card_haru_wire_walker', basePrice = 36 },
--         { item = 'card_hikari_light_speed', basePrice = 37 },
--         { item = 'card_hina_echo_dancer', basePrice = 39 },
--         { item = 'card_hiro_bolt_mechanic', basePrice = 42 },
--         { item = 'card_ichiro_signal_lost', basePrice = 43 },
--         -- Uncommon
--         { item = 'card_itsuki_forest_hacker', basePrice = 30 },
--         { item = 'card_izumi_neon_assassin', basePrice = 32 },
--         { item = 'card_jin_iron_blood', basePrice = 34 },
--         { item = 'card_kaito_storm_rider', basePrice = 36 },
--         { item = 'card_karin_spark_medic', basePrice = 38 },
--         { item = 'card_keiko_wire_puppet', basePrice = 40 },
--         { item = 'card_ken_carbon_fist', basePrice = 42 },
--         { item = 'card_kenshin_neo_samurai', basePrice = 44 },
--         { item = 'card_kira_blade_dancer', basePrice = 46 },
--         { item = 'card_koharu_glitch_girl', basePrice = 48 },
--         { item = 'card_kouta_drift_king', basePrice = 51 },
--         { item = 'card_kyosuke_void_walker', basePrice = 53 },
--         { item = 'card_last_hope_aria', basePrice = 55 },
--         { item = 'card_legendary_yuki_blade', basePrice = 57 },
--         { item = 'card_luna_ghost_pilot', basePrice = 59 },
--         { item = 'card_mai_titanium_rose', basePrice = 61 },
--         { item = 'card_makoto_justice_bot', basePrice = 63 },
--         { item = 'card_masaru_heavy_metal', basePrice = 65 },
--         { item = 'card_mecha_dojo_master', basePrice = 67 },
--         { item = 'card_mecha_kensei_g', basePrice = 69 },
--         -- Rare
--         { item = 'card_mecha_maid_unit_1', basePrice = 105 },
--         { item = 'card_mecha_sentry_m_2', basePrice = 110 },
--         { item = 'card_mika_data_runner', basePrice = 116 },
--         { item = 'card_minato_harbor_guard', basePrice = 121 },
--         { item = 'card_misaki_laser_eye', basePrice = 127 },
--         { item = 'card_miyuu_mirror_mask', basePrice = 132 },
--         { item = 'card_momo_binary_brawler', basePrice = 138 },
--         { item = 'card_nanami_nano_slayer', basePrice = 143 },
--         { item = 'card_nao_silicon_heart', basePrice = 149 },
--         { item = 'card_nozomi_solar_soul', basePrice = 154 },
--         { item = 'card_overlord_mecha_saki', basePrice = 160 },
--         { item = 'card_prototype_zero_boy', basePrice = 165 },
--         { item = 'card_rei_system_proxy', basePrice = 171 },
--         { item = 'card_ren_cyber_shinobi', basePrice = 176 },
--         { item = 'card_rika_chrome_queen', basePrice = 182 },
--         { item = 'card_rin_techno_geisha', basePrice = 187 },
--         { item = 'card_rina_metal_soul', basePrice = 193 },
--         { item = 'card_ritsuko_radar_girl', basePrice = 198 },
--         { item = 'card_ryota_static_sword', basePrice = 204 },
--         { item = 'card_ryu_street_warlord', basePrice = 209 },
--         -- Epic
--         { item = 'card_ryusei_comet_crasher', basePrice = 1400 },
--         { item = 'card_ryuu_dragon_hybrid', basePrice = 1466 },
--         { item = 'card_sae_circuit_seeker', basePrice = 1533 },
--         { item = 'card_sakura_cyber_vixen', basePrice = 1599 },
--         { item = 'card_satoshi_code_breaker', basePrice = 1666 },
--         { item = 'card_sayuri_neon_ghost', basePrice = 1733 },
--         { item = 'card_shadow_council_ren', basePrice = 1799 },
--         { item = 'card_shin_genesis_alpha_boy', basePrice = 1866 },
--         { item = 'card_shin_genesis_warlord', basePrice = 1932 },
--         { item = 'card_shizuku_water_wire', basePrice = 1999 },
--         -- Legendary
--         { item = 'card_sho_vortex_pilot', basePrice = 2000 },
--         { item = 'card_shun_flash_rebel', basePrice = 2066 },
--         { item = 'card_sora_plasma_princess', basePrice = 2133 },
--         { item = 'card_sora_sky_stalker', basePrice = 2199 },
--         { item = 'card_sota_ransom_boy', basePrice = 2266 },
--         { item = 'card_taiga_tiger_tech', basePrice = 2333 },
--         { item = 'card_takumi_tech_monk', basePrice = 2399 },
--         { item = 'card_taro_scrap_dealer', basePrice = 2466 },
--         { item = 'card_the_jg_prototype', basePrice = 2532 },
--         { item = 'card_the_shin_original_boy', basePrice = 2599 },
--         -- Holo
--         { item = 'card_ultimate_shin_boy', basePrice = 26000 },
--         { item = 'card_unit_7_guardian', basePrice = 26444 },
--         { item = 'card_unit_alpha_tactician', basePrice = 26888 },
--         { item = 'card_unit_delta_heavy', basePrice = 27332 },
--         { item = 'card_unit_gamma_sniper', basePrice = 27776 },
--         { item = 'card_unit_iota_infiltrator', basePrice = 28220 },
--         { item = 'card_unit_kappa_hunter', basePrice = 28664 },
--         { item = 'card_unit_lambda_leader', basePrice = 29108 },
--         { item = 'card_unit_mu_executioner', basePrice = 29552 },
--         { item = 'card_unit_nyx_shadow_girl', basePrice = 30000 },
--         -- OriginalArt
--         { item = 'card_unit_omega_slayer', basePrice = 31000 },
--         { item = 'card_unit_sigma_sentry', basePrice = 32000 },
--         { item = 'card_unit_theta_ghost', basePrice = 33000 },
--         { item = 'card_unit_zeta_breaker', basePrice = 34000 },
--         { item = 'card_yuki_blade_daughter', basePrice = 35000 },
--         { item = 'card_yumi_pulse_archer', basePrice = 35500 },
--         { item = 'card_yuna_core_breaker', basePrice = 36000 },
--         { item = 'card_yuto_neural_linker', basePrice = 36500 },
-- -- jg_void_ether
--         -- Normal
--         { item = 'card_flamewing_dragon', basePrice = 1 },
--         { item = 'card_ashspike_drake', basePrice = 1 },
--         { item = 'card_cindergloom_fiend', basePrice = 2 },
--         { item = 'card_bloodmaw_horror', basePrice = 3 },
--         { item = 'card_bloodhorn_minotaur', basePrice = 4 },
--         { item = 'card_darkspire_mage', basePrice = 6 },
--         { item = 'card_chaos_drake', basePrice = 8 },
--         { item = 'card_embermaw_hydra', basePrice = 9 },
--         { item = 'card_obsidian_seer', basePrice = 11 },
--         { item = 'card_fleshmire_beast', basePrice = 13 },
--         { item = 'card_voidspawn_aberration', basePrice = 14 },
--         { item = 'card_soulweaver_sorceress', basePrice = 16 },
--         { item = 'card_nightshroud_hag', basePrice = 18 },
--         { item = 'card_voidscream_specter', basePrice = 19 },
--         { item = 'card_cindermaw_beast', basePrice = 19 },
--         { item = 'card_voidmaw_beast', basePrice = 22 },
--         { item = 'card_darkfang_beast', basePrice = 23 },
--         { item = 'card_blazefang', basePrice = 24 },
--         { item = 'card_ashclaw', basePrice = 26 },
--         { item = 'card_shadowspike_predator', basePrice = 28 },
--         { item = 'card_ashenfang_dragon', basePrice = 29 },
--         { item = 'card_hunter_noble', basePrice = 31 },
--         { item = 'card_cindergale', basePrice = 32 },
--         { item = 'card_ancient_rall', basePrice = 33 },
--         { item = 'card_shadowmancer', basePrice = 34 },
--         { item = 'card_twilight_hag', basePrice = 36 },
--         { item = 'card_seeall', basePrice = 37 },
--         { item = 'card_ashfang_basilisk', basePrice = 39 },
--         { item = 'card_bonegrasp_horror', basePrice = 42 },
--         { item = 'card_boneclaw_horror', basePrice = 43 },
--         { item = 'card_nightgore_abomination', basePrice = 44 },
--         { item = 'card_doomveil_phantom', basePrice = 46 },
--         { item = 'card_soulreaper_wraith', basePrice = 47 },
--         { item = 'card_shadowclaw', basePrice = 49 },
--         { item = 'card_bloodtalon_demon', basePrice = 50 },
--         { item = 'card_ashfang_ghoul', basePrice = 52 },
--         { item = 'card_shadowfang_lycan', basePrice = 53 },
--         { item = 'card_nightfang_horror', basePrice = 55 },
--         { item = 'card_bonegloom_abomination', basePrice = 56 },
--         { item = 'card_darkshroud_wraith', basePrice = 58 },
--         -- Uncommon
--         { item = 'card_battle_champion', basePrice = 30 },
--         { item = 'card_scorchclaw', basePrice = 32 },
--         { item = 'card_stormbeak', basePrice = 34 },
--         { item = 'card_nightveil_witch', basePrice = 36 },
--         { item = 'card_stormfang_monster', basePrice = 38 },
--         { item = 'card_desert_sentinel', basePrice = 40 },
--         { item = 'card_soulshade_sorcerer', basePrice = 42 },
--         { item = 'card_stormmaw_abomination', basePrice = 44 },
--         { item = 'card_ashclaw_behemoth', basePrice = 46 },
--         { item = 'card_shadowmaw_horror', basePrice = 48 },
--         { item = 'card_soulbloom_wizard', basePrice = 51 },
--         { item = 'card_voidfeather_specter', basePrice = 53 },
--         { item = 'card_cinderveil_witch', basePrice = 55 },
--         { item = 'card_ironveil_witch', basePrice = 57 },
--         { item = 'card_noble_guardian', basePrice = 59 },
--         { item = 'card_ironhide_colossus', basePrice = 61 },
--         { item = 'card_gravefang_specter', basePrice = 63 },
--         { item = 'card_soulfang_wraith', basePrice = 65 },
--         { item = 'card_scorchmaw_horror', basePrice = 67 },
--         { item = 'card_iron_vigilant', basePrice = 69 },
--         -- Rare
--         { item = 'card_shadowwing_horror', basePrice = 105 },
--         { item = 'card_bloodbeak_fiend', basePrice = 110 },
--         { item = 'card_frostbloom_enchantress', basePrice = 116 },
--         { item = 'card_stormveil_sorcerer', basePrice = 121 },
--         { item = 'card_blightthorn_witch', basePrice = 127 },
--         { item = 'card_ironscale', basePrice = 132 },
--         { item = 'card_iron_sigils_wizard', basePrice = 138 },
--         { item = 'card_bloodshade_wizard', basePrice = 143 },
--         { item = 'card_venomclaw_abomination', basePrice = 149 },
--         { item = 'card_ironwing_gargant', basePrice = 154 },
--         { item = 'card_emberlash_drake', basePrice = 160 },
--         { item = 'card_ashfeather', basePrice = 165 },
--         { item = 'card_sable_coven_witch', basePrice = 171 },
--         { item = 'card_wizard_of_broken_time', basePrice = 176 },
--         { item = 'card_gravewing', basePrice = 182 },
--         { item = 'card_wizard_of_frozen_runes', basePrice = 187 },
--         { item = 'card_darktalon', basePrice = 193 },
--         { item = 'card_gold_armorer', basePrice = 198 },
--         { item = 'card_arcane_relic_wizard', basePrice = 204 },
--         { item = 'card_soulwing', basePrice = 209 },
--         -- Epic
--         { item = 'card_cryptfire_wizard', basePrice = 1400 },
--         { item = 'card_ashen_tome_wizard', basePrice = 1466 },
--         { item = 'card_frostscar_wyrm', basePrice = 1533 },
--         { item = 'card_moonseer', basePrice = 1599 },
--         { item = 'card_spellscar_wizard', basePrice = 1666 },
--         { item = 'card_starfall_wizard', basePrice = 1733 },
--         { item = 'card_grim_archive_wizard', basePrice = 1799 },
--         { item = 'card_gravebloom_witch', basePrice = 1866 },
--         { item = 'card_voidbinding_wizard', basePrice = 1932 },
--         { item = 'card_thorncurse_witch', basePrice = 1999 },
--         -- Legendary
--         { item = 'card_cinderbone_witch', basePrice = 2000 },
--         { item = 'card_moonrot_witch', basePrice = 2066 },
--         { item = 'card_nighthex_witch', basePrice = 2133 },
--         { item = 'card_cryptmist_specter', basePrice = 2199 },
--         { item = 'card_shadowflame_elemental', basePrice = 2266 },
--         { item = 'card_bloodveil_witch', basePrice = 2333 },
--         { item = 'card_star_noble', basePrice = 2399 },
--         { item = 'card_sunken_prince', basePrice = 2466 },
--         { item = 'card_soulmaw_wraith', basePrice = 2532 },
--         { item = 'card_voidcaller_witch', basePrice = 2599 },
--         -- Holo
--         { item = 'card_cindercloak_wizard', basePrice = 26000 },
--         { item = 'card_emberflame_witch', basePrice = 26444 },
--         { item = 'card_moon_lancer', basePrice = 26888 },
--         { item = 'card_fallen_scribe', basePrice = 27332 },
--         { item = 'card_dreadbloom_witch', basePrice = 27776 },
--         { item = 'card_gravewhisper', basePrice = 28220 },
--         { item = 'card_high_priest', basePrice = 28664 },
--         { item = 'card_pharaoh_ruler', basePrice = 29108 },
--         { item = 'card_flameveil_witch', basePrice = 29552 },
--         { item = 'card_soulveil_witch', basePrice = 30000 },
--         -- OriginalArt
--         { item = 'card_bloodrot_witch', basePrice = 31000 },
--         { item = 'card_nightgloom_witch', basePrice = 32000 },
--         { item = 'card_shadowbloom_witch', basePrice = 33000 },
--         { item = 'card_cryptveil_witch', basePrice = 34000 },
--         { item = 'card_frostbane_sorcerer', basePrice = 35000 },
--         { item = 'card_stormbinder', basePrice = 35500 },
--         { item = 'card_ashen_circle_witch', basePrice = 36000 },
--         { item = 'card_scorchtome', basePrice = 36500 },
--         { item = 'card_voidveil_witch', basePrice = 37000 },
--         { item = 'card_dark_archenemy', basePrice = 37500 },
-- -- jg_sands_of_eternity
--         -- Normal
--         { item = 'card_ammit_eater', basePrice = 1 },
--         { item = 'card_ankh_keeper', basePrice = 1 },
--         { item = 'card_ankhbrace', basePrice = 2 },
--         { item = 'card_ankhou_justice', basePrice = 3 },
--         { item = 'card_ankhouveil', basePrice = 4 },
--         { item = 'card_anubis_guardian', basePrice = 6 },
--         { item = 'card_apep_serpent', basePrice = 8 },
--         { item = 'card_apepcoil', basePrice = 9 },
--         { item = 'card_apepdevourer', basePrice = 11 },
--         { item = 'card_apepshadow', basePrice = 13 },
--         { item = 'card_aten_disk', basePrice = 14 },
--         { item = 'card_atenflare_divine', basePrice = 16 },
--         { item = 'card_bast_shadow', basePrice = 18 },
--         { item = 'card_bastet_protector', basePrice = 19 },
--         { item = 'card_bastetpurr', basePrice = 19 },
--         { item = 'card_bastpatrol', basePrice = 22 },
--         { item = 'card_bastpaw', basePrice = 23 },
--         { item = 'card_bastshadow', basePrice = 24 },
--         { item = 'card_bennucry', basePrice = 26 },
--         { item = 'card_bennuwing', basePrice = 28 },
--         { item = 'card_dedunbring', basePrice = 29 },
--         { item = 'card_dedunprosper', basePrice = 31 },
--         { item = 'card_duat_guardian', basePrice = 32 },
--         { item = 'card_duatveil', basePrice = 33 },
--         { item = 'card_gebsoil', basePrice = 34 },
--         { item = 'card_hapiflows', basePrice = 36 },
--         { item = 'card_hapinile', basePrice = 37 },
--         { item = 'card_hathor_goddess', basePrice = 39 },
--         { item = 'card_hathorcharm', basePrice = 42 },
--         { item = 'card_hathorhorn', basePrice = 43 },
--         { item = 'card_hathorpulse', basePrice = 44 },
--         { item = 'card_hathorvoice', basePrice = 46 },
--         { item = 'card_horus_sky_warrior', basePrice = 47 },
--         { item = 'card_horusfalcon', basePrice = 49 },
--         { item = 'card_horusra_watcher', basePrice = 50 },
--         { item = 'card_horuswatch', basePrice = 52 },
--         { item = 'card_isis_mother', basePrice = 53 },
--         { item = 'card_isisbless', basePrice = 55 },
--         { item = 'card_isisglow', basePrice = 56 },
--         { item = 'card_isisgrace', basePrice = 58 },
--         -- Uncommon
--         { item = 'card_isisveil', basePrice = 30 },
--         { item = 'card_keb_earth', basePrice = 32 },
--         { item = 'card_kebrock', basePrice = 34 },
--         { item = 'card_khepribeetle', basePrice = 36 },
--         { item = 'card_kheprihold', basePrice = 38 },
--         { item = 'card_khnemu_creator', basePrice = 40 },
--         { item = 'card_khonsu_moon', basePrice = 42 },
--         { item = 'card_khonsubright', basePrice = 44 },
--         { item = 'card_khonsulight', basePrice = 46 },
--         { item = 'card_khonsumoon', basePrice = 48 },
--         { item = 'card_khonsusilver', basePrice = 51 },
--         { item = 'card_maahes_huntress', basePrice = 53 },
--         { item = 'card_maahes_lion', basePrice = 55 },
--         { item = 'card_maahesclaw', basePrice = 57 },
--         { item = 'card_maat_truth', basePrice = 59 },
--         { item = 'card_maatlaw_truth', basePrice = 61 },
--         { item = 'card_maatlawbalance', basePrice = 63 },
--         { item = 'card_menkheper_ra', basePrice = 65 },
--         { item = 'card_montu_striker', basePrice = 67 },
--         { item = 'card_montu_warrior', basePrice = 69 },
--         -- Rare
--         { item = 'card_montubreaker', basePrice = 105 },
--         { item = 'card_montufury', basePrice = 110 },
--         { item = 'card_nebet_majesty', basePrice = 116 },
--         { item = 'card_neith_hunter', basePrice = 121 },
--         { item = 'card_neitharrow', basePrice = 127 },
--         { item = 'card_neithhunt', basePrice = 132 },
--         { item = 'card_nephthys_shadow', basePrice = 138 },
--         { item = 'card_nephthysdark', basePrice = 143 },
--         { item = 'card_nephthysveil', basePrice = 149 },
--         { item = 'card_nun_primordial', basePrice = 154 },
--         { item = 'card_osiris_ruler', basePrice = 160 },
--         { item = 'card_osirislament', basePrice = 165 },
--         { item = 'card_osiriswatch', basePrice = 171 },
--         { item = 'card_ptah_creator', basePrice = 176 },
--         { item = 'card_ptahforge', basePrice = 182 },
--         { item = 'card_ptahhammer', basePrice = 187 },
--         { item = 'card_ra_sun_god', basePrice = 193 },
--         { item = 'card_raet_lightbringer', basePrice = 198 },
--         { item = 'card_raet_sun', basePrice = 204 },
--         { item = 'card_raflame', basePrice = 209 },
--         -- Epic
--         { item = 'card_raflare', basePrice = 1400 },
--         { item = 'card_raheat', basePrice = 1466 },
--         { item = 'card_renpetcircle', basePrice = 1533 },
--         { item = 'card_renpetcycle', basePrice = 1599 },
--         { item = 'card_sah_star', basePrice = 1666 },
--         { item = 'card_sahglow', basePrice = 1733 },
--         { item = 'card_sahstar', basePrice = 1799 },
--         { item = 'card_sahure_guardian', basePrice = 1866 },
--         { item = 'card_sauket_magic', basePrice = 1932 },
--         { item = 'card_sauketcloak', basePrice = 1999 },
--         -- Legendary
--         { item = 'card_sekmet_warrior', basePrice = 2000 },
--         { item = 'card_sekmetclaw', basePrice = 2066 },
--         { item = 'card_sekmetfury', basePrice = 2133 },
--         { item = 'card_serqetsting', basePrice = 2199 },
--         { item = 'card_serqetstinger', basePrice = 2266 },
--         { item = 'card_set_chaos_lord', basePrice = 2333 },
--         { item = 'card_setchaos', basePrice = 2399 },
--         { item = 'card_setstorm', basePrice = 2466 },
--         { item = 'card_shu_air', basePrice = 2532 },
--         { item = 'card_shubreeze', basePrice = 2599 },
--         -- Holo
--         { item = 'card_shusky', basePrice = 26000 },
--         { item = 'card_sobekflood', basePrice = 26444 },
--         { item = 'card_sobekhunt', basePrice = 26888 },
--         { item = 'card_sobekjaw_predator', basePrice = 27332 },
--         { item = 'card_sopduguardian', basePrice = 27776 },
--         { item = 'card_sopduspear', basePrice = 28220 },
--         { item = 'card_sopduspire', basePrice = 28664 },
--         { item = 'card_sphinx_guard', basePrice = 29108 },
--         { item = 'card_sphinxriddle', basePrice = 29552 },
--         { item = 'card_sphinxrune', basePrice = 30000 },
--         -- OriginalArt
--         { item = 'card_taweret_protector', basePrice = 31000 },
--         { item = 'card_tefnut_moisture', basePrice = 32000 },
--         { item = 'card_tefnutdrop', basePrice = 33000 },
--         { item = 'card_thoth_scribe', basePrice = 34000 },
--         { item = 'card_thothscribe', basePrice = 35000 },
--         { item = 'card_thothwisdom_keeper', basePrice = 35500 },
--         { item = 'card_wadjet_protector', basePrice = 36000 },
--         { item = 'card_wadjetcobra', basePrice = 36500 },
--         { item = 'card_wadjeteye', basePrice = 37000 },
--         { item = 'card_wadjetprotect', basePrice = 37500 },
-- -- ammunation_elite
--         -- Normal
--         { item = 'card_weapon_bat', basePrice = 1 },
--         { item = 'card_weapon_crowbar', basePrice = 1 },
--         { item = 'card_weapon_flashlight', basePrice = 2 },
--         { item = 'card_weapon_golfclub', basePrice = 3 },
--         { item = 'card_weapon_hammer', basePrice = 4 },
--         { item = 'card_weapon_knife', basePrice = 6 },
--         { item = 'card_weapon_nightstick', basePrice = 8 },
--         { item = 'card_weapon_pistol', basePrice = 9 },
--         { item = 'card_weapon_poolcue', basePrice = 11 },
--         { item = 'card_weapon_wrench', basePrice = 13 },
--         { item = 'card_weapon_appisto', basePrice = 14 },
--         { item = 'card_weapon_bottle', basePrice = 16 },
--         { item = 'card_weapon_combatpistol', basePrice = 18 },
--         { item = 'card_weapon_dagger', basePrice = 19 },
--         { item = 'card_weapon_hatchet', basePrice = 19 },
--         { item = 'card_weapon_knuckle', basePrice = 22 },
--         { item = 'card_weapon_machete', basePrice = 23 },
--         { item = 'card_weapon_microsmg', basePrice = 24 },
--         { item = 'card_weapon_pistol_mk2', basePrice = 26 },
--         { item = 'card_weapon_pumpshotgun', basePrice = 28 },
--         { item = 'card_weapon_sawnoffshotgun', basePrice = 29 },
--         { item = 'card_weapon_switchblade', basePrice = 31 },
--         { item = 'card_weapon_snspistol', basePrice = 32 },
--         { item = 'card_weapon_assaultrifle', basePrice = 33 },
--         { item = 'card_weapon_assaultsmg', basePrice = 34 },
--         { item = 'card_weapon_carbinerifle', basePrice = 36 },
--         { item = 'card_weapon_compactrifle', basePrice = 37 },
--         { item = 'card_weapon_grenade', basePrice = 39 },
--         { item = 'card_weapon_heavypistol', basePrice = 42 },
--         { item = 'card_weapon_machinepistol', basePrice = 43 },
--         -- Uncommon
--         { item = 'card_weapon_appisto', basePrice = 30 },
--         { item = 'card_weapon_bottle', basePrice = 32 },
--         { item = 'card_weapon_combatpistol', basePrice = 34 },
--         { item = 'card_weapon_dagger', basePrice = 36 },
--         { item = 'card_weapon_hatchet', basePrice = 38 },
--         { item = 'card_weapon_knuckle', basePrice = 40 },
--         { item = 'card_weapon_machete', basePrice = 42 },
--         { item = 'card_weapon_microsmg', basePrice = 44 },
--         { item = 'card_weapon_pistol_mk2', basePrice = 46 },
--         { item = 'card_weapon_pumpshotgun', basePrice = 48 },
--         { item = 'card_weapon_sawnoffshotgun', basePrice = 51 },
--         { item = 'card_weapon_switchblade', basePrice = 53 },
--         { item = 'card_weapon_snspistol', basePrice = 55 },
--         { item = 'card_weapon_assaultrifle', basePrice = 57 },
--         { item = 'card_weapon_assaultsmg', basePrice = 59 },
--         { item = 'card_weapon_carbinerifle', basePrice = 61 },
--         { item = 'card_weapon_compactrifle', basePrice = 63 },
--         { item = 'card_weapon_grenade', basePrice = 65 },
--         { item = 'card_weapon_heavypistol', basePrice = 67 },
--         { item = 'card_weapon_machinepistol', basePrice = 69 },
--         -- Rare
--         { item = 'card_weapon_marksmanpistol', basePrice = 105 },
--         { item = 'card_weapon_minismg', basePrice = 110 },
--         { item = 'card_weapon_pumpshotgun_mk2', basePrice = 116 },
--         { item = 'card_weapon_smg', basePrice = 121 },
--         { item = 'card_weapon_smokegrenade', basePrice = 127 },
--         { item = 'card_weapon_vintagepistol', basePrice = 132 },
--         { item = 'card_weapon_stickybomb', basePrice = 138 },
--         { item = 'card_weapon_advancedrifle', basePrice = 143 },
--         { item = 'card_weapon_assaultshotgun', basePrice = 149 },
--         { item = 'card_weapon_bullpuprifle', basePrice = 154 },
--         { item = 'card_weapon_bullpupshotgun', basePrice = 160 },
--         { item = 'card_weapon_combatpdw', basePrice = 165 },
--         { item = 'card_weapon_heavyrifle', basePrice = 171 },
--         { item = 'card_weapon_militaryrifle', basePrice = 176 },
--         { item = 'card_weapon_proxmine', basePrice = 182 },
--         { item = 'card_weapon_revolver', basePrice = 187 },
--         { item = 'card_weapon_revolver_mk2', basePrice = 193 },
--         { item = 'card_weapon_smg_mk2', basePrice = 198 },
--         { item = 'card_weapon_sniperrifle', basePrice = 204 },
--         { item = 'card_weapon_specialcarbine', basePrice = 209 },
--         -- Epic
--         { item = 'card_weapon_navyrevolver', basePrice = 1400 },
--         { item = 'card_weapon_pistolxm3', basePrice = 1466 },
--         { item = 'card_weapon_specialcarbine_mk2', basePrice = 1533 },
--         { item = 'card_weapon_tacticalrifle', basePrice = 1599 },
--         { item = 'card_weapon_tecpistol', basePrice = 1666 },
--         { item = 'card_weapon_autoshotgun', basePrice = 1733 },
--         { item = 'card_weapon_combatmg', basePrice = 1799 },
--         { item = 'card_weapon_combatmg_mk2', basePrice = 1866 },
--         { item = 'card_weapon_combatshotgun', basePrice = 1932 },
--         { item = 'card_weapon_doubleaction', basePrice = 1999 },
--         -- Legendary
--         { item = 'card_weapon_gadgetpistol', basePrice = 2000 },
--         { item = 'card_weapon_heavyshotgun', basePrice = 2066 },
--         { item = 'card_weapon_heavysniper', basePrice = 2133 },
--         { item = 'card_weapon_marksmanrifle', basePrice = 2199 },
--         { item = 'card_weapon_marksmanrifle_mk2', basePrice = 2266 },
--         { item = 'card_weapon_rpg', basePrice = 2333 },
--         { item = 'card_weapon_compactlauncher', basePrice = 2399 },
--         { item = 'card_weapon_raypistol', basePrice = 2439 },
--         { item = 'card_weapon_emplauncher', basePrice = 2466 },
--         { item = 'card_weapon_firework', basePrice = 2532 },
--         { item = 'card_weapon_grenadelauncher', basePrice = 2599 },
--         -- Holo
--         { item = 'card_weapon_heavysniper_mk2', basePrice = 26000 },
--         { item = 'card_weapon_hominglauncher', basePrice = 26444 },
--         { item = 'card_weapon_minigun', basePrice = 26888 },
--         { item = 'card_weapon_precisionrifle', basePrice = 27332 },
--         { item = 'card_weapon_railgun', basePrice = 27776 },
--         { item = 'card_weapon_raycarbine', basePrice = 28220 },
--         { item = 'card_weapon_rayminigun', basePrice = 28664 },
--         { item = 'card_weapon_stungun', basePrice = 29108 },
--         { item = 'card_weapon_ball', basePrice = 29552 },
--         { item = 'card_weapon_battleaxe', basePrice = 30000 },
--         -- OriginalArt
--         { item = 'card_weapon_ceramicpistol', basePrice = 31000 },
--         { item = 'card_weapon_candycane', basePrice = 32000 },
--         { item = 'card_weapon_hazardcan', basePrice = 33000 },
--         { item = 'card_weapon_fertilizercan', basePrice = 34000 },
--         { item = 'card_weapon_molotov', basePrice = 35000 },
--         { item = 'card_weapon_pipebomb', basePrice = 35500 },
--         { item = 'card_weapon_snowball', basePrice = 36000 },
--         { item = 'card_weapon_flaregun', basePrice = 36500 },
--         { item = 'card_weapon_flare', basePrice = 37000 },
--         { item = 'card_weapon_jerrycan', basePrice = 37500 },
-- -- full_throttle
--         -- Normal
--         { item = 'card_panto', basePrice = 1 },
--         { item = 'card_dilettante', basePrice = 1 },
--         { item = 'card_asea', basePrice = 2 },
--         { item = 'card_regina', basePrice = 3 },
--         { item = 'card_journey', basePrice = 4 },
--         { item = 'card_taco', basePrice = 6 },
--         { item = 'card_boxville2', basePrice = 8 },
--         { item = 'card_feltzer2', basePrice = 9 },
--         { item = 'card_oracle', basePrice = 11 },
--         { item = 'card_sentinel2', basePrice = 13 },
--         { item = 'card_blista2', basePrice = 14 },
--         { item = 'card_issi2', basePrice = 16 },
--         { item = 'card_prairie', basePrice = 18 },
--         { item = 'card_ingot', basePrice = 19 },
--         { item = 'card_stratum', basePrice = 19 },
--         { item = 'card_premier', basePrice = 22 },
--         { item = 'card_stanier', basePrice = 23 },
--         { item = 'card_rhapsody', basePrice = 24 },
--         { item = 'card_faggio', basePrice = 26 },
--         { item = 'card_tractor', basePrice = 28 },
--         -- Uncommon
--         { item = 'card_bati', basePrice = 30 },
--         { item = 'card_akuma', basePrice = 32 },
--         { item = 'card_hakuchou2', basePrice = 34 },
--         { item = 'card_double', basePrice = 36 },
--         { item = 'card_sanchez', basePrice = 38 },
--         { item = 'card_manchez2', basePrice = 40 },
--         { item = 'card_faggio3', basePrice = 42 },
--         { item = 'card_faggio2', basePrice = 44 },
--         { item = 'card_bf400', basePrice = 48 },
--         { item = 'card_shinobi', basePrice = 51 },
--         { item = 'card_vindicator', basePrice = 53 },
--         { item = 'card_gargoyle', basePrice = 55 },
--         { item = 'card_chimera', basePrice = 57 },
--         { item = 'card_bmx', basePrice = 59 },
--         -- Rare
--         { item = 'card_sandking', basePrice = 105 },
--         { item = 'card_dubsta3', basePrice = 110 },
--         { item = 'card_kamacho', basePrice = 116 },
--         { item = 'card_draugur', basePrice = 121 },
--         { item = 'card_insurgent', basePrice = 127 },
--         { item = 'card_nightshark', basePrice = 132 },
--         { item = 'card_toros', basePrice = 138 },
--         { item = 'card_baller7', basePrice = 143 },
--         { item = 'card_rebel', basePrice = 149 },
--         { item = 'card_bifta', basePrice = 154 },
--         { item = 'card_freecrawler', basePrice = 160 },
--         { item = 'card_patriot3', basePrice = 165 },
--         { item = 'card_granger2', basePrice = 171 },
--         { item = 'card_marshall', basePrice = 176 },
--         -- Epic
--         { item = 'card_dominator', basePrice = 1400 },
--         { item = 'card_gauntlet4', basePrice = 1450 },
--         { item = 'card_deathbike', basePrice = 1500 },
--         { item = 'card_dukes', basePrice = 1550 },
--         { item = 'card_buccaneer', basePrice = 1600 },
--         { item = 'card_tornado', basePrice = 1650 },
--         { item = 'card_voodoo', basePrice = 1700 },
--         { item = 'card_hermes', basePrice = 1750 },
--         { item = 'card_mamba', basePrice = 1800 },
--         { item = 'card_ztype', basePrice = 1850 },
--         { item = 'card_monroe', basePrice = 1900 },
--         { item = 'card_peyote', basePrice = 1950 },
--         { item = 'card_coquette2', basePrice = 1999 },
--         -- Legendary
--         { item = 'card_elegy2', basePrice = 2000 },
--         { item = 'card_elegy', basePrice = 2040 },
--         { item = 'card_sultanrs', basePrice = 2080 },
--         { item = 'card_banshee2', basePrice = 2120 },
--         { item = 'card_jester4', basePrice = 2160 },
--         { item = 'card_calico', basePrice = 2200 },
--         { item = 'card_futo2', basePrice = 2240 },
--         { item = 'card_dominator7', basePrice = 2280 },
--         { item = 'card_previon', basePrice = 2320 },
--         { item = 'card_remus', basePrice = 2360 },
--         { item = 'card_rt3000', basePrice = 2400 },
--         { item = 'card_zr350', basePrice = 2440 },
--         { item = 'card_penumbra2', basePrice = 2480 },
--         { item = 'card_comet7', basePrice = 2520 },
--         { item = 'card_kuruma2', basePrice = 2560 },
--         -- Holo
--         { item = 'card_adder', basePrice = 26000 },
--         { item = 'card_zentorno', basePrice = 26200 },
--         { item = 'card_t20', basePrice = 26400 },
--         { item = 'card_osiris', basePrice = 26600 },
--         { item = 'card_emerus', basePrice = 26800 },
--         { item = 'card_krieger', basePrice = 27000 },
--         { item = 'card_italigto', basePrice = 27200 },
--         { item = 'card_pariah', basePrice = 27400 },
--         { item = 'card_turismor', basePrice = 27600 },
--         { item = 'card_infernus', basePrice = 27800 },
--         { item = 'card_cheetah', basePrice = 28000 },
--         { item = 'card_entityxf', basePrice = 28200 },
--         { item = 'card_vagner', basePrice = 28400 },
--         { item = 'card_tezeract', basePrice = 28600 },
--         { item = 'card_thrax', basePrice = 28800 },
--         { item = 'card_ignus', basePrice = 29000 },
--         { item = 'card_champion', basePrice = 29200 },
--         { item = 'card_nero2', basePrice = 29400 },
--         { item = 'card_xa21', basePrice = 29600 },
--         { item = 'card_tyrant', basePrice = 29800 },
--         -- OriginalArt
--         { item = 'card_entity3', basePrice = 31000 },
--         { item = 'card_furia', basePrice = 31500 },
--         { item = 'card_gp1', basePrice = 32000 },
--         { item = 'card_sultan3', basePrice = 32500 },
--         { item = 'card_kanjosj', basePrice = 33000 },
--         { item = 'card_penumbra', basePrice = 33500 },
--         { item = 'card_dominator8', basePrice = 34000 },
--         { item = 'card_vigero2', basePrice = 34500 },
--         { item = 'card_manana', basePrice = 35000 },
--         { item = 'card_terminus', basePrice = 35500 },
--         { item = 'card_dorado', basePrice = 36000 },
--         { item = 'card_benson', basePrice = 36500 },
-- -- ls_legends
--         -- Normal
--         { item = 'card_s_m_m_marine_02', basePrice = 1 },
--         { item = 'card_ig_englishdave', basePrice = 1 },
--         { item = 'card_g_m_m_mexboss_02', basePrice = 2 },
--         { item = 'card_ig_avon', basePrice = 3 },
--         { item = 'card_s_m_y_clown_01', basePrice = 4 },
--         { item = 'card_csb_bogdan', basePrice = 6 },
--         { item = 'card_u_f_y_lauren', basePrice = 8 },
--         { item = 'card_u_m_y_party_01', basePrice = 9 },
--         { item = 'card_u_f_y_bikerchic', basePrice = 11 },
--         { item = 'card_a_m_y_methhead_01', basePrice = 13 },
--         { item = 'card_u_f_y_beth', basePrice = 14 },
--         { item = 'card_ig_sol', basePrice = 16 },
--         { item = 'card_ig_tonyprince', basePrice = 18 },
--         { item = 'card_ig_lazlow_2', basePrice = 19 },
--         { item = 'card_ig_ortega', basePrice = 19 },
--         -- Uncommon
--         { item = 'card_ig_dom', basePrice = 30 },
--         { item = 'card_ig_maryann', basePrice = 32 },
--         { item = 'card_ig_barry', basePrice = 34 },
--         { item = 'card_ig_beverly', basePrice = 36 },
--         { item = 'card_ig_dreyfuss', basePrice = 38 },
--         { item = 'card_ig_abigail', basePrice = 40 },
--         { item = 'card_ig_josh', basePrice = 42 },
--         { item = 'card_ig_nigel', basePrice = 44 },
--         { item = 'card_ig_mrs_thornhill', basePrice = 46 },
--         { item = 'card_ig_maude', basePrice = 48 },
--         { item = 'card_ig_cletus', basePrice = 51 },
--         { item = 'card_ig_omega', basePrice = 53 },
--         { item = 'card_ig_tonya', basePrice = 55 },
--         { item = 'card_s_m_m_lifeinvad_01', basePrice = 57 },
--         { item = 'card_ig_hao', basePrice = 59 },
--         { item = 'card_ig_roccopelosi', basePrice = 61 },
--         -- Rare
--         { item = 'card_s_m_y_construct_01', basePrice = 105 },
--         { item = 'card_ig_talina', basePrice = 110 },
--         { item = 'card_ig_paige', basePrice = 116 },
--         { item = 'card_u_m_y_staggrm_01', basePrice = 121 },
--         { item = 'card_ig_lestercrest', basePrice = 127 },
--         { item = 'card_ig_lazlow', basePrice = 132 },
--         { item = 'card_ig_solomon', basePrice = 138 },
--         { item = 'card_s_m_y_devinsec_01', basePrice = 143 },
--         { item = 'card_ig_drfriedlander', basePrice = 149 },
--         { item = 'card_ig_oneil', basePrice = 154 },
--         { item = 'card_a_m_m_hillbilly_01', basePrice = 160 },
--         -- Epic
--         { item = 'card_s_m_m_highsec_01', basePrice = 1400 },
--         { item = 'card_s_m_m_highsec_02', basePrice = 1466 },
--         { item = 'card_s_m_m_fiboffice_02', basePrice = 1533 },
--         { item = 'card_s_m_y_blackops_01', basePrice = 1599 },
--         { item = 'card_s_m_y_blackops_02', basePrice = 1666 },
--         { item = 'card_ig_chef', basePrice = 1733 },
--         { item = 'card_hc_gunman', basePrice = 1799 },
--         { item = 'card_s_m_y_xmech_01', basePrice = 1866 },
--         { item = 'card_s_m_y_waretech_01', basePrice = 1932 },
--         { item = 'card_s_m_y_waiter_01', basePrice = 1999 },
--         { item = 'card_g_m_m_mexboss_01', basePrice = 2000 },
--         { item = 'card_ig_stretch', basePrice = 2066 },
--         { item = 'card_ig_ballasog', basePrice = 2133 },
--         { item = 'card_ig_jay_norris', basePrice = 2199 },
--         { item = 'card_u_m_y_antonb', basePrice = 2266 },
--         -- Legendary
--         { item = 'card_ig_davenorton', basePrice = 2000 },
--         { item = 'card_ig_stevehains', basePrice = 2066 },
--         { item = 'card_ig_andreas', basePrice = 2133 },
--         { item = 'card_ig_devin', basePrice = 2199 },
--         { item = 'card_ig_molly', basePrice = 2266 },
--         { item = 'card_ig_karen_daniels', basePrice = 2333 },
--         { item = 'card_ig_fbisuit_01', basePrice = 2399 },
--         { item = 'card_ig_patricia', basePrice = 2466 },
--         { item = 'card_ig_chengsr', basePrice = 2532 },
--         { item = 'card_ig_taocheng', basePrice = 2599 },
--         -- Holo
--         { item = 'card_player_zero', basePrice = 26000 },
--         { item = 'card_player_one', basePrice = 26444 },
--         { item = 'card_player_two', basePrice = 26888 },
--         { item = 'card_ig_amandatownley', basePrice = 27332 },
--         { item = 'card_ig_jimmydisanto', basePrice = 27776 },
--         { item = 'card_ig_tracydisanto', basePrice = 28220 },
--         { item = 'card_ig_lamardavis', basePrice = 28664 },
--         { item = 'card_a_c_chop', basePrice = 29108 },
--         { item = 'card_ig_nervousron', basePrice = 29552 },
--         { item = 'card_ig_wade', basePrice = 30000 },
--         -- OriginalArt
--         { item = 'card_ig_siemonyetarian', basePrice = 31000 },
--         { item = 'card_ig_chrisformage', basePrice = 31500 },
--         { item = 'card_ig_jimmyboston', basePrice = 32000 },
--         { item = 'card_ig_marnie', basePrice = 32500 },
--         { item = 'card_u_m_y_baygor', basePrice = 33000 },
--         { item = 'card_s_m_y_mime', basePrice = 33500 },
--         { item = 'card_u_m_y_pogo_01', basePrice = 34000 },
--         { item = 'card_u_m_y_imporage', basePrice = 34500 },
--         { item = 'card_u_f_y_princess', basePrice = 35000 },
--         { item = 'card_u_m_y_rsranger_01', basePrice = 35500 },
--         { item = 'card_u_f_y_hotposh_01', basePrice = 36000 },
--         { item = 'card_ig_benny', basePrice = 36500 },
--         { item = 'card_u_f_y_dancelthr_01', basePrice = 37000 },
--         { item = 'card_ig_vincent', basePrice = 37500 },
--         { item = 'card_s_m_y_valet_01', basePrice = 38000 },
-- -- ls_landmark
--         -- Normal
--         { item = 'card_los_santos_customs_burton', basePrice = 1 },
--         { item = 'card_supermarket_24_7', basePrice = 1 },
--         { item = 'card_ltd_gasoline', basePrice = 2 },
--         { item = 'card_ammu_nation_downtown', basePrice = 3 },
--         { item = 'card_fleeca_bank', basePrice = 4 },
--         { item = 'card_vanilla_unicorn', basePrice = 6 },
--         { item = 'card_bean_machine', basePrice = 8 },
--         { item = 'card_burger_shot', basePrice = 9 },
--         { item = 'card_cluckin_bell', basePrice = 11 },
--         { item = 'card_up_n_atom_burger', basePrice = 13 },
--         { item = 'card_hookies', basePrice = 14 },
--         { item = 'card_yellow_jack_inn', basePrice = 16 },
--         { item = 'card_liquor_ace', basePrice = 18 },
--         { item = 'card_hen_house', basePrice = 19 },
--         { item = 'card_tequi_la_la', basePrice = 19 },
--         { item = 'card_bahama_mamas', basePrice = 22 },
--         { item = 'card_los_santos_golf_club', basePrice = 23 },
--         { item = 'card_vespucci_tennis_courts', basePrice = 24 },
--         { item = 'card_public_library', basePrice = 26 },
--         { item = 'card_bishops_wtf_museum', basePrice = 28 },
--         -- Uncommon
--         { item = 'card_del_perro_pier', basePrice = 30 },
--         { item = 'card_pacific_standard_bank', basePrice = 32 },
--         { item = 'card_maze_bank_arena', basePrice = 34 },
--         { item = 'card_los_santos_international_airport', basePrice = 36 },
--         { item = 'card_port_of_south_los_santos', basePrice = 38 },
--         { item = 'card_union_depository', basePrice = 40 },
--         { item = 'card_fib_building', basePrice = 42 },
--         { item = 'card_iaa_building', basePrice = 44 },
--         { item = 'card_schlongberg_sachs_center', basePrice = 46 },
--         { item = 'card_richards_majestic_studio', basePrice = 48 },
--         { item = 'card_weazel_news_tower', basePrice = 51 },
--         { item = 'card_kortz_center', basePrice = 53 },
--         { item = 'card_ulsa_university', basePrice = 55 },
--         { item = 'card_st_fiacre_hospital', basePrice = 57 },
--         { item = 'card_central_los_santos_medical_center', basePrice = 59 },
--         { item = 'card_bolingbroke_penitentiary', basePrice = 61 },
--         { item = 'card_palmer_taylor_power_station', basePrice = 63 },
--         { item = 'card_ron_alternates_wind_farm', basePrice = 65 },
--         { item = 'card_davis_quartz_quarry', basePrice = 67 },
--         { item = 'card_redwood_lights_track', basePrice = 69 },
--         -- Rare
--         { item = 'card_vinewood_sign', basePrice = 105 },
--         { item = 'card_galileo_observatory', basePrice = 110 },
--         { item = 'card_diamond_casino_resort', basePrice = 116 },
--         { item = 'card_fort_zancudo', basePrice = 121 },
--         { item = 'card_humane_labs_and_research', basePrice = 127 },
--         { item = 'card_land_act_dam', basePrice = 132 },
--         { item = 'card_mount_chiliad_cable_car', basePrice = 138 },
--         { item = 'card_paleto_bay_sheriffs_office', basePrice = 143 },
--         { item = 'card_sandy_shores_airfield', basePrice = 149 },
--         { item = 'card_grapeseed_oneil_ranch', basePrice = 154 },
--         { item = 'card_dignity_village', basePrice = 160 },
--         { item = 'card_altruist_camp', basePrice = 165 },
--         { item = 'card_noose', basePrice = 171 },
--         { item = 'card_los_santos_city_hall', basePrice = 176 },
--         { item = 'card_mirror_park_lake', basePrice = 182 },
--         -- Epic
--         { item = 'card_maze_bank_tower', basePrice = 1400 },
--         { item = 'card_eclipse_towers', basePrice = 1450 },
--         { item = 'card_playboy_mansion', basePrice = 1500 },
--         { item = 'card_the_lighthouse', basePrice = 1550 },
--         { item = 'card_mount_gordo', basePrice = 1600 },
--         { item = 'card_mount_josiah', basePrice = 1650 },
--         { item = 'card_cassidy_creek_bridge', basePrice = 1700 },
--         { item = 'card_raton_canyon', basePrice = 1750 },
--         { item = 'card_north_yankton', basePrice = 1800 },
--         { item = 'card_cayo_perico_mansion', basePrice = 1850 },
--         { item = 'card_merryweather_hq', basePrice = 1900 },
--         { item = 'card_coveted_cove', basePrice = 1950 },
--         { item = 'card_calafia_bridge', basePrice = 1975 },
--         { item = 'card_tongva_valley_waterfall', basePrice = 1999 },
--         -- Legendary
--         { item = 'card_mount_chiliad_summit', basePrice = 2000 },
--         { item = 'card_the_sunken_ufo', basePrice = 2040 },
--         { item = 'card_the_sunken_cargo_ship', basePrice = 2080 },
--         { item = 'card_the_abandoned_mine_shaft', basePrice = 2120 },
--         { item = 'card_the_infinity_8_killers_house', basePrice = 2160 },
--         { item = 'card_the_epsilon_center', basePrice = 2200 },
--         { item = 'card_the_big_orange', basePrice = 2240 },
--         { item = 'card_the_giant_dinosaur', basePrice = 2280 },
--         -- Holo
--         { item = 'card_the_chiliad_mystery_mural', basePrice = 26000 },
--         { item = 'card_the_golden_tree', basePrice = 26500 },
--         { item = 'card_the_underwater_plane_wreck', basePrice = 27000 },
--         { item = 'card_de_santa_house', basePrice = 27500 },
--         { item = 'card_trevors_house', basePrice = 28000 },
--         { item = 'card_franklins_house', basePrice = 28500 },
--         { item = 'card_lamar_davis_house', basePrice = 29000 },
--         { item = 'card_lester_crests_house', basePrice = 29500 },
--         { item = 'card_ron_jakowski_house', basePrice = 30000 },
--         -- OriginalArt
--         { item = 'card_ls_river_concrete', basePrice = 31000 },
--         { item = 'card_vespucci_lifeguard_tower', basePrice = 31500 },
--         { item = 'card_grand_senora_highway', basePrice = 32000 },
--         { item = 'card_tinsel_towers', basePrice = 32500 },
--         { item = 'card_the_jetty', basePrice = 33000 },
--         { item = 'card_pipeline_inn', basePrice = 33500 },
--         { item = 'card_pillbox_hospital', basePrice = 34000 },
--         { item = 'card_oil_fields', basePrice = 34500 },
    }
}
