["drill"] = {
    ["name"] = "drill",
    ["label"] = "Drill",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "drill.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},
["bag"] = {
    ["name"] = "bag",
    ["label"] = "Bag",
    ["weight"] = 5,
    ["type"] = "item",
    ["image"] = "bag.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "Bag"
},
["c4_bomb"] = {
    ["name"] = "c4_bomb",
    ["label"] = "C4",
    ["weight"] = 100,
    ["type"] = "weapon",
    ["ammotype"] = nil,
    ["image"] = "weapon_stickybomb.png",
    ["unique"] = true,
    ["useable"] = false,
    ["description"] = "0x0x"
},
["hack_usb"] = {
    ["name"] = "hack_usb",
    ["label"] = "Hack USB",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "usb_device.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = "Handy software to shut down some systems"
},
["weed_pooch"] = {
    ["name"] = "weed_pooch",
    ["label"] = "Weed Pooch",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "blowtorch.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},
["coke_pooch"] = {
    ["name"] = "coke_pooch",
    ["label"] = "Coke Pooch",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "blowtorch.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},
["gold"] = {
    ["name"] = "gold",
    ["label"] = "Gold Bar",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "blowtorch.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
}
["big_bomb"] = {
    ["name"] = "big_bomb",
    ["label"] = "Big Bomb",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "big_bomb.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
}
["virus"] = {
    ["name"] = "virus",
    ["label"] = "Virus",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "virus.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
}
["chest_gold"] = {
    ["name"] = "chest_gold",
    ["label"] = "Chest Gold",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "chest_gold.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
}
["cashbon"] = {
    ["name"] = "cashbon",
    ["label"] = "Cashbon",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "cashbon.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
}
