crm_menus = {}

crm_menus.crm_menus = {
    -- crm-radialmenu -
    {
        crm_id = 'crm-general',
        crm_title = "General",
        crm_icon = "globe",
        crm_items = {
             {
                crm_id = 'selldrugs',
                crm_title = "Sell Drugs",
                crm_icon = "cannabis",
                crm_close_menu = true,
                crm_action = {crm_type = "crm-client", crm_event = "momof-drugsales:client:ToggleDrugSales"},
            },
            --         {
            --             crm_id = 'crm-interaction-location',
            --             crm_title = "Interaction Location",
            --             crm_icon = "house",
            --             crm_items = {
            --                 {
            --                     crm_id = 'crm-set-stash',
            --                     crm_title = "Set Stash",
            --                     crm_icon = "box",
            --                     crm_close = false,
            --                     crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:setLocation"},
            --                 },
            --                 {
            --                     crm_id = 'crm-set-wardrobe',
            --                     crm_title = "Set Wardrobe",
            --                     crm_icon = "shirt",
            --                     crm_close = false,
            --                     crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:setLocation"},
            --                 },
            --                 {
            --                     crm_id = 'crm-set-logout',
            --                     crm_title = "Set Logout",
            --                     crm_icon = "right-from-bracket",
            --                     crm_close = false,
            --                     crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:setLocation"},
            --                 },
            --             },
            --         },
            --         {
            --             crm_id = 'crm-give-house-keys',
            --             crm_title = "Give House Keys",
            --             crm_icon = "key",
            --             crm_close = false,
            --             crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:giveHouseKey"},
            --         },
            --         {
            --             crm_id = 'crm-decorate-house',
            --             crm_title = "Decorate House",
            --             crm_icon = "holly-berry",
            --             crm_close = false,
            --             crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:decorate"},
            --         },
            --         {
            --             crm_id = 'crm-remove-house-keys',
            --             crm_title = "Remove House Keys",
            --             crm_icon = "key",
            --             crm_close = false,
            --             crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:removeHouseKey"},
            --         },
            --         {
            --             crm_id = 'crm-toggle-doorlock',
            --             crm_title = "Toggle Doorlock",
            --             crm_icon = "lock",
            --             crm_close = false,
            --             crm_action = {crm_type = "crm-client", crm_event = "qb-houses:client:toggleDoorlock"},
            --         },
            --     },
            -- },
            {
                crm_id = 'crm-clothes',
                crm_title = "Clothing",
                crm_icon = "shirt",
                crm_items = {
                    {
                        crm_id = 'crm-clth-mask',
                        crm_title = "Mask",
                        crm_icon = "mask",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                    },
                    {
                        crm_id = 'crm-clth-pants',
                        crm_title = "Pants",
                        crm_icon = "shirt",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                    },
                    {
                        crm_id = 'crm-clth-vest',
                        crm_title = "Vest",
                        crm_icon = "vest",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                    },

                    {
                        crm_id = 'crm-clth-shoes',
                        crm_title = "Shoes",
                        crm_icon = "shoe-prints",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                    },

                    {
                        crm_id = 'crm-clth-shirt',
                        crm_title = "Top",
                        crm_icon = "shirt",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                    },
                    {
                        crm_id = 'crm-clth-extras',
                        crm_title = "Extras",
                        crm_icon = "plus",
                        crm_items = {
                            {
                                crm_id = 'crm-clth-hat',
                                crm_title = "Hat",
                                crm_icon = "hat-cowboy",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                            {
                                crm_id = 'crm-clth-glasses',
                                crm_title = "Glasses",
                                crm_icon = "glasses",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                            {
                                crm_id = 'crm-clth-ear',
                                crm_title = "Ear",
                                crm_icon = "ear-listen",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                            {
                                crm_id = 'crm-clth-watch',
                                crm_title = "Watch",
                                crm_icon = "clock",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                            {
                                crm_id = 'crm-clth-bracelet',
                                crm_title = "Bracelet",
                                crm_icon = "hands-bound",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                            {
                                crm_id = 'crm-clth-bag',
                                crm_title = "Bag",
                                crm_icon = "bag-shopping",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                            {
                                crm_id = 'crm-clth-neck',
                                crm_title = "Neck",
                                crm_icon = "user-tie",
                                crm_close = false,
                                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-clothing"},
                            },
                        },
                    },
                },
            },
        },
    },
    -- crm-radialmenu -
    {
        crm_id = 'crm-citizen',
        crm_title = "Citizen",
        crm_icon = "user",
        crm_items = {
            {
                crm_id = 'crm-get-in-trunk',
                crm_title = "Get In Trunk",
                crm_icon = "car",
                crm_close = true,
                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:get-in-trunk"},
            },
            {
                crm_id = 'crm-get-out-trunk',
                crm_title = "Get Out Trunk",
                crm_icon = "car",
                crm_close = true,
                crm_action = {crm_type = "crm-client", crm_event = "crm-radial:get-out-trunk"},
            },
            -- {
            --     crm_id = 'crm-give-num',
            --     crm_title = "Give Phone Number",
            --     crm_icon = "address-book",
            --     crm_close = true,
            --     crm_action = {crm_type = "crm-client", crm_event = "qb-phone:client:GiveContactDetails"},
            -- },
        },
    },
    -- crm-radialmenu -
    {
        crm_id = 'crm-interactions',
        crm_title = "Interactions",
        crm_icon = "handshake",
        crm_items = {
            {
                crm_id = 'crm-put-in-vehicle',
                crm_title = "Put In Vehicle",
                crm_icon = "user-plus",
                crm_close = false,
                crm_action = {crm_type = "crm-client", crm_event = "police:client:PutPlayerInVehicle"},
            },
            {
                crm_id = 'crm-take-out-of-vehicle',
                crm_title = "Take Out Of Vehicle",
                crm_icon = "user-minus",
                crm_close = false,
                crm_action = {crm_type = "crm-client", crm_event = "police:client:SetPlayerOutVehicle"},
            },
            -- {
            --     crm_id = 'crm-cuff',
            --     crm_title = "Cuff",
            --     crm_icon = "handcuffs",
            --     crm_close = false,
            --     crm_action = {crm_type = "crm-client", crm_event = "police:client:CuffPlayerSoft"},
            -- },
            {
                crm_id = 'crm-rob',
                crm_title = "Rob",
                crm_icon = "people-robbery",
                crm_close = false,
                crm_action = {crm_type = "crm-client", crm_event = "police:client:RobPlayer"},
            },
            {
                crm_id = 'crm-escort',
                crm_title = "Escort",
                crm_icon = "people-arrows",
                crm_close = false,
                crm_action = {crm_type = "crm-client", crm_event = "police:client:EscortPlayer"},
            },
            {
                crm_id = 'take-hostage',
                crm_title = "Take Hostage",
                crm_icon = "mask",
                crm_close = false,
                crm_action = {crm_type = "crm-client", crm_event = "A5:Client:TakeHostage"},
            },
            {
                crm_id = 'crm-carry',
                crm_title = "Carry",
                crm_icon = "hands-holding",
                crm_close = false,
                crm_action = {crm_type = "crm-client", crm_event = "police:client:KidnapPlayer"},
            },
        },
    },
    -- crm-radialmenu -
    {
        crm_id = 'crm-vehicle',
        crm_title = "Vehicle",
        crm_icon = "car",
        crm_items = {
            {
                crm_id = 'crm-vehicle-doors',
                crm_title = "Vehicle Doors",
                crm_icon = "car",
                crm_items = {
                    {
                        crm_id = 'crm-door-4',
                        crm_title = "Hood",
                        crm_icon = "car",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-door"},
                    },
                    {
                        crm_id = 'crm-door-0',
                        crm_title = "Driver Door",
                        crm_icon = "car-side",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-door"},
                    },
                    {
                        crm_id = 'crm-door-1',
                        crm_title = "Passenger Door",
                        crm_icon = "car-side",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-door"},
                    },
                    {
                        crm_id = 'crm-door-2',
                        crm_title = "Left Back",
                        crm_icon = "car-side",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-door"},
                    },
                    {
                        crm_id = 'crm-door-3',
                        crm_title = "Right Back",
                        crm_icon = "car-side",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-door"},
                    },
                    {
                        crm_id = 'crm-door-5',
                        crm_title = "Trunk",
                        crm_icon = "car-rear",
                        crm_close = false,
                        crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-door"},
                    },
                    
                },
            },
            {
                crm_id = 'crm-flip-vehicle',
                crm_title = "Flip Vehicle",
                crm_icon = "repeat",
                crm_close = true,
                crm_action = {crm_type = "crm-client", crm_event = "os-quality:flipvehicle"},
            },
            -- {
            --     crm_id = 'crm-vehicle-seats',
            --     crm_title = "Vehicle Seats",
            --     crm_icon = "chair",
            --     crm_items = {
            --         {
            --             crm_id = 'crm-seat-1',
            --             crm_title = "Driver Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {-1}},
            --         },
            --         {
            --             crm_id = 'crm-seat-2',
            --             crm_title = "Passenger Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {0}},
            --         },
            --         {
            --             crm_id = 'crm-seat-3',
            --             crm_title = "Left Back Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {1}},
            --         },
            --         {
            --             crm_id = 'crm-seat-4',
            --             crm_title = "Right Back Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {2}},
            --         },
            --         {
            --             crm_id = 'crm-seat-5',
            --             crm_title = "Other Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {3}},
            --         },
            --         {
            --             crm_id = 'crm-seat-6',
            --             crm_title = "Other Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {4}},
            --         },
            --         {
            --             crm_id = 'crm-seat-7',
            --             crm_title = "Other Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {5}},
            --         },
            --         {
            --             crm_id = 'crm-seat-8',
            --             crm_title = "Other Seat",
            --             crm_icon = "caret-up",
            --             crm_action = {crm_type = "crm-client", crm_event = "crm-radial:toggle-seat", crm_args = {6}},
            --         },
            --     },
            -- },
        },
    },
}

crm_menus.crm_menu_job = {
    crm_title = "Work", 
    crm_icon = "briefcase",
}

crm_menus.crm_menu_jobs = {
    ['taxi'] = {
        {
            crm_id = 'crm-taxi-toggle-meter',
            crm_title = "Show/Hide Meter",
            crm_icon = "eye-slash",
            crm_close = false,
            crm_action = {crm_type = "crm-client", crm_event = "qb-taxi:client:toggleMeter"},
        },
        {
            crm_id = 'crm-taxi-meter',
            crm_title = "Start/Stop Meter",
            crm_icon = "hourglass-start",
            crm_close = false,
            crm_action = {crm_type = "crm-client", crm_event = "qb-taxi:client:enableMeter"},
        },
        {
            crm_id = 'crm-taxi-mission',
            crm_title = "NPC Mission",
            crm_icon = "taxi",
            crm_close = false,
            crm_action = {crm_type = "crm-client", crm_event = "qb-taxi:client:DoTaxiNpc"},
        },
    },
    ['police'] = {
        {
            crm_id = 'crm-emergencybutton',
            crm_title = "Silent Panic",
            crm_icon = "bell",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "police:client:SendPoliceEmergencyAlert"},
        },
        -- {
        --     crm_id = 'crm-trafficstop',
        --     crm_title = "Traffic Stop",
        --     crm_icon = "car-side",
        --     crm_close_menu = true,
        --     crm_action = {crm_type = "crm-client", crm_event = "ps-mdt:client:trafficStop"},
        -- },
        {
            crm_id = 'keep_gunrack_',
            crm_title = "Open Gun Rack",
            crm_icon = "car",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "keep-gunrack:client:open_gunrack_menu"},
        },
        {
            crm_id = 'crm-searchplayer',
            crm_title = "Search",
            crm_icon = "magnifying-glass",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "police:client:SearchPlayer"},
        },
        {
            crm_id = 'crm-policeinteraction',
            crm_title = "Grappler",
            crm_icon = "list",
            crm_items = {
                {
                    crm_id = 'crm-grapplerinstall',
                    crm_title = "Install Grappler",
                    crm_icon = "hammer",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "Client:installGrappler"},
                },
                {
                    crm_id = 'crm-grapplerremove',
                    crm_title = "Remove Grappler",
                    crm_icon = "delete-left",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "Client:removeGrappler"},
                },
                {
                    crm_id = 'crm-grapplerreset',
                    crm_title = "Reset Grappler",
                    crm_icon = "window-restore",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "Client:resetGrappler"},
                },
                -- {
                --     crm_id = 'crm-searchplayer',
                --     crm_title = "Search",
                --     crm_icon = "magnifying-glass",
                --     crm_close_menu = true,
                --     crm_action = {crm_type = "crm-server", crm_event = "police:server:SearchPlayer"},
                -- },
                -- {
                --     crm_id = 'crm-jailplayer',
                --     crm_title = "Jail",
                --     crm_icon = "user-lock",
                --     crm_close_menu = true,
                --     crm_action = {crm_type = "crm-client", crm_event = "police:client:JailPlayer"},
                -- },
                -- {
                --     crm_id = 'crm-cufftobed',
                --     crm_title = "(un) Cuff to Bed",
                --     crm_icon = "magnifying-glass",
                --     crm_close_menu = true,
                --     crm_action = {crm_type = "crm-client", crm_event = "qb-ambulancejob:client:CuffToBed"},
                -- },
            },
        },
        {
            crm_id = 'crm-policeobjects',
            crm_title = "Police Objects",
            crm_icon = "road",
            crm_items = {
                {
                    crm_id = 'cone',
                    crm_title = "Cone",
                    crm_icon = "triangle-exclamation",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj", crm_args = {'cone'}},
                }, 
                {
                    crm_id = 'barrier',
                    crm_title = "Gate",
                    crm_icon = "torii-gate",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                },
                {
                    crm_id = 'roadsign',
                    crm_title = "Speed Limit Sign",
                    crm_icon = "sign-hanging",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                },
                {
                    crm_id = 'tent',
                    crm_title = "Tent",
                    crm_icon = "campground",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                },
                {
                    crm_id = 'light',
                    crm_title = "Lighting",
                    crm_icon = "lightbulb",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                },
                {
                    crm_id = 'chair',
                    crm_title = "Chair",
                    crm_icon = "chair",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                },
                -- {
                --     crm_id = 'chairs',
                --     crm_title = "Chairs",
                --     crm_icon = "couch",
                --     crm_close_menu = true,
                --     crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                -- },
                {
                    crm_id = 'tabe',
                    crm_title = "Table",
                    crm_icon = "couch",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                },
                -- {
                --     crm_id = 'monitor',
                --     crm_title = "Monitor",
                --     crm_icon = "desktop",
                --     crm_close_menu = true,
                --     crm_action = {crm_type = "crm-client", crm_event = "police:client:spawnPObj"},
                -- },
                -- {
                --     crm_id = 'crm-spikestrip',
                --     crm_title = "Spike Strips",
                --     crm_icon = "caret-up",
                --     crm_close_menu = true,
                --     crm_action = {crm_type = "crm-client", crm_event = "police:client:SpawnSpikeStrip"},
                -- },
                {
                    crm_id = 'crm-deleteobject',
                    crm_title = "Remove object",
                    crm_icon = "trash",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "police:client:deleteObject"},
                },
            },
        },
    },
    ['k9'] = {
        {
            crm_id = 'crm-emergencybutton',
            crm_title = "Silent Panic",
            crm_icon = "bell",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "police:client:SendPoliceEmergencyAlert"},
        },
    },
    ['ambulance'] = {
        {
            crm_id = 'crm-statuscheck',
            crm_title = "Check Health Status",
            crm_icon = "heart-pulse",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "hospital:client:CheckStatus"},
        },
        {
            crm_id = 'crm-revivep',
            crm_title = "Revive",
            crm_icon = "hand-holding-heart",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "hospital:client:RevivePlayer"},
        },
        {
            crm_id = 'crm-treatwounds',
            crm_title = "Heal wounds",
            crm_icon = "hand-holding-medical",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "hospital:client:TreatWounds"},
        },
        {
            crm_id = 'crm-emergencybutton2',
            crm_title = "Silent Panic",
            crm_icon = "house",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "police:client:SendPoliceEmergencyAlert"},
        },
        {
            crm_id = 'crm-escort',
            crm_title = "Escort",
            crm_icon = "people-arrows",
            crm_close_menu = true,
            crm_action = {crm_type = "crm-client", crm_event = "police:client:EscortPlayer"},
        },
        {
            crm_id = 'crm-stretcheroptions',
            crm_title = "Stretcher",
            crm_icon = "truck-medical",
            crm_items = {
                {
                    crm_id = 'crm-spawnstretcher',
                    crm_title = "Spawn Stretcher",
                    crm_icon = "plus",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "qb-radialmenu:client:TakeStretcher"},
                },
                {
                    crm_id = 'crm-despawnstretcher',
                    crm_title = "Remove Stretcher",
                    crm_icon = "minus",
                    crm_close_menu = true,
                    crm_action = {crm_type = "crm-client", crm_event = "qb-radialmenu:client:RemoveStretcher"},
                },
            },
        },
    },
}