---@type PetShopItem[]
PetShopItems = {
    -- Example How use new VIP System Coins
    -- Warning: When you use **customCurrency** it will make a mix of the values, so it will charge both the regular money and the VIP amount. If you want it to only charge the VIP amount, just set the **price** value to 0.

    --  {
    --     key = "bedcomf9",
    --     price = 0,
    --     vip = true,
    --     category = "accessory_category_bed",
    --     customCurrency = {
    --         vip_coins = 50,
    --     },
    -- },
    {
        PetShopId = "pet_cat_black",
        key = "pet_cat_black",
        isPremiumPackage = true,
        thumbnail = "pet_cat_black.webp",
        label = "A Black Cat",
        price = 10000,
        category = "pet_category_pets",
        description = "An Black Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_pug",
        key = "pet_pug",
        label = "Pug",
        hasFemale = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Pug",
        canBeK9 = false,
        isPremiumPackage = true,
    },
    {
        PetShopId = "pet_hottweiler",
        key = "pet_chop",
        label = "Hottweiler",
        hasFemale = true,
        vip = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Hottweiler",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_dobermann_basic",
        key = "pet_dobermann",
        label = "Dobermann Brown",
        hasFemale = false,
        vip = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Dobermann",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_dobermann_black",
        key = "pet_dobermann",
        thumbnail = "pet_dobermann_black.webp",
        label = "Dobermann Black",
        hasFemale = true,
        vip = true,
        isPremiumPackage = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Dobermann",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 1
            }
        },
        canBeK9 = false,
    },
    {
        PetShopId = "pet_husky_gray",
        key = "pet_husky",
        thumbnail = "pet_husky_gray.webp",
        label = "Husky Gray",
        hasFemale = true,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Husky",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_husky_caramel",
        key = "pet_husky",
        thumbnail = "pet_husky_caramel.webp",
        hasFemale = true,
        vip = true,
        label = "Husky Caramel",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Husky",
        customization = {
            drawables = {
                ["4"] = 0,
                ["3"] = 0,
            },
            textures = {
                ["4"] = 1,
                ["3"] = 1,
            }
        },
        canBeK9 = false,
    },
    {
        PetShopId = "pet_husky_light_gray",
        key = "pet_husky",
        thumbnail = "pet_husky_light_gray.webp",
        label = "Husky Light Gray",
        isPremiumPackage = true,
        price = 20000,
        hasFemale = true,
        vip = true,
        category = "pet_category_pets",
        description = "A Husky",
        customization = {
            drawables = {
                ["4"] = 0,
                ["3"] = 0,
            },
            textures = {
                ["4"] = 2,
                ["3"] = 2,
            }
        },
        canBeK9 = false,
    },
    {
        PetShopId = "pet_husky_white",
        key = "pet_husky",
        thumbnail = "pet_husky_white.webp",
        label = "Husky White",
        isPremiumPackage = true,
        price = 20000,
        hasFemale = true,
        vip = true,
        category = "pet_category_pets",
        description = "A Husky",
        customization = {
            drawables = {
                ["4"] = 0,
                ["3"] = 0,
            },
            textures = {
                ["4"] = 3,
                ["3"] = 3,
            }
        },
        canBeK9 = false,
    },
    {
        PetShopId = "pet_gold",
        key = "pet_gold",
        label = "Golden Retriever",
        isPremiumPackage = true,
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Golden Retriever",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_shusky",
        key = "pet_shusky",
        label = "Small Husky",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Small Husky",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_chiua",
        key = "pet_chiua",
        label = "Chihuahua",
        hasFemale = true,
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Chihuahua",
        canBeK9 = false,
        isPremiumPackage = true,
    },
    {
        PetShopId = "pet_dash",
        key = "pet_dash",
        label = "Dachshund",
        hasFemale = true,
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Dachshund",
        canBeK9 = false,
        isPremiumPackage = true,
    },
    {
        PetShopId = "pet_york",
        key = "pet_york",
        label = "Yorkshire Terrier",
        hasFemale = true,
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Yorkshire Terrier",
        canBeK9 = false,
        isPremiumPackage = true,
    },
    {
        PetShopId = "pet_poodle",
        key = "pet_poodle",
        label = "Poodle",
        isPremiumPackage = true,
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Poodle",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_akita",
        key = "pet_akita",
        thumbnail = "pet_akita.webp",
        label = "Akita",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Akita",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_austshep",
        key = "pet_austshep",
        thumbnail = "pet_austshep.webp",
        label = "Australian Shepherd",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Australian Shepherd",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_bloodhound",
        key = "pet_bloodhound",
        thumbnail = "pet_bloodhound.webp",
        label = "Bloodhound",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Bloodhound",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_engbulldog",
        key = "pet_engbulldog",
        thumbnail = "pet_engbulldog.webp",
        label = "English Bulldog",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A English Bulldog",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_bulldogpup",
        key = "pet_bulldogpup",
        thumbnail = "pet_bulldogpup.webp",
        label = "Bulldog Puppy",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Bulldog Puppy",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_terrierk",
        key = "pet_terrierk",
        label = "Terrier",
        hasFemale = false,
        vip = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Terrier",
        canBeK9 = false,
        isPremiumPackage = true,
    },
    {
        PetShopId = "pet_bulldog_black",
        key = "pet_frbul",
        thumbnail = "pet_frbull_black.webp",
        hasFemale = true,
        vip = true,
        label = "Bulldog Black",
        isPremiumPackage = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Bulldog",
    },
    {
        PetShopId = "pet_frbul_brown",
        key = "pet_frbul",
        thumbnail = "pet_frbull_brown.webp",
        hasFemale = true,
        vip = true,
        label = "Bulldog Brown",
        isPremiumPackage = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Bulldog",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 1,
            }
        },
    },
    {
        PetShopId = "pet_frbul_caramel",
        key = "pet_frbul",
        thumbnail = "pet_frbull_caramel.webp",
        hasFemale = true,
        vip = true,
        label = "Bulldog Caramel",
        isPremiumPackage = true,
        price = 10000,
        category = "pet_category_pets",
        description = "A Bulldog",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 2,
            }
        },
    },
    {
        PetShopId = "pet_bully_white",
        key = "pet_bully",
        thumbnail = "pet_bully_white.webp",
        hasFemale = true,
        vip = true,
        label = "American Bully White",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "An American Bully White",
    },
    {
        PetShopId = "pet_bully_black",
        key = "pet_bully",
        thumbnail = "pet_bully_black.webp",
        hasFemale = true,
        vip = true,
        label = "American Bully Black",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "An American Bully Black",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 1,
            }
        },
    },
    {
        PetShopId = "pet_bully_brown",
        key = "pet_bully",
        thumbnail = "pet_bully_brown.webp",
        hasFemale = true,
        vip = true,
        label = "American Bully Brown",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "An American Bully Brown",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 2,
            }
        },
    },
    {
        PetShopId = "pet_shep",
        key = "pet_shep",
        thumbnail = "pet_shep.webp",
        hasFemale = true,
        vip = true,
        label = "German Shepherd",
        isPremiumPackage = true,
        price = 30000,
        category = "pet_category_pets",
        description = "A German Shepherd",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_chow",
        key = "pet_chow",
        thumbnail = "pet_chowchow.webp",
        hasFemale = false,
        vip = true,
        label = "Chow Chow",
        isPremiumPackage = true,
        price = 30000,
        category = "pet_category_pets",
        description = "A Chow Chow",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_minpit",
        key = "pet_minpit",
        thumbnail = "pet_pitt_cream.webp",
        hasFemale = false,
        vip = true,
        label = "Pit Bull Mini",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Mini Pitbull",
    },
    {
        PetShopId = "pet_dal",
        key = "pet_dal",
        thumbnail = "pet_dal.webp",
        hasFemale = false,
        vip = true,
        label = "Dalmatian",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Dalmatian",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_mal",
        key = "pet_mal",
        thumbnail = "pet_mal.webp",
        hasFemale = false,
        vip = true,
        label = "Belgian Malinois",
        isPremiumPackage = true,
        price = 30000,
        category = "pet_category_pets",
        description = "A Belgian Malinois",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_pitt_cream",
        key = "pet_pitt",
        thumbnail = "pet_pitt_cream.webp",
        hasFemale = false,
        vip = true,
        label = "Pit Bull Cream",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Pit Bull Cream",
    },
    {
        PetShopId = "pet_pitt_brown",
        key = "pet_pitt",
        thumbnail = "pet_pitt_brown.webp",
        hasFemale = false,
        vip = true,
        label = "Pit Bull Brown",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Pit Bull Brown",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 1,
            }
        },
    },
    {
        PetShopId = "pet_pitt_gray",
        key = "pet_pitt",
        thumbnail = "pet_pitt_gray.webp",
        hasFemale = false,
        vip = true,
        label = "Pit Bull Gray",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Pit Bull Gray",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 2,
            }
        },
    },
    {
        PetShopId = "pet_pitt_darkbrown",
        key = "pet_pitt",
        thumbnail = "pet_pitt_darkbrown.webp",
        hasFemale = false,
        vip = true,
        label = "Pit Bull Dark Brown",
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Dark Brown Pit Bull",
        customization = {
            drawables = {
                ["4"] = 0,
            },
            textures = {
                ["4"] = 3,
            }
        },
    },
    {
        PetShopId = "pet_bichon",
        key = "pet_bichon",
        thumbnail = "pet_bichon.webp",
        label = "Bichon Frise",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Bichon Frise",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_dalpup",
        key = "pet_dalpup",
        thumbnail = "pet_dalpup.webp",
        label = "Dalmatian Pup",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Dalmatian Pup",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_goldenpup",
        key = "pet_goldenpup",
        thumbnail = "pet_goldenpup.webp",
        label = "Golden Pup",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Golden Pup",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_shepup",
        key = "pet_shepup",
        thumbnail = "pet_shepup.webp",
        label = "Shepherd Pup",
        hasFemale = false,
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "A Shepherd Pup",
        canBeK9 = false,
    },
    -- {
    --     PetShopId = "pet_animal_capy",
    --     key = "pet_animal_capy",
    --     thumbnail = "pet_animal_capy.webp",
    --     label = "Capybara",
    --     hasFemale = false,
    --     isPremiumPackage = true,
    --     price = 5000,
    --     category = "pet_category_pets",
    --     description = "A Capybara",
    --     canBeK9 = false,
    -- },
    -- {
    --     PetShopId = "pet_animal_lion",
    --     key = "pet_animal_lion",
    --     thumbnail = "pet_animal_lion.webp",
    --     label = "Lion",
    --     hasFemale = false,
    --     isPremiumPackage = true,
    --     price = 5000,
    --     category = "pet_category_pets",
    --     description = "A Lion",
    --     canBeK9 = false,
    -- },
    -- {
    --     PetShopId = "pet_animal_puma",
    --     key = "pet_animal_puma",
    --     thumbnail = "pet_animal_puma.webp",
    --     label = "Puma",
    --     hasFemale = false,
    --     isPremiumPackage = true,
    --     price = 5000,
    --     category = "pet_category_pets",
    --     description = "A Puma",
    --     canBeK9 = false,
    -- },
    -- {
    --     PetShopId = "pet_animal_tiger",
    --     key = "pet_animal_tiger",
    --     thumbnail = "pet_animal_tiger.webp",
    --     label = "Tiger",
    --     hasFemale = false,
    --     isPremiumPackage = true,
    --     price = 5000,
    --     category = "pet_category_pets",
    --     description = "A Tiger",
    --     canBeK9 = false,
    -- },
    -- Cats
    {
        PetShopId = "pet_amer_orange",
        key = "pet_amer",
        thumbnail = "pet_amer_orange.webp",
        label = "Orange American Cat",
        vip = true,
        price = 10000,
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_grey",
        key = "pet_amer",
        thumbnail = "pet_amer_grey.webp",
        label = "Grey American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 1,
                ["3"] = 1,
                ["6"] = 1,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_white",
        key = "pet_amer",
        thumbnail = "pet_amer_white.webp",
        label = "White American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 2,
                ["3"] = 2,
                ["6"] = 2,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_gray",
        key = "pet_amer",
        thumbnail = "pet_amer_gray.webp",
        label = "Gray American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 3,
                ["3"] = 3,
                ["6"] = 3,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_black",
        key = "pet_amer",
        thumbnail = "pet_amer_black.webp",
        label = "Black American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 4,
                ["3"] = 4,
                ["6"] = 4,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_black_orange_eyes",
        key = "pet_amer",
        thumbnail = "pet_amer_black_orange_eyes.webp",
        label = "Black Orange Eyes American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 8,
                ["3"] = 8,
                ["6"] = 8,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_blue_eyes_orange",
        key = "pet_amer",
        thumbnail = "pet_amer_blue_eyes_orange.webp",
        label = "Blue Eyes Orange American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 5,
                ["3"] = 5,
                ["6"] = 5,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_brown",
        key = "pet_amer",
        thumbnail = "pet_amer_brown.webp",
        label = "Brown American Cat",
        vip = true,
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 6,
                ["3"] = 6,
                ["6"] = 6,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_black",
        key = "pet_turk",
        label = "Black Turkish Cat",
        vip = true,
        thumbnail = "pet_turk_black.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 1,
                ["3"] = 1,
                ["6"] = 1,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_amer_white_grey",
        key = "pet_amer",
        thumbnail = "pet_amer_grey.webp",
        vip = true,
        label = "White and Grey American Cat",
        price = 10000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 7,
                ["3"] = 7,
                ["6"] = 7,
            }
        },
        category = "pet_category_pets",
        description = "An American Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_white",
        key = "pet_turk",
        label = "White Turkish Cat",
        vip = true,
        thumbnail = "pet_turk_white.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 2,
                ["3"] = 2,
                ["6"] = 2,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_white_heterochromia",
        key = "pet_turk",
        thumbnail = "pet_turk_white_heterochromia.webp",
        label = "White Heterochromia Cat",
        vip = true,
        isPremiumPackage = true,
        price = 20000,
        category = "pet_category_pets",
        description = "An Orange Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_grey",
        key = "pet_turk",
        label = "Grey Turkish Cat",
        vip = true,
        thumbnail = "pet_turk_grey.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 3,
                ["3"] = 3,
                ["6"] = 3,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_snow_1",
        key = "pet_turk",
        label = "Snow Turkish Cat 1",
        vip = true,
        thumbnail = "pet_turk_snow.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 4,
                ["3"] = 4,
                ["6"] = 4,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_snow_2",
        key = "pet_turk",
        label = "Snow Turkish Cat 2",
        vip = true,
        thumbnail = "pet_turk_snow_2.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 5,
                ["3"] = 5,
                ["6"] = 5,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_snow_3",
        key = "pet_turk",
        label = "Snow Turkish Cat 3",
        vip = true,
        thumbnail = "pet_turk_snow_3.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 6,
                ["3"] = 6,
                ["6"] = 6,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_turk_snow_4",
        key = "pet_turk",
        label = "Snow Turkish Cat 4",
        vip = true,
        thumbnail = "pet_turk_snow_4.webp",
        isPremiumPackage = true,
        price = 20000,
        customization = {
            drawables = {
                ["0"] = 0,
                ["3"] = 0,
                ["6"] = 0,
            },
            textures = {
                ["0"] = 7,
                ["3"] = 7,
                ["6"] = 7,
            }
        },
        category = "pet_category_pets",
        description = "A Turkish Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_synphix_default",
        key = "pet_synphix",
        thumbnail = "pet_cat_synphix.webp",
        label = "Synphix Cat",
        vip = true,
        price = 10000,
        isPremiumPackage = true,
        category = "pet_category_pets",
        description = "An Synphix Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_wcoon_default",
        key = "pet_wcoon",
        thumbnail = "pet_cat_wcoon.webp",
        label = "Wcoon Cat",
        vip = true,
        price = 30000,
        isPremiumPackage = true,
        category = "pet_category_pets",
        description = "An Wcoon Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_wolf_default",
        key = "pet_wolf",
        isPremiumPackage = true,
        thumbnail = "pet_cat_wolf.webp",
        label = "Wolf Cat",
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "An Wcoon Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_cat_egyptian",
        key = "pet_cat_egyptian",
        isPremiumPackage = true,
        thumbnail = "pet_cat_egyptian.webp",
        label = "A Egyptian Cat",
        vip = true,
        price = 10000,
        category = "pet_category_pets",
        description = "An Egyptian Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_cat_grey",
        key = "pet_cat_grey",
        isPremiumPackage = true,
        thumbnail = "pet_cat_grey.webp",
        label = "A Grey Cat",
        vip = true,
        price = 20000,
        category = "pet_category_pets",
        description = "An Grey Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_cat_siamese",
        key = "pet_cat_siamese",
        isPremiumPackage = true,
        vip = true,
        thumbnail = "pet_cat_siamese.webp",
        label = "A Siamese Cat",
        price = 20000,
        category = "pet_category_pets",
        description = "An Siamese Cat",
        canBeK9 = false,
    },
    {
        PetShopId = "pet_cat_tricolor",
        key = "pet_cat_tricolor",
        isPremiumPackage = true,
        vip = true,
        thumbnail = "pet_cat_tricolor.webp",
        label = "A Tricolor Cat",
        price = 20000,
        category = "pet_category_pets",
        description = "An Siamese Cat",
        canBeK9 = false,
    },
    {
        key = "dummy",
        price = 5000,
        category = "accesorry_category_training",
    },
    {
        key = "cdev_pets_plataform1",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "cdev_pets_sandbox1_a",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "cdev_pets_bowl1_a",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl1_b",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl1_c",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl1_e",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl1_f",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl2_a",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl2_b",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl2_c",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl2_d",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl2_e",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl2_f",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_a",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_b",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_c",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_d",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_e",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_f",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_g",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_h",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_i",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl3_j",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_a",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_b",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_c",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_d",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_e",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_f",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_g",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_bowl4_h",
        price = 2500,
        category = "accessory_category_bowl"
    },
    {
        key = "cdev_pets_sandbox1_b",
        price = 2500,
        category = "accessory_category_toys",
    },
    {
        key = "cdev_pets_sandbox1_c",
        price = 2500,
        category = "accessory_category_toys",
    },
    {
        key = "cdev_pets_sandbox1_d",
        price = 2500,
        category = "accessory_category_toys",
    },
    {
        key = "catbaga",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagb",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagc",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagd",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbage",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagf",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagg",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagh",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "catbagi",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbaga",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagb",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagc",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagd",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbage",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagf",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagg",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagh",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "bigdogbagi",
        price = 7500,
        category = "accessory_category_toys"
    },
    {
        key = "dogbaga",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagb",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagc",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagd",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbage",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagf",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagg",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagh",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "dogbagi",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cone",
        price = 5000,
        category = "accesorry_category_training"
    },
    {
        key = "ramp",
        price = 5000,
        category = "accesorry_category_training"
    },
    {
        key = "scratch1a",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "bedbasketa",
        price = 5000,
        category = "accessory_category_bed"
    },
    {
        key = "bedbasketb",
        price = 5000,
        category = "accessory_category_bed"
    },
    {
        key = "bedbasketc",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedsubmarinea",
        price = 5000,
        category = "accessory_category_bed"
    },
    {
        key = "bedsubmarineb",
        price = 5000,
        category = "accessory_category_bed"
    },
    {
        key = "bedsubmarinec",
        price = 5000,
        category = "accessory_category_bed"
    },
    {
        key = "cdev_pets_tree1_a",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "cdev_pets_tree1_b",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "cdev_pets_tree1_c",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "cdev_pets_tree2_a",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "cdev_pets_tree2_b",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "cdev_pets_tree2_c",
        price = 5000,
        category = "accessory_category_bed",
    },

    {
        key = "cdev_pets_ball1_a",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_b",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_c",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_d",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_e",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_f",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_g",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_h",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_i",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "cdev_pets_ball1_j",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "scratch1b",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "scratch1c",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "scratch1d",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "scratch1e",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "scratch1f",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "scratch2a",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "scratch2b",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "scratch2c",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "scratch2d",
        price = 5000,
        category = "accessory_category_toys"
    },
    {
        key = "hoop",
        price = 5000,
        category = "accesorry_category_training",
    },
    {
        key = "purpleshoes",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "blackcollarstrass",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "goldcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "whitecollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greencamohoodie",
        price = 5000,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "gunnerleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "blackandredleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "silverpendantcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "goldpendantcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greendothoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "yellowbootslong",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "orangehoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "bluebootslong",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "redbootslong",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "whitehoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "snowbootsgray",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "pinkhoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "purplehoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "snowbootsblue",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "lightpinkhoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "sneakersblue",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "whitebrownhoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "sneakerspurple",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "oragecamohoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "sneakersgreen",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "bluecamohoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "halowingsgoldwhite",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "pinkcamohoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "purplecamohoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camohoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "halowingsgold",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "halowingssilverblack",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "blacksailorcape",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "halowingsgoldpink",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "pinksailorcape",
        price = 5000,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "yellowflowers",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "graysailorcape",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camosailorcape",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "plaidsailorcape",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "pinkskirt",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "suit",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "animlaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camovest",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camored",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camoblack",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camobluewhite",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camoblueyellow",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "camodarkblue",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "trouble",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "flowersdarkbow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "bluelinesbow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "greenplaidbow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "policecap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "redsailorcap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "heartsbow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "pinkbow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "bluesailorcap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "medicalcap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "kapolicecap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "whiteflowers",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "pinkflowers",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "bedbones",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcream",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedgold",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedmaster",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedmodern",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedold",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedplaid",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedwood",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedbath",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedsmall",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedflower",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedhouse",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedhammock",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedprincess",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedpumpkin",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bedpumpkinhollow",
        price = 5000,
        category = "accessory_category_bed",
        vip = true,
    },
    {
        key = "bluebowl",
        price = 2500,
        category = "accessory_category_bowl",
    },
    {
        key = "brownbowl",
        price = 2500,
        category = "accessory_category_bowl",
    },
    {
        key = "greenbowl",
        price = 2500,
        category = "accessory_category_bowl",
    },
    {
        key = "redbowl",
        price = 2500,
        category = "accessory_category_bowl",
        vip = true,
    },
    {
        key = "silverbowl",
        price = 2500,
        category = "accessory_category_bowl",
        vip = true,
    },
    {
        key = "leashgreen",
        price = 5000,
        category = "accessory_category_leash",
    },
    {
        key = "cleanwater",
        price = 2500,
        category = "care_category_liquids",
    },
    {
        key = "petfood1",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "petfood2",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "petfood3",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "petfood4",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "petfood5",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "petfood6",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "pettreat1",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "pettreat2",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "pettreat3",
        price = 2500,
        category = "care_category_food",
    },
    {
        key = "petmedlow",
        price = 2500,
        category = "care_category_health",
    },
    {
        key = "petmedmed",
        price = 5000,
        category = "care_category_health",
    },
    {
        key = "petmedhigh",
        price = 7500,
        category = "care_category_health",
    },
    {
        key = "baseball",
        price = 5000,
        category = "accessory_category_toys",
    },
    {
        key = "greencollarbandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "redcollarbandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greycollarbandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "whitecollarbandana",
        price = 5000,
        category = "apparel_category_collar",
    },
    {
        key = "brownmask",
        price = 5000,
        category = "apparel_category_mask",
        vip = true,
    },
    {
        key = "beigemask",
        price = 5000,
        category = "apparel_category_mask",
        vip = true,
    },
    {
        key = "securitypatch",
        price = 5000,
        category = "apparel_category_patch",
        vip = true,
    },
    {
        key = "servicedogpatch",
        price = 5000,
        category = "apparel_category_patch",
        vip = true,
    },
    {
        key = "policepatch",
        price = 5000,
        category = "apparel_category_patch",
        vip = true,
    },
    {
        key = "rescuepatch",
        price = 5000,
        category = "apparel_category_patch",
        vip = true,
    },
    {
        key = "sheriffpatch",
        price = 5000,
        category = "apparel_category_patch",
        vip = true,
    },
    {
        key = "pinkyellowbootslong",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "pinkbootslong",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "yellowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "blueboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "greenboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "pinkwhitesnowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "darkbluesnowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "yellowsnowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "pinksnowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "greywhitesnowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "darkgreensnowboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "lightblueboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "pinkwhiteboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "redboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "beigeboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "bluedarklightboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "yelloworangeboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "yellowbootsshort",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "bluebandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinkbandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "redbandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "orangebandana",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinksunglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "blacksunglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "redsunglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "whitesunglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "blacksweater",
        price = 7500,
        category = "apparel_category_clothes",
    },
    {
        key = "pinksweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "greensweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "redsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "medfullyvest",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "medfullyvestpurple",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "k9fullyvestblack",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "k9fullyvestblackpolice",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "k9fullyvestbluepolice",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "k9fullyvestyellowpolice",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "k9fullyvestcammopolice",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "policestylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "whiteredstylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "purpleblackstylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "yellowrainbowstylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "whiterainbowstylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "lovemomstylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "lovedadstylishsweater",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "prop1",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "prop2",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "prop3",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "prop4",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "beigestyleboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "blackstyleboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "brownstyleboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "elfwhiteboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "elfgreenboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "elfbrownboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "redairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "pinkairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "blackairone",
        price = 5000,
        category = "apparel_category_shoes",
    },
    {
        key = "blueairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "cyanairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "greenairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "darkgreenairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "yellowairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "organgeairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "darkredairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "brownairone",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "wgsailorhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "piratehat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "wizhatwhite",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "wizhatpurple",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "beaniewhite",
        price = 5000,
        category = "apparel_category_head",
    },
    {
        key = "beanieyellow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "beanieblue",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "beaniepink",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "cowdog",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "whitecap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "whitepinkcap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "whiteyellowcap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "roundsunglasses",
        price = 2500,
        category = "apparel_category_glasses",
    },
    {
        key = "butterflycyanglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "butterflygreenglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "butterflyyellowglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "butterflypinkglasses",
        price = 2500,
        category = "apparel_category_glasses",
        vip = true,
    },
    {
        key = "pumpkinhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "devilearsred",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "devilearsblack",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "devilearsgreen",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "devilearspink",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "devilearsyellow",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "devilearsblue",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "wingsred",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "wingsblack",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "wingsgreen",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "wingsdarkblue",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "candyprop",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pumpkinprop",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "bigredwings",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "redorangewings",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "purplewings",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "pinkwings",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "bluewings",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "spiderprop1",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "spiderprop2",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "greenleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "tealleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "purpleleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greentealleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinkleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "redleathercollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greenskirt",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "redskirt",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "blueskirt",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "rainbowskirt",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "pinksuit",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "greensuit",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "bluesuit",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "whitesuit",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "tealsuit",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "skypajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "woolpajama",
        price = 7500,
        category = "apparel_category_clothes",
    },
    {
        key = "flowerspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "starspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "pandapajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "rainbowpajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "unicornpajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "duckpajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "duckpajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "chrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "greenchrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "whitechrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "brownchrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "greychrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "redchrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "cyanchrismaspajama",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "blackmchoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "aodmchoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "thelostmchoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "satanhoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "emohoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "witchhoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "witchfamilyhoodie",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troublered",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troublepurple",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troublegreen",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troubleyellow",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troubleorange",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troublepink",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "troubleblue",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "silverchaincollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "blackchaincollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "goldchaincollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "whitecollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "darkredcollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "redcollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greencollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "tealcollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinkcollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "darkbluecollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "beigecollarbow",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "rainbowcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "tiedyecollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pawcolorcollar",
        price = 5000,
        category = "apparel_category_collar",
    },
    {
        key = "brownpendantleacollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "redpendantleacollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greenpendantleacollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "tribalpendantleacollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinkpendantleacollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "metalcollarblack",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "metalcollargray",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "metalcollarwhite",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "silvermetalcollar",
        price = 5000,
        category = "apparel_category_collar",
    },
    {
        key = "whitetie",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "blacktie",
        price = 5000,
        category = "apparel_category_collar",
    },
    {
        key = "greentie",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinktie",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "brownboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "purpleboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "redbooots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "blackboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "greenbooots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "darkgreenboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "beigeboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "darkergreenboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "blackandwhiteboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "purpleandwhiteboots",
        price = 5000,
        category = "apparel_category_shoes",
        vip = true,
    },
    {
        key = "cowboyhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "deerantlerbrown",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "deerantlerwhite",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "deerantlerred",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "deerantlerlightbrown",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "deerantlerblack",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "blackhearttiara",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "redhearttiara",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "bluehearttiara",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "pinkhearttiara",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowcyanhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowpinkhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowblackhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowbeigehat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowredhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowbluehat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowpenguinhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "snowfishhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "darkbluepolicecap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "whiteandgoldpolicecap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "blackpolicecap",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "propellerhat",
        price = 5000,
        category = "apparel_category_head",
    },
    {
        key = "purplehearttiara",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "greennoelhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "noelhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "yellownoelhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "orangenoelhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "pinknoelhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "bluenoelhat",
        price = 5000,
        category = "apparel_category_head",
        vip = true,
    },
    {
        key = "hotdog",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "mechanicuniform",
        price = 7500,
        category = "apparel_category_clothes",
        vip = true,
    },
    {
        key = "beigescarf",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "grayscarf",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "bluescarf",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "lightpinkscarf",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinkscarf",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "chestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "blackchestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "bluechestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "pinkchestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "lightbluechestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "redchestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "greenchestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "purplechestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "lightpinkchestcollar",
        price = 5000,
        category = "apparel_category_collar",
        vip = true,
    },
    {
        key = "bedbath2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedbath3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedflower2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedflower3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedhouse2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedhouse3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedprincess2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedprincess3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedprincess4",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkin2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkin3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkin4",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkin5",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkin6",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkinhollow2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkinhollow3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedpumpkinhollow4",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedsmall2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedsmall3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf2",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf3",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf4",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf5",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf6",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf7",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf8",
        price = 5000,
        category = "accessory_category_bed",
    },
    {
        key = "bedcomf9",
        price = 5000,
        category = "accessory_category_bed",
    },
}
