import { iIndicatorSettings, iInRoom, iRoom } from "@/types/BasicTypes";
import { debugData } from "@/utils/debugData";

debugData([
  {
    action: "ui:setDefaultRooms",
    data: {
      [1]: {
        room_id: 1,
        daily_price: 1000,
        floor: 1,
        label: "De Santa Residence",
        price: 5999999,
      } as iRoom,
    },
  },
  {
    action: "ui:setInRoom",
    data: {
      apartment_id: 1,
      apartment_label: "",
      daily_price: 1000,
      due_date: 1721429675,
      floor: 1,
      label: "De Santa Residence",
      life_time: false,
      price: 30000,
      room_id: 1,
      owner: true,
      type: "square",
      owner_name: "Ali Koç",
      guest: false,
      indicators: {
        electricity: 320,
        water: 240,
        power: 400,
        gas: 750,
      },
      permissions: [
        {
          playerName: "Selin Korkmaz",
          user: "A1",
        },
      ],
      options: {
        lights: false,
        tint: 1,
      },
      furnitures: [
        {
          index: 1,
          isPlaced: true,
          label: "Test #1",
          model: "",
          objectId: 1,
          price: 1,
        },
        {
          index: 1,
          isPlaced: false,
          label: "Test #2",
          model: "",
          objectId: 1,
          price: 1,
        },
        {
          index: 1,
          isPlaced: true,
          label: "Test #3",
          model: "",
          objectId: 1,
          price: 1,
        },
      ],
    } as iInRoom,
  },
  { action: "ui:setSoldRooms", data: [] },
  {
    action: "ui:setHasDlc",
    data: {
      [1]: {
        dlc: "weed",
        value: true,
      },
    },
  },
  {
    action: "ui:setIndicatorSettings",
    data: {
      electricity: {
        maxValue: 999,
        unitPrice: 8,
      },
      power: {
        maxValue: 999,
        unitPrice: 8,
      },
      water: {
        maxValue: 999,
        unitPrice: 8,
      },
      gas: {
        maxValue: 999,
        unitPrice: 8,
      },
    } as iIndicatorSettings,
  },
  {
    action: "ui:setLocale",
    data: {
      locale: "en",
      languages: {
        buy: "Buy",
        your: "your",
        apart_room: "Apart Room",
        available_apartment_rooms: "Available rooms",
        no_rent: "Since you did not choose a rental day, you are purchasing it",
        you_buying_room: "You are buying room",
        rent_daily: "Rent Daily",
        desc_attention:
          "Before buying check documents of seller and about room!",
        attention: "Attention",
        price: "Price",
        market_price: "Market Price",
        purchase: "Purchase",
        cancel: "Cancel",
        security: "Security",
        setup: "Setup",
        apart_room_system: "Apart Room System",
        wall_color: "Wall Color",
        customize_your_walls: "Customize your walls",
        customize_your_room: "Customize your room",
        on: "ON",
        off: "OFF",
        lights: "Lights",
        furniture: "Furniture",
        cctv: "CCTV",
        desc_cctv: "Open CCTV Channel",
        toggle_lights: "Toggle Lights",
        indicators: "Indicators",
        electricity: "Electricity",
        power: "Power",
        gas: "Gas",
        water: "Water",
        permissions: "Permissions",
        desc_permissions: "Change neighboors permissions",
        player_id: "Player Id",
        search: "Search",
        add: "Add",
        guest: "Guest",
        owner: "Owner",
        type: "Type",
        leave: "Leave",
        desc_leave: "Leave the room permanently",
        double_click: "Double Click",
        // # \\
        money_type: "$",
        use: "Use",
        shop: "Shop",
        desc_shop: "You can refill your energy stores by buying them.",
        unit_x_money: "Unit {{unit}} {{money_type}}",
        desc_shop_buy: "Each time you buy 100 units. {{unit}}",
        DLC_Weed: "DLC: Weed",
        desc_buy_dlc: "Buy DLC to unlock this",
        rental_date: "Rental Date",
        time: "Time",
        life_time: "Life Time",
        select_floor:"Select Floor",
        lFurniture: {
          switch_mode: "Switch to {{mode}} Mode",
          snap_ground: "Snap To Ground",
          finish_editing: "Finish Editing",
          save: "Save",
          furniture_list: "Furniture List",
          desc_furniture_list: "Objects you can place or own.",
          input_search: "Search by name...",
          purchase: "Purchase",
          owned: "Owned",
          edit_furniture: "Edit Furniture",
          put_in_storage: "Put in Storage",
          place_on_ground: "Place on Ground",
          object_settings: "Object Settings",
          desc_object_settings: "Fine tune your placed object.",
          back_to_owned: "Back to Owned",
          resell: "Re-sell",
          delete_object: "Delete Object",
          desc_enter_del:
            "For [Enter] and [Del] you need to focus on the game!",
          camera_move: "Camera Move",
          camera_rotation: "Camera Rotation",
          placed: "Placed",
        },
      },
    },
  },
  {
    action: "ui:setWallColors",
    data: [
      { id: 1, color: "#FFFFFF" },
      { id: 2, color: "#747474" },
      { id: 3, color: "#232323" },
      { id: 4, color: "#351B7D" },
      { id: 5, color: "#FFB03A " },
      { id: 6, color: "#FFEB3A" },
      { id: 7, color: "#4383FF" },
      { id: 8, color: "#FF1A27" },
      { id: 9, color: "#048A02" },
      { id: 10, color: "#5AB0FF" },
      { id: 1, color: "#FFFFFF" },
      { id: 2, color: "#747474" },
      { id: 3, color: "#232323" },
      { id: 4, color: "#351B7D" },
      { id: 5, color: "#FFB03A " },
      { id: 6, color: "#FFEB3A" },
      { id: 7, color: "#4383FF" },
      { id: 8, color: "#FF1A27" },
      { id: 9, color: "#048A02" },
      { id: 10, color: "#5AB0FF" },
      { id: 1, color: "#FFFFFF" },
      { id: 2, color: "#747474" },
      { id: 3, color: "#232323" },
      { id: 4, color: "#351B7D" },
      { id: 5, color: "#FFB03A " },
      { id: 6, color: "#FFEB3A" },
      { id: 7, color: "#4383FF" },
      { id: 8, color: "#FF1A27" },
      { id: 9, color: "#048A02" },
      { id: 10, color: "#5AB0FF" },
      { id: 1, color: "#FFFFFF" },
      { id: 2, color: "#747474" },
      { id: 3, color: "#232323" },
      { id: 4, color: "#351B7D" },
      { id: 5, color: "#FFB03A " },
      { id: 6, color: "#FFEB3A" },
      { id: 7, color: "#4383FF" },
      { id: 8, color: "#FF1A27" },
      { id: 9, color: "#048A02" },
      { id: 10, color: "#5AB0FF" },
    ] as any,
  },
]);
