-- 
-- Just loads of data that you want need/want to tweak
-- You don't need to change anything here, unless you really want to
-- 

Config.SpeedLimits = {
  ["Abattoir Ave"] = 35,
  ["Abe Milton Pkwy"] = 50,
  ["Ace Jones Dr"] = 35,
  ["Adam's Apple Blvd"] = 50,
  ["Aguja St"] = 35,
  ["Algonquin Blvd"] = 35,
  ["Alhambra Dr"] = 35,
  ["Alta Pl"] = 50,
  ["Alta St"] = 50,
  ["Amarillo Vista"] = 35,
  ["Amarillo Way"] = 35,
  ["Americano Way"] = 35,
  ["Armadillo Ave"] = 35,
  ["Atlee St"] = 50,
  ["Autopia Pkwy"] = 50,
  ["Banham Canyon Dr"] = 65,
  ["Barbareno Rd"] = 35,
  ["Bay City Ave"] = 50,
  ["Bay City Incline"] = 50,
  ["Baytree Canyon Rd"] = 65,
  ["Boulevard Del Perro"] = 50,
  ["Bridge St"] = 35,
  ["Brouge Ave"] = 35,
  ["Buccaneer Way"] = 50,
  ["Buen Vino Rd"] = 65,
  ["Caesars Place"] = 35,
  ["Calafia Rd"] = 65,
  ["Calais Ave"] = 50,
  ["Capital Blvd"] = 50,
  ["Carcer Way"] = 50,
  ["Carson Ave"] = 50,
  ["Cascabel Ave"] = 35,
  ["Cassidy Trail"] = 65,
  ["Cat-Claw Ave"] = 65,
  ["Catfish View"] = 65,
  ["Cavalry Blvd"] = 50,
  ["Chianski Passage"] = 65,
  ["Cholla Rd"] = 35,
  ["Cholla Springs Ave"] = 35,
  ["Chum St"] = 50,
  ["Chupacabra St"] = 50,
  ["Clinton Ave"] = 50,
  ["Cockingend Dr"] = 35,
  ["Conquistador St"] = 35,
  ["Cortes St"] = 35,
  ["Cougar Ave"] = 50,
  ["Covenant Ave"] = 35,
  ["Cox Way"] = 35,
  ["Crusade Rd"] = 50,
  ["Davis Ave"] = 50,
  ["Decker St"] = 50,
  ["Del Perro Fwy"] = 85,
  ["Didion Dr"] = 35,
  ["Dorset Dr"] = 50,
  ["Duluoz Ave"] = 35,
  ["Dunstable Dr"] = 35,
  ["Dunstable Ln"] = 35,
  ["Dutch London St"] = 50,
  ["East Eclipse Blvd"] = 50,
  ["East Galileo Ave"] = 65,
  ["East Joshua Road"] = 65,
  ["East Mirror Dr"] = 35,
  ["Eastbourne Way"] = 50,
  ["Edwood Way"] = 35,
  ["El Burro Blvd"] = 50,
  ["El Rancho Blvd"] = 50,
  ["Elgin Ave"] = 50,
  ["Elysian Fields Fwy"] = 85,
  ["Equality Way"] = 50,
  ["Exceptionalists Way"] = 50,
  ["Fenwell Pl"] = 35,
  ["Fort Zancudo Approach Rd"] = 65,
  ["Forum Dr"] = 35,
  ["Fudge Ln"] = 35,
  ["Galileo Park"] = 65,
  ["Galileo Rd"] = 65,
  ["Gentry Lane"] = 35,
  ["Ginger St"] = 50,
  ["Glory Way"] = 35,
  ["Goma St"] = 35,
  ["Grapeseed Ave"] = 35,
  ["Grapeseed Main St"] = 35,
  ["Great Ocean Hwy"] = 85,
  ["Greenwich Pkwy"] = 50,
  ["Greenwich Pl"] = 35,
  ["Greenwich Way"] = 35,
  ["Grove St"] = 35,
  ["Hangman Ave"] = 35,
  ["Hanger Way"] = 50,
  ["Hardy Way"] = 35,
  ["Hawick Ave"] = 50,
  ["Heritage Way"] = 50,
  ["Hillcrest Ave"] = 35,
  ["Hillcrest Ridge Access Rd"] = 35,
  ["Imagination Ct"] = 35,
  ["Ineseno Road"] = 35,
  ["Innocence Blvd"] = 50,
  ["Integrity Way"] = 50,
  ["Invention Ct"] = 35,
  ["Jamestown St"] = 35,
  ["Joad Ln"] = 65,
  ["Joshua Rd"] = 65,
  ["Kimble Hill Dr"] = 35,
  ["Kortz Dr"] = 50,
  ["Labor Pl"] = 50,
  ["Lake Vinewood Dr"] = 35,
  ["Lake Vinewood Est"] = 35,
  ["La Puerta Fwy"] = 85,
  ["Laguna Pl"] = 50,
  ["Las Lagunas Blvd"] = 50,
  ["Lesbos Ln"] = 35,
  ["Liberty St"] = 50,
  ["Lindsay Circus"] = 50,
  ["Little Bighorn Ave"] = 50,
  ["Lolita Ave"] = 35,
  ["Los Santos Freeway"] = 85,
  ["Low Power St"] = 85,
  ["Macdonald St"] = 35,
  ["Mad Wayne Thunder Dr"] = 35,
  ["Magellan Ave"] = 35,
  ["Marathon Ave"] = 50,
  ["Marina Dr"] = 35,
  ["Marlowe Dr"] = 35,
  ["Melanoma St"] = 35,
  ["Meringue Ln"] = 35,
  ["Meteor St"] = 50,
  ["Milton Rd"] = 35,
  ["Mirror Park Blvd"] = 35,
  ["Mirror Pl"] = 35,
  ["Miriam Turner Overpass"] = 85,
  ["Morningwood Blvd"] = 50,
  ["Mountain View Dr"] = 35,
  ["Movie Star Way"] = 50,
  ["Mt Haan Rd"] = 65,
  ["Mt Vinewood Dr"] = 65,
  ["Mutiny Rd"] = 50,
  ["New Empire Way"] = 50,
  ["Nikola Ave"] = 35,
  ["Nikola Pl"] = 35,
  ["Niland Ave"] = 35,
  ["North Calafia Way"] = 65,
  ["North Conker Ave"] = 35,
  ["North Rockford Dr"] = 50,
  ["North Sheldon Ave"] = 35,
  ["Nowhere Rd"] = 65,
  ["O'Neil Way"] = 35,
  ["Occupation Ave"] = 50,
  ["Olympic Fwy"] = 85,
  ["Orchardville Ave"] = 50,
  ["Paleto Blvd"] = 35,
  ["Palomino Ave"] = 50,
  ["Palomino Fwy"] = 85,
  ["Panorama Dr"] = 35,
  ["Perth St"] = 50,
  ["Picture Perfect Drive"] = 35,
  ["Plaice Pl"] = 50,
  ["Playa Vista"] = 50,
  ["Popular St"] = 50,
  ["Portola Dr"] = 35,
  ["Power St"] = 50,
  ["Procopio Dr"] = 35,
  ["Procopio Promenade"] = 65,
  ["Prosperity St"] = 50,
  ["Pyrite Ave"] = 35,
  ["Red Desert Ave"] = 50,
  ["Richman St"] = 35,
  ["Rockford Dr"] = 50,
  ["Route 68"] = 65,
  ["Route 68 Approach"] = 65,
  ["Roy Lowenstein Blvd"] = 50,
  ["Rub St"] = 35,
  ["Sam Austin Dr"] = 35,
  ["San Andreas Ave"] = 50,
  ["San Vitus Blvd"] = 50,
  ["Sandcastle Way"] = 35,
  ["Seaview Rd"] = 65,
  ["Senora Fwy"] = 85,
  ["Senora Rd"] = 65,
  ["Senora Way"] = 65,
  ["Shank St"] = 50,
  ["Signal St"] = 50,
  ["Sinners Passage"] = 50,
  ["Sinner St"] = 50,
  ["Smoke Tree Rd"] = 65,
  ["South Arsenal St"] = 50,
  ["South Boulevard Del Perro"] = 50,
  ["South Mo Milton Dr"] = 35,
  ["South Rockford Dr"] = 50,
  ["South Shambles St"] = 50,
  ["Spanish Ave"] = 50,
  ["Strangeways Dr"] = 50,
  ["Strawberry Ave"] = 50,
  ["Supply St"] = 50,
  ["Sustancia Rd"] = 65,
  ["Swiss St"] = 50,
  ["Tackle St"] = 50,
  ["Tongva Dr"] = 65,
  ["Tower Way"] = 50,
  ["Tug St"] = 35,
  ["Union Rd"] = 65,
  ["Utopia Gardens"] = 35,
  ["Vespucci Blvd"] = 50,
  ["Vinewood Blvd"] = 50,
  ["Vinewood Park Dr"] = 35,
  ["Vitus St"] = 35,
  ["Voodoo Place"] = 50,
  ["West Eclipse Blvd"] = 50,
  ["West Galileo Ave"] = 65,
  ["West Mirror Drive"] = 35,
  ["Wild Oats Dr"] = 35,
  ["Whispymound Dr"] = 35,
  ["Zancudo Ave"] = 35,
  ["Zancudo Barranca"] = 65,
  ["Zancudo Grande Valley"] = 65,
  ["Zancudo Rd"] = 65
}

-- NOTE: This may already have been done in your framework: to avoid an unncessary thread
-- you can set this to false, delete it comment it out, whatever is easier for you :)
Config.HideBaseGameHudComponents = {
  1, -- WANTED_STARS,
  2, -- WEAPON_ICON
  3, -- CASH
  4, -- MP_CASH
  5, -- MP_MESSAGE
  6, -- VEHICLE_NAME
  7, -- AREA_NAME
  8, -- VEHICLE_CLASS
  9, -- STREET_NAME
  -- 10, --HELP_TEXT
  -- 11, --FLOATING_HELP_TEXT_1
  -- 12, --FLOATING_HELP_TEXT_2
  13, --CASH_CHANGE
  -- 14, --RETICLE
  -- 15, --SUBTITLE_TEXT
  -- 16, --RADIO_STATIONS
  -- 17, --SAVING_GAME,
  -- 18, --GAME_STREAM
  -- 19, --WEAPON_WHEEL
  -- 20, --WEAPON_WHEEL_STATS
  -- 21, --HUD_COMPONENTS
  -- 22, --HUD_WEAPONS
}

-- Use custom street or zone names
-- Tutorial: https://docs.jgscripts.com/hud/custom-street-zone-names
Config.CustomStreetNames = {
  -- [0xF5BF6BDD] = "Runway",
}
Config.CustomZoneNames = {
  -- AIRP = "Los Santos International Airport",
}
Config.CustomNamesShouldUpdateGameTextEntries = false

Config.WeaponNames = {
  WEAPON_KNIFE = "Knife",
  WEAPON_NIGHTSTICK = "Nightstick",
  WEAPON_HAMMER = "Hammer",
  WEAPON_BAT = "Bat",
  WEAPON_GOLFCLUB = "Golf Club",
  WEAPON_CROWBAR = "Crowbar",
  WEAPON_PISTOL = "Pistol",
  WEAPON_COMBATPISTOL = "Combat Pistol",
  WEAPON_APPISTOL = "AP Pistol",
  WEAPON_PISTOL50 = "Pistol 50",
  WEAPON_MICROSMG = "Micro SMG",
  WEAPON_SMG = "SMG",
  WEAPON_ASSAULTSMG = "Assault SMG",
  WEAPON_ASSAULTRIFLE = "Assault Rifle",
  WEAPON_CARBINERIFLE = "Carbine Rifle",
  WEAPON_ADVANCEDRIFLE = "Advanced Rifle",
  WEAPON_MG = "MG",
  WEAPON_COMBATMG = "Combat MG",
  WEAPON_PUMPSHOTGUN = "Pump Shotgun",
  WEAPON_SAWNOFFSHOTGUN = "Sawed-Off Shotgun",
  WEAPON_ASSAULTSHOTGUN = "Assault Shotgun",
  WEAPON_BULLPUPSHOTGUN = "Bullpup Shotgun",
  WEAPON_STUNGUN = "Stun Gun",
  WEAPON_SNIPERRIFLE = "Sniper Rifle",
  WEAPON_HEAVYSNIPER = "Heavy Sniper",
  WEAPON_GRENADELAUNCHER = "Grenade Launcher",
  WEAPON_RPG = "RPG",
  WEAPON_MINIGUN = "Minigun",
  WEAPON_GRENADE = "Grenade",
  WEAPON_STICKYBOMB = "Sticky Bomb",
  WEAPON_BZGAS = "BZ Gas",
  WEAPON_MOLOTOV = "Molotov",
  WEAPON_FIREEXTINGUISHER = "Fire Extinguisher",
  WEAPON_PETROLCAN = "Petrol Can",
  WEAPON_SNSPISTOL = "SNS Pistol",
  WEAPON_HEAVYPISTOL = "Heavy Pistol",
  WEAPON_SPECIALCARBINE = "Special Carbine",
  WEAPON_BULLPUPRIFLE = "Bullpup Rifle",
  WEAPON_BULLPUPRIFLE_MK2 = "Bullpup Rifle Mk II",
  WEAPON_MARKSMANRIFLE_MK2 = "Marksman Rifle Mk II",
  WEAPON_PUMPSHOTGUN_MK2 = "Pump Shotgun Mk II",
  WEAPON_SNSPISTOL_MK2 = "SNS Pistol Mk II",
  WEAPON_SPECIALCARBINE_MK2 = "Special Carbine Mk II",
  WEAPON_HOMINGLAUNCHER = "Homing Launcher",
  WEAPON_DOUBLEACTION = "Double-Action Revolver",
  WEAPON_REVOLVER_MK2 = "Heavy Revolver Mk II",
  WEAPON_RAYPISTOL = "Up-n-Atomizer",
  WEAPON_RAYCARBINE = "Unholy Hellbringer",
  WEAPON_RAYMINIGUN = "Widowmaker",
  WEAPON_GUSENBERG = "Gusenberg Sweeper",
  WEAPON_DAGGER = "Antique Cavalry Dagger",
  WEAPON_VINTAGEPISTOL = "Vintage Pistol",
  WEAPON_MUSKET = "Musket",
  WEAPON_FIREWORK = "Firework Launcher",
  WEAPON_RAILGUN = "Railgun",
  WEAPON_HATCHET = "Hatchet",
  WEAPON_MARKSMANRIFLE = "Marksman Rifle",
  WEAPON_HEAVYSHOTGUN = "Heavy Shotgun",
  WEAPON_CERAMICPISTOL = "Ceramic Pistol",
  WEAPON_COMBATSHOTGUN = "Combat Shotgun",
  WEAPON_GADGETPISTOL = "Perico Pistol",
  WEAPON_MILITARYRIFLE = "Military Rifle",
  WEAPON_FLAREGUN = "Flare Gun",
  WEAPON_NAVYREVOLVER = "Navy Revolver",
  WEAPON_KNUCKLE = "Brass Knuckles",
  WEAPON_MARKSMANPISTOL = "Marksman Pistol",
  WEAPON_COMBATPDW = "Combat PDW",
  WEAPON_DBSHOTGUN = "Double Barrel Shotgun",
  WEAPON_COMPACTRIFLE = "Compact Rifle",
  WEAPON_MACHINEPISTOL = "Machine Pistol",
  WEAPON_MACHETE = "Machete",
  WEAPON_FLASHLIGHT = "Flashlight",
  WEAPON_REVOLVER = "Heavy Revolver",
  WEAPON_SWITCHBLADE = "Switchblade",
  WEAPON_AUTOSHOTGUN = "Sweeper Shotgun",
  WEAPON_BATTLEAXE = "Battle Axe",
  WEAPON_COMPACTLAUNCHER = "Compact Grenade Launcher",
  WEAPON_MINISMG = "Mini SMG",
  WEAPON_POOLCUE = "Pool Cue",
  WEAPON_WRENCH = "Pipe Wrench",
  WEAPON_PIPEBOMB = "Pipe Bomb",
  WEAPON_CARBINERIFLE_MK2 = "Carbine Rifle Mk II",
  WEAPON_ASSAULTRIFLE_MK2 = "Assault Rifle Mk II",
  WEAPON_COMBATMG_MK2 = "Combat MG Mk II",
  WEAPON_SMG_MK2 = "SMG Mk II",
  WEAPON_HEAVYSNIPER_MK2 = "Heavy Sniper Mk II",
  WEAPON_PISTOL_MK2 = "Pistol Mk II",
  WEAPON_STONE_HATCHET = "Stone Hatchet",
  WEAPON_TACTICALRIFLE = "Tactical Rifle",
  WEAPON_PRECISIONRIFLE = "Precision Rifle",
  WEAPON_HEAVYRIFLE = "Heavy Rifle",
  WEAPON_TACTICALRIFLE = "Service Carbine",
  WEAPON_STUNGUN_MP = "Stun Gun",
  WEAPON_EMPLAUNCHER = "Compact EMP Launcher",
  WEAPON_BATTLERIFLE = "Battle Rifle",
  WEAPON_SNOWLAUNCHER = "Snowball Launcher",
  WEAPON_HUNTINGRIFLE = "Hunting Rifle",
  WEAPON_BALL = "Ball",
  WEAPON_ZKKNIFE = "K Knife",
  WEAPON_PISTOLXM3 = "WM 29 Pistol",
  WEAPON_TECPISTOL = "Tactical SMG",
  WEAPON_FLARE = "Flare",
  WEAPON_HAZARDCAN = "Hazard Can",
  WEAPON_METALDETECTOR = "Metal Detector",
  WEAPON_FERTILIZERCAN = "Fertilizer Can",
  WEAPON_CANDYCANE = "Candy Cane",
  WEAPON_CARROTKNIFE = "Carrot Knife",
  WEAPON_BATEASTER = "Easter Egg Bat",
  WEAPON_CHOCOLATEBAT = "Chocolate Bar Bat",
  WEAPON_CHOCOLATELOLLIPOP = "Chocolate Lollipop",
  WEAPON_CHOCOLATEBAT2 = "Chocolate Bat",
  WEAPON_HAMMERMARSHMALLOW = "Marshmallow Hammer",
  WEAPON_KNIFEEASTER1 = "Pink Easter Knife",
  WEAPON_KNIFEEASTER2 = "Teal Easter Knife",
  WEAPON_MACHETEEASTER = "Easter Blade",
  WEAPON_CANDY_CANE = "Candy Cane",
  WEAPON_PROXMINE = "Proximity Mine",
  WEAPON_RAILGUNXM3 = "Railgun XM3",
  WEAPON_SNOWBALL = "Snow Ball",
  WEAPON_TEARGAS = "Tear Gas",
  WEAPON_BRIEFCASE = "Briefcase",
  WEAPON_BRIEFCASE_02 = "Briefcase",
  WEAPON_GARBAGEBAG = "Garbage",
  WEAPON_HANDCUFFS = "Handcuffs",
  WEAPON_BREAD = "Baquette",
  WEAPON_HALLIGAN = "Halligan",
  WEAPON_CANDYAXE = "Candy Axe",
  WEAPON_PENETRATOR = "Dick Bat",
  WEAPON_SHIV = "Shiv",
  WEAPON_KATANA = "Light Sword",
  WEAPON_KATANA4 = "Katana",
  WEAPON_SLEDGEHAMMER = "Sledge Hammer",
  WEAPON_KARAMBIT = "Karambit",
  WEAPON_COLBATON = "Baton",
  WEAPON_BATS = "Baseball Bat",
  WEAPON_KATANA2 = "Just the Tip",
  WEAPON_KATANA3 = "Light Sword",
  WEAPON_2011 = "Evo",
  WEAPON_P226 = "P226",
  WEAPON_MCXSPEAR = "Spere",
  WEAPON_BOW = "Compound Bow",
  WEAPON_RFB = "RB",
  WEAPON_NSR9 = "R9",
  WEAPON_SA80 = "SA80",
  WEAPON_MUTANT_LONG = "Mutant",
  WEAPON_VIRTUS_4 = "Virtus",
  WEAPON_MK18 = "NK18",
  WEAPON_PROJECTX = "Project XR",
  WEAPON_PROJECTXSMG = "Project SXG",
  WEAPON_PROJECTXPISTOL = "Project X19",
  WEAPON_PROJECTXPISTOLUM = "Project X17",
  WEAPON_ARCTIC516 = "Arctic X",
  WEAPON_MP5 = "H&K MP5",
  WEAPON_AGC = "AG9",
  WEAPON_KVR = "KDR",
  WEAPON_P5 = "G5",
  WEAPON_PM4 = "P4",
  WEAPON_MREVOLVER = "PD Revolver",
  WEAPON_X19 = "x19",
  WEAPON_GANG1 = "x20",
  WEAPON_GANG2 = "x20",
  WEAPON_GANG3 = "x20",
  WEAPON_GANG4 = "x20",
  WEAPON_GANG5 = "x20",
  WEAPON_GANG6 = "x20",
  WEAPON_GANG7 = "x20",
  WEAPON_GANG8 = "x20",
  WEAPON_GANG9 = "x20",
  WEAPON_GANG10 = "x20",
  WEAPON_EASTERAP = "Easter x19",
  WEAPON_EASTERSEMI = "Easter Pistol",
  WEAPON_EASTERHB = "Easter XMG",
  WEAPON_RATREV = "Project X Rat Revolver",
  WEAPON_M320A = "M320",
  WEAPON_A45 = "x45",
  WEAPON_C36 = "C36",
  WEAPON_2S = "3S",
  WEAPON_590 = "S920",
  WEAPON_MI9 = "MI9",
  WEAPON_X17 = "x17",
  WEAPON_MB47 = "NG47",
  WEAPON_GLOW_BAT = "Glow Bat",
  WEAPON_EASTERKARAMBIT = "Easter Karambit",
  WEAPON_EASTERKATANA = "Easter Katana",
  WEAPON_EASTERSICKLE = "Easter Sickle",
  WEAPON_EASTERSIGN = "Easter Sign",
  WEAPON_STICKEGG = "Egg on a stick",
  WEAPON_PROLASER4 = "Radargun",
  WEAPON_BEANBAGSHOTGUN = "Beanbag Shotgun",
  WEAPON_PEPPERSPRAY = "Pepperspray",
  WEAPON_ANTIDOTE = "Antidote",
  WEAPON_SMOKEGRENADE = "Smoke Grenade",
  WEAPON_WATERGUN = "Water Gun",
  WEAPON_BLOWUP_HAMMER = "Blowup Hammer",
  WEAPON_ICEPOP_1 = "Ice Pop",
  WEAPON_ICEPOP_2 = "Ice Pop",
  WEAPON_ICEPOP_3 = "Ice Pop",
  WEAPON_POOLNOODLE = "Pool Noodle",
  WEAPON_SANDAL = "Sandal",
  WEAPON_HOBO_TOILET = "Toilet Seat",
  WEAPON_HOBO_STICK = "Hobo Stick",
  WEAPON_HOBO_SPONGE = "Wet Sponge",
  WEAPON_HOBO_MOP = "Mop",
  WEAPON_HOBO_SHARD = "Broken Glass",
  WEAPON_HOBO_REBAR = "Rebar",
  WEAPON_HOBO_PLANK = "Wooden Plank",
  WEAPON_HOBO_OLDMACHETE = "Old Machete",
  WEAPON_HOBO_DUSTERS = "Bolt Knuckles",
  WEAPON_HOBO_BRICK = "Brick",
  WEAPON_HOBO_RATSTICK = "Rat Stick",
  WEAPON_HOBO_PIPE = "Pipe",
  WEAPON_HOBO_DIRTYNEEDLE = "Dirty Needle",
  WEAPON_TARANTULA = "Paintball Gun",
  WEAPON_FMICRODRAGON = "MICRO DRAGON",
  WEAPON_PSTRIKEH = "STRIKER-H",
  WEAPON_PSPIKE = "SPIKE",
  WEAPON_PH4 = "H4 SANDSM",
  WEAPON_PT39 = "T39",
  WEAPON_P1911KT = "1911 KT",
  WEAPON_PT19 = "TITAN 19",
  WEAPON_PPH120 = "PHANTOM 120",
  WEAPON_PCM4A1 = "COBRA M41",
  WEAPON_PMK40H1 = "MK40 H1",
  WEAPON_PXS9 = "XTREME S9",
  WEAPON_PT17 = "TITAN 17",
  WEAPON_PMK14 = "MK14",
  WEAPON_PHW45 = "HAWK 45",
  WEAPON_PPH350 = "350 PSL",
  WEAPON_PDBATON = "PD BATON",
  WEAPON_BTASER = "PD Black Taser",
  WEAPON_YTASER = "PD Yellow Taser",
  WEAPON_PDT19 = "PD TITAN 19",
  WEAPON_PDPT870 = "PD PATROL 870",
  WEAPON_PDPT700 = "PD PATROL M700",
  WEAPON_MK417 = "PD MK417",
  WEAPON_PDDT607 = "PD DUTY M607",
  WEAPON_PDDT7 = "PD DUTY C7",
  WEAPON_PDT22 = "PD PINK TITAN 22",
  WEAPON_PDBR5 = "PD BREACH M5",
  WEAPON_PDFC66 = "PD FORCE P66",
  WEAPON_PDMK45 = "PD MK45",
  WEAPON_PDMK33 = "PD MK433",
  WEAPON_PDMKUSP = "PD MK USP",
  WEAPON_APPLE_CANDYCANE = "Candy Cane"
}

Config.TrainMetroStations = {
  [1] = { name = "LSIA Terminal 4", coords = vec(-1083.3578, -2716.4917, -7.4101), nextStation = { Northbound = { h = 316, s = 2 }, Southbound = { h = 137, s = false } } },
  [2] = { name = "LSIA Parking", coords = vec(-873.6451, -2313.1482, -12.6264), nextStation = { Northbound = { h = 333, s = 3 }, Southbound = { h = 151, s = 1 } } },
  [3] = { name = "Puerto Del Sol", coords = vec(-538.3027, -1289.2268, 25.9013), nextStation = { Northbound = { h = 333, s = 4 }, Southbound = { h = 151, s = 2 } } },
  [4] = { name = "Strawberry", coords = vec(260.8647, -1210.0208, 38.0746), nextStation = { Northbound = { h = 267, s = 6 }, Southbound = { h = 86, s = 3 } } },
  -- [5] = { name = "Pillbox North (Under Construction)", coords = vec(140.9126, -599.2263, 17.7564), nextStation = { { h = 64, s = 6 }, { h = 258, s = 4 } } },
  [6] = { name = "Burton", coords = vec(-294.8436, -336.0311, 10.0631), nextStation = { Northbound = { h = 349, s = 7 }, Southbound = { h = 172, s = 4 } } },
  [7] = { name = "Portola Drive", coords = vec(-813.0384, -136.0313, 19.9503), nextStation = { Northbound = { h = 117, s = 8 }, Southbound = { h = 292, s = 6 } } },
  [8] = { name = "Del Perro", coords =  vec(-1350.6287, -467.3718, 15.0454), nextStation = { Northbound = { h = 208, s = 9 }, Southbound = { h = 28, s = 7 } } },
  [9] = { name = "Little Seoul", coords =  vec(-497.0356, -673.1466, 11.8090), nextStation = { Northbound = { h = 276, s = 10 }, Southbound = { h = 83, s = 8 } } },
  [10] = { name = "Pillbox South", coords = vec(-211.6538, -1028.5626, 30.5675), nextStation = { Northbound = { h = 151, s = 11 }, Southbound = { h = 335, s = 9 } } },
  [11] = { name = "Davis", coords =  vec(112.2249, -1723.0388, 30.5415), nextStation = { Northbound = { h = 230, s = false }, Southbound = { h = 45, s = 10 } } },
}

-- Add electric vehicles to disable combustion engine features
-----------------------------------------------------------------------
-- PLEASE NOTE: In b3258 (Bottom Dollar Bounties) and newer, electric
-- vehicles are detected automatically, so this list is not used! 
Config.ElectricVehicles = {
  "Airtug",     "buffalo5",   "caddy",
  "Caddy2",     "caddy3",     "coureur",
  "cyclone",    "cyclone2",   "imorgon",
  "inductor",   "iwagen",     "khamelion",
  "metrotrain", "minitank",   "neon",
  "omnisegt",   "powersurge", "raiden",
  "rcbandito",  "surge",      "tezeract",
  "virtue",     "vivanite",   "voltic",
  "voltic2",
}

---------------------------------------------
-- Register custom street/zone names globally
if Config.CustomNamesShouldUpdateGameTextEntries then
  for hash, val in pairs(Config.CustomStreetNames) do
    AddTextEntryByHash(hash, val)
  end

  for name, val in pairs(Config.CustomZoneNames) do
    AddTextEntryByHash(joaat(name), val)
  end
end