return {
    disable = {
        -- Disables the Idle Cinematic Camera
        idleCamera = true,

        -- Disabled distance sirens, distance car alarms, etc
        ambience = true,

    },

    blacklisted = {
        scenarioTypes = {
            'WORLD_VEHICLE_AMBULANCE',
            'WORLD_VEHICLE_FIRE_TRUCK',
            'WORLD_VEHICLE_POLICE_BIKE',
            'WORLD_VEHICLE_POLICE_CAR',
            'WORLD_VEHICLE_POLICE',
            'WORLD_VEHICLE_POLICE_NEXT_TO_CAR',
            'WORLD_VEHICLE_SECURITY_CAR',
            'WORLD_VEHICLE_HELI_LIFEGUARD',
            'WORLD_VEHICLE_MILITARY_PLANES_BIG',
            'WORLD_VEHICLE_MILITARY_PLANES_SMALL',
        },

        suppressedModels = {
            'SHAMAL',
            'TOREADOR',
            'BUFFALO4',
            'CHAMPION',
            'LUXOR',
            'LUXOR2',
            'JET',
            'LAZER',
            'BUZZARD',
            'BUZZARD2',
            'ANNIHILATOR',
            'SAVAGE',
            'TITAN',
            'RHINO',
            -- 'FIRETRUK',
            'MAVERICK',
            'BLIMP',
            'AIRTUG',
            'CAMPER',
            'HYDRA',
            'OPPRESSOR',
            'TECHNICAL3',
            'INSURGENT3',
            'APC',
            'TAMPA3',
            'TRAILERSMALL2',
            'HALFTRACK',
            'HUNTER',
            'VIGILANTE',
            'AKULA',
            'BARRAGE',
            'KHANJALI',
            'CARACARA',
            'BLIMP3',
            'MENACER',
            'OPPRESSOR2',
            'SCRAMJET',
            'STRIKEFORCE',
            'CERBERUS',
            'CERBERUS2',
            'CERBERUS3',
            'SCARAB',
            'SCARAB2',
            'SCARAB3',
            'RROCKET',
            'RUINER2',
            'DELUXO',
            'POLMAV',
            'BOXVILLE5',
            'HAVOK',
            'DUNE3',
            'BESRA',
        },

        scenarioGroups = {
            'LSA_Planes',
            'SANDY_PLANES',
            'GRAPESEED_PLANES',
            `ng_planes`,
        },
    },
}
