Config = Config or {}

-- For more info check: https://mt-scripts-documentations.gitbook.io/mt-script-documentation/

Config.ingredients = { -- All items, you can create different categories of items to use on different restaurants
    globalIngredients = { -- List of the items, to create custom buffs just add them to the customBuffs field and change the function on its use on the functions.lua following the same format (more info at docs website)
        -- { needCut = true, neededItems = { onion = 1 }, item = 'cutted_onion', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { carrot = 1 }, item = 'cutted_carrot', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { lettuce = 1 }, item = 'cutted_lettuce', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { cucumber = 1 }, item = 'cutted_cucumber', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { potato = 1 }, item = 'cutted_potato', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { tomato = 1 }, item = 'cutted_tomato', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { wheat = 1 }, item = 'cutted_wheat', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { strawberry = 1 }, item = 'cutted_strawberry', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { watermelon = 1 }, item = 'cutted_watermelon', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { soya = 1 }, item = 'cutted_soya', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { pineapple = 1 }, item = 'cutted_pineapple', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { apple = 1 }, item = 'cutted_apple', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { pear = 1 }, item = 'cutted_pear', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { lemon = 1 }, item = 'cutted_lemon', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { banana = 1 }, item = 'cutted_banana', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { orange = 1 }, item = 'cutted_orange', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { peach = 1 }, item = 'cutted_peach', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { mango = 1 }, item = 'cutted_mango', count = 5, type = { 'food', 'drink' }, calories = 100, customBuffs = {} },
        -- { needCut = true, neededItems = { meat = 1 }, item = 'cutted_meat', count = 5, type = { 'food' }, calories = 500, customBuffs = {} },
        -- { needCut = true, neededItems = { fish = 1 }, item = 'cutted_fish', count = 5, type = { 'food' }, calories = 500 },
           -- Foods
        { needCut = false, item = 'meat', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'fish', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'lobster', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'bread', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'lettuce', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'potato', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'onion', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'tealeaf', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'mixedgreens', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'mixedfruits', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'lemon', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'cucumber', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'pomegranate', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'cheese', type = {'food'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'milk', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'water', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'sugar', type = {'food', 'drink', 'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'flour', type = {'food', 'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'cocoa', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'proteinpowder', type = {'food', 'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'chips', type = {'food'}, calories = 100, customBuffs = {} },


        -- Alcoholic drinks
        { needCut = false, item = 'gin', type = {'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'rum', type = {'drink'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'vodka', type = {'drink'}, calories = 100, customBuffs = {} },

        -- Weed Shops
        { needCut = false, item = 'drug_shears', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'drug_grinder', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'rollingpapers', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'gummymould', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'gelatine', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'rawhoney', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'emptybaggy', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'weddingcake_crop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'sourdiesel_crop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'granddaddypurple_crop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'afghankush_crop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'jackherrer_crop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'weddingcake_bud', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'sourdiesel_bud', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'granddaddypurple_bud', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'afghankush_bud', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'jackherrer_bud', type = {'weed'}, calories = 100, customBuffs = {} },

        -- Smoke Shops
        { needCut = false, item = 'nicotine', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'glycerine', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'vape_battery', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'vape_coil', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'vape_casing', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'cakepopstick', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'skintbackdrop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'candybombdrop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'sweettitsdrop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'blueberrydreamdrop', type = {'weed'}, calories = 100, customBuffs = {} },
        { needCut = false, item = 'tripsittersdrop', type = {'weed'}, calories = 100, customBuffs = {} },

        --Mechanic
        { needCut = false, item = 'turbopart', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'performance_part', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'mechrubber', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'brakespart', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'mechplastic', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'mechaluminum', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'mechsteel', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'vehicle_wheels', type = { 'item' }, calories = 100 },
        { needCut = false, item = 'mechiron', type = { 'item' }, calories = 100 },
    },
}