if not Config.DatabaseChecker.Enabled then
    return
end

local defaultTables = {
	lbracing_converted_scripts = {
		{
			column = "script_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			length = 100,
		},
	},
	lbracing_liked_tracks = {
		{
			column = "track_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "player_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			length = 100,
		},
	},
	lbracing_repeating_races = {
		{
			column = "repeat_minute_interval",
			type = "MEDIUMINT",
			allowNull = false,
			isKey = false,
			length = 8,
			unsigned = true,
		},
		{
			column = "original_race_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "tracks",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 5000,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "latest_race_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "creator",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "next_race_date",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
		},
		{
			column = "start_time",
			type = "SMALLINT",
			allowNull = false,
			isKey = false,
			default = "15",
			length = 5,
			unsigned = true,
		},
	},
	lbracing_races = {
		{
			column = "race_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "min_rating",
			type = "INT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 10,
			unsigned = true,
		},
		{
			column = "vehicle_model",
			type = "INT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 11,
		},
		{
			column = "disable_npc_traffic",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 1,
		},
		{
			column = "first_person_only",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 1,
		},
		{
			column = "payment_method",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			default = "'bank'",
			length = 50,
		},
		{
			column = "finished",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 1,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "max_participants",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			length = 3,
			unsigned = true,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "start_date",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
		},
		{
			column = "canceled",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 1,
		},
		{
			column = "personal_vehicle",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
			length = 1,
		},
		{
			column = "max_rating",
			type = "INT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 10,
			unsigned = true,
		},
		{
			column = "vehicle_tiers",
			type = "TEXT",
			allowNull = true,
			isKey = false,
			default = "NULL",
		},
		{
			column = "min_participants",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			length = 3,
			unsigned = true,
		},
		{
			column = "collision",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
			length = 1,
		},
		{
			column = "ranked",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
			length = 1,
		},
		{
			column = "participants",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 3,
			unsigned = true,
		},
		{
			column = "assign_vehicle",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 1,
		},
		{
			column = "track_id",
			type = "INT",
			allowNull = false,
			isKey = false,
			length = 10,
			unsigned = true,
		},
		{
			column = "invite_only",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 1,
		},
		{
			column = "entry_fee",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "require_sign_up",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
			length = 1,
		},
		{
			column = "commission",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 3,
			unsigned = true,
		},
		{
			column = "prize_distribution",
			type = "TEXT",
			allowNull = false,
			isKey = false,
		},
		{
			column = "vehicle_class",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 100,
		},
		{
			column = "starting_prize",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "laps",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
			length = 3,
			unsigned = true,
		},
		{
			column = "host",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
	},
	lbracing_tracks = {
		{
			column = "track_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "checkpoints",
			type = "LONGTEXT",
			allowNull = false,
			isKey = false,
		},
		{
			column = "created_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "start_position",
			type = "LONGTEXT",
			allowNull = false,
			isKey = false,
		},
		{
			column = "track_length",
			type = "INT",
			allowNull = false,
			isKey = false,
			length = 10,
			unsigned = true,
		},
		{
			column = "track_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			default = "'circuit'",
			length = 15,
		},
		{
			column = "likes",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "uses",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "barriers",
			type = "LONGTEXT",
			allowNull = true,
			isKey = false,
			default = "NULL",
		},
		{
			column = "creator",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "vehicle_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
	},
	lbracing_race_invites = {
		{
			column = "inviter_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "race_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "invitee_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			length = 100,
		},
		{
			column = "invite_date",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
	},
	lbracing_accounts = {
		{
			column = "money_won",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "username",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "rating",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "avatar",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 500,
		},
		{
			column = "public_profile",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
			length = 1,
		},
		{
			column = "races_won",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			length = 100,
		},
		{
			column = "updated_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "created_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "last_race",
			type = "INT",
			allowNull = true,
			isKey = true,
			default = "NULL",
			length = 10,
			unsigned = true,
		},
		{
			column = "races_played",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
			length = 10,
			unsigned = true,
		},
	},
	lbracing_race_participants = {
		{
			column = "vehicle_tier",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 100,
		},
		{
			column = "rating_change",
			type = "TINYINT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 4,
		},
		{
			column = "vehicle_model",
			type = "INT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 11,
		},
		{
			column = "participant_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			length = 100,
		},
		{
			column = "race_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "placing",
			type = "TINYINT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 3,
			unsigned = true,
		},
		{
			column = "finish_time",
			type = "INT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 10,
			unsigned = true,
		},
	},
	lbracing_track_times = {
		{
			column = "player_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			length = 100,
		},
		{
			column = "vehicle_model",
			type = "INT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			length = 11,
		},
		{
			column = "lap_number",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			length = 3,
			unsigned = true,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "vehicle_tier",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			length = 100,
		},
		{
			column = "race_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "track_id",
			type = "INT",
			allowNull = false,
			isKey = true,
			length = 10,
			unsigned = true,
		},
		{
			column = "lap_time",
			type = "INT",
			allowNull = false,
			isKey = false,
			length = 10,
			unsigned = true,
		},
	},
}

function GetDefaultDatabaseTables()
    return defaultTables
end
