INSERT INTO `drx_mdt_charges` (`id`, `label`, `description`, `fine`, `jail`, `points`, `category`) VALUES
	(1, 'Public Intoxication', 'Being visibly intoxicated in public', 100, 10, 0, 1),
	(2, 'Underage Drinking', 'Consuming or possessing alcohol under the age of 21', 200, 0, 0, 2),
	(3, 'Driving Without License', 'Operating a motor vehicle without a valid license', 500, 0, 2, 1),
	(4, 'Reckless Driving', 'Driving with willful or wanton disregard for the safety of others', 1000, 30, 5, 1),
	(5, 'Speeding', 'Driving over the posted speed limit', 150, 0, 1, 1),
	(6, 'Driving Under the Influence (DUI)', 'Driving while under the influence of drugs or alcohol', 5000, 90, 10, 1),
	(7, 'Assault and Battery', 'Intentionally or recklessly causing bodily harm to another person', 2000, 60, 5, 3),
	(8, 'Domestic Violence', 'Committing violence against a spouse, partner, or family member', 5000, 90, 10, 3),
	(9, 'Embezzlement', 'Stealing money or property that has been entrusted to you by another person or organization', 10000, 180, 15, 6),
	(10, 'Forgery', 'Falsely creating or altering a legal document with the intent to defraud', 5000, 90, 10, 6),
	(11, 'Narcotics Trafficking', 'Selling, distributing, or transporting illegal drugs', 25000, 360, 25, 5),
	(12, 'Money Laundering', 'Concealing the source of money obtained through illegal means', 20000, 240, 20, 6),
	(13, 'Arson', 'Intentionally setting fire to property', 10000, 180, 15, 4),
	(14, 'Grand Theft Auto', 'Stealing a vehicle worth over $1,000', 5000, 90, 10, 1),
	(15, 'Kidnapping', 'Taking a person against their will and holding them captive', 20000, 360, 25, 3),
	(16, 'Arson', 'Willfully and maliciously sets fire to or burns or causes to be burned, or aids, counsels, or procures the burning of, any structure, forest land, or property.', 5000, 60, 20, 2),
	(17, 'Prostitution', 'Engages in or agrees to engage in sexual conduct for a fee.', 2000, 30, 10, 9),
	(18, 'Kidnapping', 'Takes, holds, or detains another person by force, threat, or deception, with intent to deprive that person of liberty.', 10000, 120, 50, 3),
	(19, 'Forgery', 'Creates or alters a document with the intent to defraud, deceive, or injure another person or entity.', 1500, 30, 10, 8),
	(20, 'Drug trafficking', 'Manufactures, delivers, or possesses with the intent to manufacture or deliver a controlled substance.', 10000, 120, 50, 5),
	(21, 'Trespassing', 'Enters or remains on property of another person without permission or legal authority.', 500, 0, 0, 1),
	(22, 'Aggravated assault', 'Attempts to cause serious bodily injury to another person with a deadly weapon or dangerous instrument.', 5000, 60, 20, 3),
	(23, 'Identity theft', 'Uses another person\'s personal identifying information to commit fraud or other crimes.', 2500, 30, 10, 8),
	(24, 'Embezzlement', 'Steals or misappropriates money or property that has been entrusted to one\'s care or control.', 5000, 60, 20, 6),
	(25, 'Domestic violence', 'Commits a crime of violence against a current or former spouse, romantic partner, family member, or household member.', 2500, 30, 10, 3),
	(26, 'Obstruction of justice', 'Obstructs, impairs, or perverts the administration of law or other governmental function.', 1000, 30, 10, 8),
	(27, 'Child pornography', 'Produces, distributes, or possesses with intent to distribute any visual depiction of a minor engaging in sexually explicit conduct.', 10000, 120, 50, 9),
	(28, 'Animal cruelty', 'Intentionally, knowingly or recklessly causes bodily injury to an animal or maliciously kills an animal.', 2000, 30, 10, 8),
	(29, 'Burglary', 'Entering a building or structure with the intent to commit a crime', 5000, 90, 15, 2),
	(30, 'Credit Card Fraud', 'Using a stolen or fake credit card to make purchases', 2500, 30, 10, 8),
	(31, 'Identity Theft', 'Using another person\'s identity to obtain goods or services', 5000, 60, 20, 6),
	(32, 'Insurance Fraud', 'Making false claims to an insurance company for financial gain', 10000, 180, 15, 6),
	(33, 'Hate Crime', 'Committing a crime against a person or group based on their race, ethnicity, religion, or other characteristic', 5000, 60, 20, 3),
	(34, 'Sexual Assault', 'Forcing someone to engage in sexual activity without their consent', 10000, 240, 25, 9),
	(35, 'Stalking', 'Repeatedly harassing or following another person', 2000, 30, 10, 8),
	(36, 'Wire Fraud', 'Using electronic communication to commit fraud or theft', 10000, 180, 15, 6),
	(37, 'Money Counterfeiting', 'Creating or using fake money with the intent to defraud', 5000, 90, 15, 6),
	(38, 'Cybercrime', 'Using a computer or the internet to commit a crime, such as hacking or identity theft', 10000, 180, 20, 8),
	(39, 'Fraudulent Investment Schemes', 'Using false promises to swindle people out of their money for a fake investment', 25000, 360, 25, 6),
	(40, 'Environmental Crimes', 'Polluting or damaging the environment in violation of laws and regulations', 5000, 90, 10, 6),
	(41, 'Child Abuse', 'Physically or emotionally harming a child', 5000, 90, 15, 9),
	(42, 'Sexual Exploitation of a Minor', 'Using a minor for sexual purposes, such as prostitution or pornography', 25000, 360, 30, 9),
	(43, 'Human Trafficking', 'Forcing or coercing people into labor or sexual servitude', 50000, 720, 50, 9),
	(44, 'Terrorism', 'Intending to intimidate or coerce a civilian population or government through violent acts', 50000, 720, 50, 10),
	(45, 'Espionage', 'Gathering or transmitting confidential information to a foreign government', 50000, 720, 50, 10),
	(46, 'Insider Trading', 'Using non-public information to profit in the stock market', 100000, 180, 20, 6),
	(47, 'Money Laundering', 'Concealing the source of illegally obtained money', 50000, 720, 30, 6),
	(48, 'Racketeering', 'Organized crime involving extortion, money laundering, and other illegal activities', 100000, 360, 25, 6),
	(49, 'Public Corruption', 'Abusing public office for personal gain or to benefit others', 50000, 720, 30, 6),
	(50, 'Election Fraud', 'Manipulating election results through illegal means', 10000, 180, 10, 6),
	(51, 'Bribery', 'Offering or accepting money or other benefits in exchange for favorable treatment', 25000, 360, 20, 6),
	(52, 'Perjury', 'Lying under oath in a court or legal proceeding', 5000, 90, 10, 8),
	(53, 'Obstruction of Congress', 'Impeding the legislative process through illegal means', 10000, 180, 20, 6),
	(54, 'Sedition', 'Inciting rebellion or overthrow of the government through illegal means', 50000, 720, 50, 10),
	(55, 'Contempt of Court', 'Disobeying or disrespecting a court order or proceeding', 5000, 90, 10, 8),
	(56, 'Child Neglect', 'Failing to provide basic care and necessities for a child', 5000, 90, 10, 9),
	(57, 'Animal Fighting', 'Organizing or participating in animal fights for entertainment or profit', 5000, 90, 10, 8),
	(58, 'Armed Robbery', 'Robbing a person or place with a weapon', 10000, 240, 25, 4),
	(59, 'Extortion', 'Forcing a person or entity to give up property or money through threats or coercion', 10000, 180, 20, 6),
	(60, 'Money Laundering', 'Concealing the source of money obtained through illegal activities such as drug trafficking or embezzlement', 50000, 720, 50, 6),
	(61, 'Human Trafficking', 'Exploiting or coercing individuals for labor or sexual purposes', 50000, 360, 25, 9),
	(62, 'Criminal Mischief', 'Intentionally damaging or destroying another person\'s property', 5000, 90, 10, 2),
	(63, 'Stalking', 'Engaging in a course of conduct that causes a person to fear for their safety or the safety of others', 2500, 60, 10, 3),
	(64, 'Criminal Trespass', 'Entering or remaining in a building or property without permission', 1000, 30, 5, 1),
	(65, 'Hate Crime', 'Committing a crime with the intent to harm or intimidate a person or group based on their race, religion, gender, or sexual orientation', 5000, 120, 25, 3),
	(66, 'Involuntary Manslaughter', 'Causing the death of another person through recklessness or negligence', 10000, 180, 20, 10),
	(67, 'Vehicular Manslaughter', 'Causing the death of another person while operating a vehicle recklessly or under the influence of drugs or alcohol', 20000, 360, 50, 1),
	(68, 'Child Endangerment', 'Putting a child at risk of harm through neglect or abuse', 5000, 90, 10, 9),
	(69, 'Aggravated Sexual Assault', 'Sexual assault involving violence, weapons, or serious bodily injury', 50000, 720, 50, 9),
	(70, 'Burglary', 'Entering a building or property with the intent to commit a crime', 5000, 90, 10, 2),
	(71, 'Misdemeanor Assault', 'Causing bodily injury to another person through intentional or reckless behavior', 1000, 30, 5, 3),
	(72, 'Identity Theft', 'Using someone else\'s personal information to commit fraud or other crimes', 5000, 90, 10, 8),
	(73, 'Misdemeanor Drug Possession', 'Possessing a small amount of drugs for personal use', 1000, 30, 2, 5),
	(74, 'Felony Drug Possession', 'Possessing a large amount of drugs with the intent to sell or distribute', 10000, 180, 20, 5),
	(75, 'Fraud', 'Deceiving or misleading others for financial gain', 5000, 90, 10, 6),
	(76, 'Perjury', 'Lying under oath in a court of law', 5000, 90, 10, 8),
	(77, 'Tax Evasion', 'Failing to pay taxes owed to the government', 10000, 180, 15, 6),
	(78, 'Forgery', 'Falsifying a legal document or signature with the intent to defraud', 5000, 90, 10, 6),
	(79, 'Robbery', 'Taking property from a person or entity through force or threat of force', 10000, 360, 25, 4),
	(80, 'False Imprisonment', 'Unlawfully restraining or confining another person', 5000, 90, 10, 3),
	(81, 'Armed Robbery', 'Robbery committed with a weapon or dangerous instrument', 25000, 720, 50, 4),
	(82, 'Hijacking', 'Seizing control of a vehicle or aircraft by force or threat of force', 50000, 720, 50, 4),
	(83, 'Money Laundering', 'Concealing or disguising the proceeds of criminal activity to make them appear legitimate', 25000, 360, 25, 6),
	(84, 'Insurance Fraud', 'Making false insurance claims or providing false information to obtain insurance benefits', 10000, 180, 15, 6),
	(85, 'Credit Card Fraud', 'Using someone else\'s credit card or credit information to make unauthorized purchases', 5000, 90, 10, 6),
	(86, 'Embezzlement', 'Stealing money or property that has been entrusted to you by an employer or organization', 10000, 180, 20, 6),
	(87, 'Receiving Stolen Property', 'Possessing or buying property that has been stolen', 5000, 90, 10, 6),
	(88, 'Racketeering', 'Engaging in organized crime for financial gain', 25000, 720, 50, 6),
	(89, 'Money Laundering', 'Concealing the source of illegally obtained money or assets', 50000, 720, 50, 6),
	(90, 'Grand Larceny', 'Theft of property valued at over $1,000', 10000, 180, 15, 4),
	(91, 'Bribery', 'Offering or receiving money or gifts to influence the actions of a public official or businessperson', 10000, 180, 15, 6),
	(92, 'Environmental Crimes', 'Violating laws related to pollution or hazardous waste disposal', 5000, 90, 10, 6),
	(93, 'Child Abuse', 'Intentionally causing harm to a child', 10000, 360, 25, 3),
	(94, 'Child Neglect', 'Failing to provide necessary care or protection to a child', 5000, 90, 10, 3),
	(95, 'Aggravated Battery', 'Intentionally causing serious bodily injury to another person', 10000, 360, 25, 3),
	(96, 'Stalking', 'Repeating unwanted contact with another person that causes fear or emotional distress', 5000, 90, 10, 3),
	(97, 'Extortion', 'Using threats or force to obtain money or property from another person', 10000, 360, 25, 4),
	(98, 'Hate Crimes', 'Committing a crime motivated by prejudice or hate against a particular group', 10000, 360, 25, 3),
	(99, 'Sexual Assault', 'Forcing another person to engage in sexual activity against their will', 10000, 360, 25, 9),
	(100, 'Murder', 'Intentionally causing the death of another person', 50000, 999, 50, 10),
	(101, 'Burglary', 'Entering a building or property without permission with the intent to commit a crime', 5000, 90, 10, 4),
	(102, 'Criminal Mischief', 'Causing damage to property without the owner\'s consent', 1000, 30, 5, 2),
	(103, 'Harassment', 'Intentionally causing emotional distress or fear through repeated unwanted contact', 1000, 30, 5, 3),
	(104, 'Disorderly Conduct', 'Behaving in a disruptive or unruly manner in public', 500, 0, 0, 8),
	(105, 'Public Indecency', 'Engaging in sexual activity or exposing oneself in public', 1000, 30, 5, 9),
	(106, 'Terrorism', 'Using violence or intimidation to achieve political or social goals', 50000, 999, 50, 10),
	(107, 'Espionage', 'Gathering or transmitting sensitive information without authorization for the purpose of harming national security', 50000, 999, 50, 10),
	(108, 'Insider Trading', 'Using confidential information to buy or sell stocks for personal gain', 10000, 180, 15, 6),
	(109, 'Perjury', 'Lying under oath in a court of law', 5000, 60, 20, 8),
	(110, 'Obstruction of Congress', 'Interfering with the work of the US Congress or any other legislative body', 5000, 60, 20, 10),
	(111, 'Sabotage', 'Intentionally damaging or destroying equipment or property to hinder the operations of a business or organization', 10000, 360, 25, 10),
	(112, 'Blackmail', 'Threatening to reveal embarrassing or damaging information in exchange for money or other benefits', 10000, 180, 15, 6),
	(113, 'Animal Fighting', 'Organizing or participating in fights between animals for entertainment or profit', 5000, 90, 10, 8),
	(114, 'Cybercrime', 'Using computers or the internet to commit fraud, identity theft, or other crimes', 10000, 180, 15, 6),
	(115, 'Counterfeiting', 'Creating or selling fake money or goods with the intent to deceive', 10000, 180, 15, 6),
	(116, 'Environmental Crimes', 'Violating laws related to pollution, waste disposal, or natural resource preservation', 10000, 180, 15, 4),
	(117, 'Human Trafficking', 'Using force or coercion to exploit or transport individuals for forced labor or sexual exploitation', 50000, 360, 25, 9),
	(118, 'Money Counterfeiting', 'Making fake money or selling it with the intent to deceive', 10000, 180, 15, 6),
	(119, 'Stalking', 'Following, harassing, or threatening another person repeatedly and causing fear for their safety', 2000, 30, 10, 3),
	(120, 'Child Abuse', 'Intentionally harming or endangering a child physically, mentally, or emotionally', 5000, 90, 10, 9),
	(121, 'Elder Abuse', 'Intentionally harming or exploiting an elderly person physically, mentally, or emotionally', 5000, 90, 10, 9),
	(122, 'Tax Evasion', 'Intentionally failing to report or pay taxes owed to the government', 10000, 180, 15, 6),
	(123, 'Healthcare Fraud', 'Intentionally submitting false or misleading information to healthcare providers or insurance companies for personal gain', 10000, 180, 15, 6),
	(124, 'Insurrection', 'Participating in or inciting a violent uprising against the government or other authority', 50000, 999, 50, 10),
	(125, 'Racketeering', 'Participating in organized crime, such as extortion or illegal gambling, for personal gain', 10000, 360, 25, 6),
	(126, 'Terroristic Threats', 'Threatening to commit violence or harm to others for political or social purposes', 5000, 90, 10, 10),
	(127, 'Vandalism', 'Intentionally damaging or defacing property belonging to another person or organization', 1000, 30, 5, 2),
	(128, 'Weapons Offenses', 'Violating laws related to the possession or use of firearms, knives, or other weapons', 5000, 90, 10, 7),
	(129, 'Robbery with Firearm', 'Taking property from someone by force or fear, while armed with a gun', 10000, 180, 15, 4),
	(130, 'Identity Theft', 'Stealing someone\'s personal information and using it for financial gain', 5000, 90, 10, 8),
	(131, 'Child Abduction', 'Taking a child away from their legal guardian without permission or legal authority', 10000, 180, 15, 3),
	(132, 'Animal Trafficking', 'Selling, transporting, or possessing wild or endangered animals', 10000, 180, 15, 8),
	(133, 'Bribery', 'Offering or accepting money or gifts in exchange for special treatment or favors', 10000, 180, 15, 6),
	(134, 'Cybercrime', 'Committing a crime using a computer or the internet, such as hacking or identity theft', 10000, 180, 15, 8),
	(135, 'False Imprisonment', 'Restraining someone against their will and without legal authority', 5000, 90, 10, 3),
	(136, 'Insurance Fraud', 'Submitting false or misleading insurance claims for personal gain', 10000, 180, 15, 6),
	(137, 'Money Laundering', 'Converting money obtained from illegal activities into legitimate funds', 10000, 180, 15, 6),
	(138, 'Perjury', 'Intentionally lying under oath or in a legal document', 5000, 90, 10, 6),
	(139, 'Sexual Assault', 'Engaging in non-consensual sexual contact with another person', 5000, 90, 10, 9),
	(140, 'Terrorism', 'Using violence or intimidation to achieve political or social goals', 50000, 999, 50, 10),
	(141, 'Aggravated Robbery', 'Taking property from someone by force or fear, and causing serious bodily injury or using a deadly weapon', 20000, 360, 25, 4),
	(142, 'Armed Robbery', 'Taking property from someone by force or fear, while armed with a weapon', 15000, 240, 20, 4),
	(143, 'Child Pornography', 'Creating, distributing, or possessing images or videos depicting minors engaged in sexual conduct', 25000, 360, 25, 9),
	(144, 'Criminal Conspiracy', 'Planning or agreeing with others to commit a crime', 10000, 180, 15, 6),
	(145, 'Espionage', 'Gathering or providing sensitive or classified information to a foreign government or entity', 50000, 999, 50, 6),
	(146, 'Extortion', 'Threatening to harm someone or their property in exchange for money or something of value', 10000, 180, 15, 6),
	(147, 'Human Trafficking', 'Using force, fraud, or coercion to exploit someone for labor or commercial sex acts', 25000, 360, 25, 9),
	(148, 'Money Counterfeiting', 'Creating or passing counterfeit money', 10000, 180, 15, 6),
	(149, 'Racketeering', 'Operating an illegal business, often involving organized crime', 50000, 999, 50, 6),
	(150, 'Treason', 'Betraying one\'s country by providing aid and comfort to its enemies', 50000, 999, 50, 6),
	(151, 'Vandalism', 'Intentionally damaging or destroying property that belongs to someone else', 1000, 30, 5, 2),
	(152, 'Wire Fraud', 'Using electronic communication to commit fraud or obtain money or property through false pretenses', 10000, 180, 15, 8),
	(153, 'Felony DUI', 'Driving under the influence and causing serious bodily injury or death', 10000, 999, 50, 1),
	(154, 'Manslaughter', 'Killing someone without malice or premeditation', 20000, 360, 25, 10),
	(155, 'Murder', 'Killing someone with malice or premeditation', 50000, 999, 50, 10),
	(156, 'Robbery with Explosives', 'Taking property from someone by force or fear, while armed with an explosive device', 50000, 999, 50, 4),
	(157, 'Terroristic Threats', 'Making threats to commit acts of violence or terrorism', 5000, 90, 10, 10),
	(158, 'Aggravated Stalking', 'Engaging in a course of conduct that causes someone to fear for their safety, while also violating a restraining order or injunction', 5000, 60, 20, 8),
	(159, 'Concealed Weapon Violation', 'Carrying a concealed weapon without a permit or in a prohibited location', 1000, 30, 5, 7),
	(160, 'Contempt of Court', 'Willfully disobeying or disrespecting a court order or the authority of the court', 500, 0, 0, 8),
	(161, 'Credit Card Fraud', 'Using someone else\'s credit card or credit card information without their permission to make unauthorized purchases', 5000, 90, 10, 8),
	(162, 'Criminal Trespass', 'Entering or remaining on property without permission, knowing that permission has been withdrawn or that one is not authorized to enter or remain on the property', 500, 0, 0, 2),
	(163, 'Cruelty to Children', 'Committing acts that cause physical or emotional harm to a child', 2000, 60, 5, 9),
	(164, 'Disorderly Conduct', 'Behaving in a way that disturbs the peace, such as fighting, making loud noise, or using obscene language', 500, 0, 0, 8),
	(165, 'Drug Possession', 'Possessing illegal drugs for personal use or distribution', 1000, 30, 5, 5),
	(166, 'DUI with Bodily Injury', 'Driving under the influence and causing injury to another person', 5000, 90, 10, 1),
	(167, 'Environmental Crimes', 'Violating environmental laws, such as polluting or dumping hazardous waste', 10000, 180, 15, 6),
	(168, 'Forgery and Counterfeiting', 'Creating or altering documents with the intent to deceive or defraud', 5000, 60, 20, 6),
	(169, 'Fraud', 'Intentionally deceiving someone in order to gain something of value', 5000, 60, 20, 6),
	(170, 'Harassment', 'Repetitive and unwanted behavior that causes emotional distress or a threat to one\'s safety', 1000, 30, 5, 8),
	(171, 'Identity Theft', 'Using someone else\'s personal information to commit fraud or other crimes', 5000, 60, 20, 6),
	(172, 'Insurance Fraud', 'Providing false information to an insurance company in order to obtain money or other benefits', 10000, 180, 15, 6),
	(173, 'Internet Crime', 'Committing a crime using the internet, such as hacking, cyberstalking, or identity theft', 5000, 60, 20, 8),
	(174, 'Larceny', 'Taking someone else\'s property without their consent and with the intent to permanently deprive them of it', 1000, 30, 5, 2),
	(175, 'Mail Fraud', 'Using the postal service to commit fraud, such as sending false information in order to obtain money or other benefits', 10000, 180, 15, 6),
	(176, 'Manslaughter', 'Killing someone without the intent to do so, such as in a car accident or as a result of criminal negligence', 10000, 180, 15, 10),
	(177, 'Money Laundering', 'Concealing the source of illegally obtained money or other assets', 20000, 240, 20, 6),
	(178, 'Perjury', 'Lying under oath in a court of law or in a legal document', 5000, 60, 20, 8),
	(179, 'Public Nuisance', 'Behaving in a way that interferes with the public\'s right to use and enjoy public spaces', 500, 0, 0, 8),
	(180, 'Racketeering', 'Engaging in illegal business activities, such as extortion or fraud, as part of an organized crime group', 25000, 360, 25, 6),
	(181, 'Robbery with Deadly Weapon', 'Stealing someone else\'s property by using or threatening to use a deadly weapon', 20000, 240, 20, 4),
	(182, 'Securities Fraud', 'Providing false or misleading information in order to manipulate stock prices or obtain money from investors', 25000, 360, 25, 6),
	(183, 'Sexual Assault', 'Engaging in sexual activity with someone without their consent', 5000, 90, 10, 9),
	(184, 'Stalking', 'Repeatedly harassing or following someone, causing them to fear for their safety', 1000, 30, 5, 8),
	(185, 'Tax Evasion', 'Failing to pay or underreporting taxes owed to the government', 5000, 60, 20, 6),
	(186, 'Theft by Deception', 'Obtaining someone else\'s property through the use of false information or other deceptive means', 5000, 60, 20, 2),
	(187, 'Trademark Infringement', 'Using someone else\'s trademark without permission or authorization', 1000, 0, 0, 6),
	(188, 'Trespassing with Intent to Commit a Crime', 'Entering someone else\'s property with the intention of committing a crime', 5000, 60, 20, 2),
	(189, 'Unlawful Imprisonment', 'Restraining someone against their will, without legal justification', 10000, 180, 15, 3),
	(190, 'Vandalism', 'Damaging or defacing someone else\'s property', 1000, 0, 0, 2),
	(191, 'Wire Fraud', 'Using electronic communication to commit fraud, such as sending false information in order to obtain money or other benefits', 10000, 180, 15, 6),
	(192, 'Witness Tampering', 'Intimidating or otherwise influencing a witness in a legal case', 5000, 60, 20, 8),
	(193, 'Welfare Fraud', 'Providing false information in order to obtain benefits from a government welfare program', 5000, 60, 20, 6),
	(194, 'Zoning Violation', 'Violating local zoning laws, such as building without a permit or using a property for an unauthorized purpose', 1000, 0, 0, 8),
	(195, 'Animal Fighting', 'Organizing or participating in a fight between animals, such as cockfighting or dogfighting', 5000, 90, 10, 8),
	(196, 'Child Abuse', 'Intentionally causing harm to a child, whether physical, emotional, or sexual', 10000, 180, 15, 9),
	(197, 'Criminal Contempt of Court', 'Violating a court order or otherwise obstructing the administration of justice', 5000, 60, 20, 8),
	(198, 'Conspiracy', 'Planning to commit a crime with one or more people, even if the crime is never carried out', 5000, 60, 20, 8),
	(199, 'Espionage', 'Gathering or transmitting confidential information for a foreign government or other organization, with the intention of harming national security', 25000, 360, 25, 10),
	(200, 'Insurance Fraud', 'Making false claims or providing false information in order to obtain benefits from an insurance company', 10000, 180, 15, 6);
