CREATE TABLE IF NOT EXISTS `playerskins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(255) NOT NULL,
  `model` varchar(255) NOT NULL,
  `skin` text NOT NULL,
  `active` tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`),
  KEY `active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `crm_outfits` (
  `crm_id` int(11) NOT NULL AUTO_INCREMENT,
  `crm_owner` varchar(255) NOT NULL,
  `crm_name` varchar(50) NOT NULL,
  `crm_share` varchar(50) NOT NULL DEFAULT '',
  `crm_model` varchar(50) NOT NULL,
  `crm_clothing` varchar(1500) NOT NULL,
  `crm_accessories` varchar(1500) NOT NULL,
  PRIMARY KEY (`crm_id`),
  KEY `crm_owner` (`crm_owner`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `crm_outfits_job` (
  `crm_id` int(11) NOT NULL AUTO_INCREMENT,
  `crm_owner` varchar(255) NOT NULL,
  `crm_name` varchar(50) NOT NULL,
  `crm_grades` varchar(255) NOT NULL DEFAULT '',
  `crm_model` varchar(50) NOT NULL,
  `crm_clothing` varchar(1500) NOT NULL,
  `crm_accessories` varchar(1500) NOT NULL,
  PRIMARY KEY (`crm_id`),
  KEY `crm_owner` (`crm_owner`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `crm_outfits_job` (`crm_id`, `crm_owner`, `crm_name`, `crm_grades`, `crm_model`, `crm_clothing`, `crm_accessories`) VALUES
(1, 'police', 'Recruit', '[0]', 'mp_m_freemode_01', '[{\"crm_style\":0,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":0,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":1,\"crm_texture\":0},{\"crm_style\":19,\"crm_id\":3,\"crm_texture\":0},{\"crm_style\":35,\"crm_id\":4,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":5,\"crm_texture\":0},{\"crm_style\":51,\"crm_id\":6,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":7,\"crm_texture\":0},{\"crm_style\":59,\"crm_id\":8,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":9,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":10,\"crm_texture\":0},{\"crm_style\":55,\"crm_id\":11,\"crm_texture\":0}]', '[{\"crm_style\":-1,\"crm_id\":0,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":1,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":2,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":6,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":7,\"crm_texture\":-1}]'),
(2, 'police', 'Officer', '[0,1]', 'mp_m_freemode_01', '[{\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":0,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":1,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":3,\"crm_texture\":0,\"crm_style\":19},{\"crm_id\":4,\"crm_texture\":0,\"crm_style\":35},{\"crm_id\":5,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":6,\"crm_texture\":0,\"crm_style\":51},{\"crm_id\":7,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":8,\"crm_texture\":0,\"crm_style\":58},{\"crm_id\":9,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":10,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":11,\"crm_texture\":0,\"crm_style\":55}]', '[{\"crm_id\":0,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":1,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":2,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":6,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":7,\"crm_texture\":-1,\"crm_style\":-1}]'),
(3, 'police', 'Sergeant', '[0,1,2]', 'mp_m_freemode_01', '[{\"crm_texture\":0,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":0,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":1,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":3,\"crm_style\":20},{\"crm_texture\":0,\"crm_id\":4,\"crm_style\":35},{\"crm_texture\":0,\"crm_id\":5,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":6,\"crm_style\":51},{\"crm_texture\":0,\"crm_id\":7,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":8,\"crm_style\":58},{\"crm_texture\":0,\"crm_id\":9,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":10,\"crm_style\":0},{\"crm_texture\":0,\"crm_id\":11,\"crm_style\":317}]', '[{\"crm_texture\":-1,\"crm_id\":0,\"crm_style\":-1},{\"crm_texture\":-1,\"crm_id\":1,\"crm_style\":-1},{\"crm_texture\":-1,\"crm_id\":2,\"crm_style\":-1},{\"crm_texture\":-1,\"crm_id\":6,\"crm_style\":-1},{\"crm_texture\":-1,\"crm_id\":7,\"crm_style\":-1}]'),
(4, 'police', 'Lieutenant', '[0,1,2,3]', 'mp_m_freemode_01', '[{\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":0,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":1,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":3,\"crm_style\":19,\"crm_texture\":0},{\"crm_id\":4,\"crm_style\":25,\"crm_texture\":0},{\"crm_id\":5,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":6,\"crm_style\":51,\"crm_texture\":0},{\"crm_id\":7,\"crm_style\":125,\"crm_texture\":0},{\"crm_id\":8,\"crm_style\":122,\"crm_texture\":0},{\"crm_id\":9,\"crm_style\":11,\"crm_texture\":1},{\"crm_id\":10,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":11,\"crm_style\":242,\"crm_texture\":0}]', '[{\"crm_id\":0,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":1,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":2,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":6,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":7,\"crm_style\":-1,\"crm_texture\":-1}]'),
(5, 'police', 'Chief', '[0,1,2,3,4]', 'mp_m_freemode_01', '[{\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":0,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":1,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":3,\"crm_texture\":0,\"crm_style\":35},{\"crm_id\":4,\"crm_texture\":0,\"crm_style\":24},{\"crm_id\":5,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":6,\"crm_texture\":0,\"crm_style\":21},{\"crm_id\":7,\"crm_texture\":0,\"crm_style\":128},{\"crm_id\":8,\"crm_texture\":0,\"crm_style\":32},{\"crm_id\":9,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":10,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":11,\"crm_texture\":0,\"crm_style\":29}]', '[{\"crm_id\":0,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":1,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":2,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":6,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":7,\"crm_texture\":-1,\"crm_style\":-1}]'),
(6, 'ambulance', 'Recruit', '[0]', 'mp_m_freemode_01', '[{\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":0,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":1,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":3,\"crm_texture\":0,\"crm_style\":79},{\"crm_id\":4,\"crm_texture\":0,\"crm_style\":22},{\"crm_id\":5,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":6,\"crm_texture\":0,\"crm_style\":25},{\"crm_id\":7,\"crm_texture\":0,\"crm_style\":126},{\"crm_id\":8,\"crm_texture\":3,\"crm_style\":72},{\"crm_id\":9,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":10,\"crm_texture\":0,\"crm_style\":57},{\"crm_id\":11,\"crm_texture\":0,\"crm_style\":249}]', '[{\"crm_id\":0,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":1,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":2,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":6,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":7,\"crm_texture\":-1,\"crm_style\":-1}]'),
(7, 'ambulance', 'Paramedic', '[0,1]', 'mp_m_freemode_01', '[{\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":0,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":1,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":3,\"crm_style\":74,\"crm_texture\":0},{\"crm_id\":4,\"crm_style\":173,\"crm_texture\":0},{\"crm_id\":5,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":6,\"crm_style\":25,\"crm_texture\":0},{\"crm_id\":7,\"crm_style\":126,\"crm_texture\":0},{\"crm_id\":8,\"crm_style\":129,\"crm_texture\":0},{\"crm_id\":9,\"crm_style\":0,\"crm_texture\":0},{\"crm_id\":10,\"crm_style\":57,\"crm_texture\":0},{\"crm_id\":11,\"crm_style\":424,\"crm_texture\":0}]', '[{\"crm_id\":0,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":1,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":2,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":6,\"crm_style\":-1,\"crm_texture\":-1},{\"crm_id\":7,\"crm_style\":-1,\"crm_texture\":-1}]'),
(8, 'ambulance', 'Doctor', '[0,1,2]', 'mp_m_freemode_01', '[{\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":0,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":1,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":3,\"crm_texture\":0,\"crm_style\":81},{\"crm_id\":4,\"crm_texture\":0,\"crm_style\":24},{\"crm_id\":5,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":6,\"crm_texture\":0,\"crm_style\":21},{\"crm_id\":7,\"crm_texture\":0,\"crm_style\":126},{\"crm_id\":8,\"crm_texture\":0,\"crm_style\":15},{\"crm_id\":9,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":10,\"crm_texture\":0,\"crm_style\":0},{\"crm_id\":11,\"crm_texture\":0,\"crm_style\":321}]', '[{\"crm_id\":0,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":1,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":2,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":6,\"crm_texture\":-1,\"crm_style\":-1},{\"crm_id\":7,\"crm_texture\":-1,\"crm_style\":-1}]'),
(9, 'ambulance', 'Surgeon', '[0,1,2,3]', 'mp_m_freemode_01', '[{\"crm_style\":0,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":0,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":1,\"crm_texture\":0},{\"crm_style\":85,\"crm_id\":3,\"crm_texture\":0},{\"crm_style\":96,\"crm_id\":4,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":5,\"crm_texture\":0},{\"crm_style\":42,\"crm_id\":6,\"crm_texture\":0},{\"crm_style\":127,\"crm_id\":7,\"crm_texture\":0},{\"crm_style\":129,\"crm_id\":8,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":9,\"crm_texture\":0},{\"crm_style\":58,\"crm_id\":10,\"crm_texture\":0},{\"crm_style\":250,\"crm_id\":11,\"crm_texture\":0}]', '[{\"crm_style\":-1,\"crm_id\":0,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":1,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":2,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":6,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":7,\"crm_texture\":-1}]'),
(10, 'ambulance', 'Chief', '[0,1,2,3,4]', 'mp_m_freemode_01', '[{\"crm_style\":0,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":0,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":1,\"crm_texture\":0},{\"crm_style\":82,\"crm_id\":3,\"crm_texture\":0},{\"crm_style\":24,\"crm_id\":4,\"crm_texture\":6},{\"crm_style\":0,\"crm_id\":5,\"crm_texture\":0},{\"crm_style\":42,\"crm_id\":6,\"crm_texture\":0},{\"crm_style\":127,\"crm_id\":7,\"crm_texture\":0},{\"crm_style\":31,\"crm_id\":8,\"crm_texture\":14},{\"crm_style\":0,\"crm_id\":9,\"crm_texture\":0},{\"crm_style\":0,\"crm_id\":10,\"crm_texture\":0},{\"crm_style\":30,\"crm_id\":11,\"crm_texture\":7}]', '[{\"crm_style\":-1,\"crm_id\":0,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":1,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":2,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":6,\"crm_texture\":-1},{\"crm_style\":-1,\"crm_id\":7,\"crm_texture\":-1}]');
